<?php

namespace App\Agent;

use Symfony\Component\Process\Process;

class ToolMaker
{
    private const BLOCKED_PATTERN = '/\b(exec|system|shell_exec|passthru|proc_open|popen|pcntl_exec|eval|assert)\s*\(/i';

    /**
     * @param array<int, string> $builtInNames
     */
    public function __construct(
        private string $generatedToolsPath,
        private array $builtInNames,
    ) {
    }

    /**
     * Validate and write a generated tool file.
     *
     * @param array<string, mixed> $schema
     * @return array{ok: bool, errors: array<int, string>, file?: string}
     */
    public function make(string $name, string $description, array $schema, string $code): array
    {
        $errors = $this->validate($name, $schema, $code);

        if ($errors !== []) {
            return ['ok' => false, 'errors' => $errors];
        }

        $source = $this->render($name, $description, $schema, $code);

        if (($lintError = $this->lint($source)) !== null) {
            return ['ok' => false, 'errors' => ["Generated PHP does not compile: {$lintError}"]];
        }

        if (! is_dir($this->generatedToolsPath)) {
            mkdir($this->generatedToolsPath, 0777, true);
        }

        $file = $this->generatedToolsPath.'/'.$name.'.php';
        file_put_contents($file, $source);

        return ['ok' => true, 'errors' => [], 'file' => $file];
    }

    /**
     * @param array<string, mixed> $schema
     * @return array<int, string>
     */
    public function validate(string $name, array $schema, string $code): array
    {
        $errors = [];

        if (! preg_match('/^[a-z][a-z0-9_]*$/', $name) || strlen($name) > 64) {
            $errors[] = 'Tool name must be snake_case (lowercase letters, digits, underscores) and at most 64 characters.';
        }

        if (in_array($name, $this->builtInNames, true)) {
            $errors[] = "Tool name [{$name}] collides with a built-in tool.";
        }

        if (is_file($this->generatedToolsPath.'/'.$name.'.php')) {
            $errors[] = "A generated tool named [{$name}] already exists. Pick a different name.";
        }

        if (function_exists($name)) {
            $errors[] = "A PHP function named [{$name}] already exists. Pick a different name.";
        }

        if (trim($code) === '') {
            $errors[] = 'Tool code must not be empty.';
        }

        if (str_contains($code, '<?php') || str_contains($code, '<?=')) {
            $errors[] = 'Tool code must be a function body only, without a <?php tag.';
        }

        if (preg_match(self::BLOCKED_PATTERN, $code, $match)) {
            $errors[] = "Tool code calls blocked function [{$match[1]}]. Shell execution and eval are not allowed.";
        }

        if (str_contains($code, '`')) {
            $errors[] = 'Tool code must not use backtick shell execution.';
        }

        foreach (array_keys($schema['properties'] ?? []) as $property) {
            if (! preg_match('/^[a-z_][a-z0-9_]*$/i', (string) $property)) {
                $errors[] = "Schema property [{$property}] is not a valid PHP parameter name.";
            }
        }

        return $errors;
    }

    /**
     * @param array<string, mixed> $schema
     */
    private function render(string $name, string $description, array $schema, string $code): string
    {
        $parameters = $schema;
        $parameters['type'] = $parameters['type'] ?? 'object';
        $parameters['properties'] = $parameters['properties'] ?? [];

        $definition = [
            'type' => 'function',
            'function' => [
                'name' => $name,
                'description' => $description,
                'parameters' => $parameters,
            ],
        ];

        $signature = $this->signature($schema);

        $body = implode("\n", array_map(
            fn (string $line) => $line === '' ? '' : '        '.$line,
            explode("\n", str_replace("\r\n", "\n", trim($code, "\n")))
        ));

        $export = var_export($definition, true);

        return <<<PHP
<?php

// Generated by make_tool. Do not edit by hand unless you know why.

\$toolDefinition_{$name} = {$export};

if (! function_exists('{$name}')) {
    function {$name}({$signature})
    {
{$body}
    }
}

PHP;
    }

    /**
     * Build the function signature from the schema: required parameters first
     * (PHP demands it), optional parameters default to null.
     *
     * @param array<string, mixed> $schema
     */
    private function signature(array $schema): string
    {
        $properties = array_keys($schema['properties'] ?? []);
        $required = $schema['required'] ?? [];

        $requiredParams = array_filter($properties, fn ($p) => in_array($p, $required, true));
        $optionalParams = array_filter($properties, fn ($p) => ! in_array($p, $required, true));

        return implode(', ', array_merge(
            array_map(fn ($p) => "\${$p}", $requiredParams),
            array_map(fn ($p) => "\${$p} = null", $optionalParams),
        ));
    }

    private function lint(string $source): ?string
    {
        $tmp = tempnam(sys_get_temp_dir(), 'agent_tool_');
        file_put_contents($tmp, $source);

        try {
            $process = new Process([PHP_BINARY, '-l', $tmp]);
            $process->run();

            if ($process->isSuccessful()) {
                return null;
            }

            return trim($process->getOutput().' '.$process->getErrorOutput());
        } finally {
            @unlink($tmp);
        }
    }
}
