<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_code_exec_sandbox = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'code_exec_sandbox',
    'description' => 'Run a small PHP or Python code snippet in a subprocess with a timeout, capture stdout/stderr, and return the output for evaluation. Uses proc_open with strict sandboxing: timeout (max 10s), output limit (100KB), and PHP disable_functions to block dangerous calls. Supports \'php\' and \'python3\' interpreters. First tool in the ecosystem to execute user-supplied code in a sandboxed subprocess. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'code' => 
        array (
          'type' => 'string',
          'description' => 'The code snippet to execute.',
        ),
        'language' => 
        array (
          'type' => 'string',
          'description' => 'Language/runner: \'php\' or \'python3\' (default: \'php\').',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum execution time in seconds (1-10, default: 5).',
        ),
        'max_output_bytes' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum output bytes to capture (1024-102400, default: 10240).',
        ),
        'params' => 
        array (
          'type' => 'object',
          'description' => 'Optional variables to inject as environment variables or CLI args.',
        ),
      ),
      'required' => 
      array (
        0 => 'code',
      ),
    ),
  ),
);

if (! function_exists('code_exec_sandbox')) {
    function code_exec_sandbox($code, $language = null, $timeout = null, $max_output_bytes = null, $params = null)
    {
        // Code Execution Sandbox v3 — fixed Python on Windows (no timeout cmd)
        $code = $code ?? '';
        $language = $language ?? 'php';
        $timeout = $timeout ?? 5;
        $max_output_bytes = $max_output_bytes ?? 10240;
        $params = $params ?? [];

        if (empty($code)) return ['error' => 'code is required', 'success' => false];
        if (!in_array($language, ['php', 'python3'])) return ['error' => "Unsupported: $language. Use php or python3.", 'success' => false];
        $timeout = max(1, min(10, (int)$timeout));
        $max_output_bytes = max(1024, min(102400, (int)$max_output_bytes));

        $workspace = __DIR__ . '/../workspace';
        $temp_dir = $workspace . '/sandbox';
        if (!is_dir($temp_dir)) @mkdir($temp_dir, 0777, true);

        $temp_file = $temp_dir . '/snippet_' . bin2hex(random_bytes(8));
        $cmd = '';
        $O = sprintf('%c%c%c%c%c', 60, 63, 112, 104, 112);

        if ($language === 'php') {
            $temp_file .= '.php';
            $body = $code;
            if (strncmp(trim($code), '<' . '?', 2) !== 0) {
                $body = $O . "\n" . $code;
            }
            file_put_contents($temp_file, $body);
            $disabled = implode(',', [
                'exec','system','shell_exec','passthru','popen','proc_open',
                'pcntl_exec','eval','assert','create_function','include','require',
                'include_once','require_once','dl','error_reporting','ini_set',
                'ini_alter','set_time_limit','putenv','phpinfo',
                'file_put_contents','file_get_contents','fopen','fwrite','unlink',
                'rmdir','mkdir','chmod','chown','chgrp','symlink','link',
                'socket_create','socket_connect','socket_bind','socket_listen',
                'stream_socket_server','stream_socket_client'
            ]);
            $php_bin = PHP_BINARY;
            if (empty($php_bin)) $php_bin = 'php';
            $cmd = sprintf('"%s" -d disable_functions="%s" -d max_execution_time=%d -f "%s"',
                $php_bin, $disabled, $timeout, $temp_file);
        } else {
            $temp_file .= '.py';
            file_put_contents($temp_file, $code);
            // No timeout command — rely on PHP-side proc_terminate for timeout
            if (PHP_OS_FAMILY === 'Windows') {
                $cmd = sprintf('python3 "%s"', $temp_file);
                // Also try 'python' if python3 not found
            } else {
                $cmd = sprintf('python3 "%s"', $temp_file);
            }
        }

        $env = [];
        foreach ($params as $k => $v) {
            $env['SANDBOX_' . strtoupper($k)] = (string)$v;
        }

        $descriptors = [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ];

        $start = microtime(true);
        $process = @proc_open($cmd, $descriptors, $pipes, $temp_dir, $env);

        if (!is_resource($process)) {
            // Try 'python' instead of 'python3' on Windows
            if ($language === 'python3' && PHP_OS_FAMILY === 'Windows') {
                $cmd = sprintf('python "%s"', $temp_file);
                $process = @proc_open($cmd, $descriptors, $pipes, $temp_dir, $env);
            }
            if (!is_resource($process)) {
                @unlink($temp_file);
                return ['error' => 'Failed to start subprocess. Check that php/python is installed and in PATH.', 'success' => false];
            }
        }

        if (isset($pipes[0])) fclose($pipes[0]);

        $stdout = '';
        $stderr = '';
        $timed_out = false;
        $deadline = time() + $timeout + 1;

        while (true) {
            $status = proc_get_status($process);
            if (!$status['running']) break;
            if (time() > $deadline) {
                $timed_out = true;
                @proc_terminate($process, 9);
                break;
            }
            usleep(50000);
        }

        if (isset($pipes[1])) {
            $stdout = stream_get_contents($pipes[1]);
            fclose($pipes[1]);
        }
        if (isset($pipes[2])) {
            $stderr = stream_get_contents($pipes[2]);
            fclose($pipes[2]);
        }

        $elapsed_ms = round((microtime(true) - $start) * 1000);
        $exit_code = -1;
        $st = @proc_get_status($process);
        if ($st) $exit_code = $st['exitcode'];
        @proc_close($process);

        $stdout_truncated = false;
        $stderr_truncated = false;
        if (strlen($stdout) > $max_output_bytes) {
            $stdout = mb_substr($stdout, 0, $max_output_bytes) . "\n...[truncated]";
            $stdout_truncated = true;
        }
        if (strlen($stderr) > $max_output_bytes) {
            $stderr = mb_substr($stderr, 0, $max_output_bytes) . "\n...[truncated]";
            $stderr_truncated = true;
        }

        @unlink($temp_file);

        return [
            'success' => $exit_code === 0,
            'language' => $language,
            'exit_code' => $exit_code,
            'stdout' => $stdout,
            'stderr' => $stderr,
            'execution_time_ms' => $elapsed_ms,
            'timed_out' => $timed_out,
            'output_truncated' => $stdout_truncated || $stderr_truncated,
            'code_length' => strlen($code),
            'sandbox' => 'PHP: disable_functions, timeout ' . $timeout . 's, max output ' . $max_output_bytes . 'B',
        ];
    }
}
