<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_color_converter = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'color_converter',
    'description' => 'Convert colors between hex, RGB, HSL, and HSV formats. Accepts any format and returns all others. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'color' => 
        array (
          'type' => 'string',
          'description' => 'Color in any format: hex \'#ff3366\', \'ff3366\', \'fff\'; or rgb \'rgb(255,51,102)\'; or hsl \'hsl(340,100%,60%)\'; or hsv \'hsv(340,80%,100%)\'',
        ),
        'output_format' => 
        array (
          'type' => 'string',
          'description' => 'Optional: \'hex\',\'rgb\',\'hsl\',\'hsv\',\'all\' to return one specific format. Default: \'all\'.',
        ),
      ),
      'required' => 
      array (
        0 => 'color',
      ),
    ),
  ),
);

if (! function_exists('color_converter')) {
    function color_converter($color, $output_format = null)
    {
        // Parse incoming color
        $format = $output_format ?? 'all';
        $allowed = ['hex','rgb','hsl','hsv','all'];
        if (!in_array($format, $allowed)) {
            return json_encode(['error' => "Invalid output_format. Must be one of: " . implode(', ', $allowed)]);
        }

        $r = $g = $b = null;

        // Try hex
        $c = trim($color);
        if ($c[0] === '#') $c = substr($c, 1);
        if (preg_match('/^[0-9a-fA-F]{6}$/', $c) || preg_match('/^[0-9a-fA-F]{3}$/', $c)) {
            if (strlen($c) === 3) {
                $c = $c[0].$c[0].$c[1].$c[1].$c[2].$c[2];
            }
            $r = hexdec(substr($c, 0, 2));
            $g = hexdec(substr($c, 2, 2));
            $b = hexdec(substr($c, 4, 2));
        }
        // Try rgb()
        elseif (preg_match('/^rgb\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/i', $color, $m)) {
            $r = (int)$m[1];
            $g = (int)$m[2];
            $b = (int)$m[3];
        }
        // Try hsl()
        elseif (preg_match('/^hsl\s*\(\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)%?\s*,\s*(\d+(?:\.\d+)?)%?\s*\)$/i', $color, $m)) {
            $h = (float)$m[1];
            $s = (float)$m[2] / 100;
            $l = (float)$m[3] / 100;
            // HSL -> RGB
            $c2 = (1 - abs(2 * $l - 1)) * $s;
            $x = $c2 * (1 - abs(fmod($h / 60, 2) - 1));
            $m2 = $l - $c2 / 2;
            if ($h < 60) { $r1 = $c2; $g1 = $x; $b1 = 0; }
            elseif ($h < 120) { $r1 = $x; $g1 = $c2; $b1 = 0; }
            elseif ($h < 180) { $r1 = 0; $g1 = $c2; $b1 = $x; }
            elseif ($h < 240) { $r1 = 0; $g1 = $x; $b1 = $c2; }
            elseif ($h < 300) { $r1 = $x; $g1 = 0; $b1 = $c2; }
            else { $r1 = $c2; $g1 = 0; $b1 = $x; }
            $r = (int)round(($r1 + $m2) * 255);
            $g = (int)round(($g1 + $m2) * 255);
            $b = (int)round(($b1 + $m2) * 255);
        }
        // Try hsv()
        elseif (preg_match('/^hsv\s*\(\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)%?\s*,\s*(\d+(?:\.\d+)?)%?\s*\)$/i', $color, $m)) {
            $h = (float)$m[1];
            $s = (float)$m[2] / 100;
            $v = (float)$m[3] / 100;
            // HSV -> RGB
            $c2 = $v * $s;
            $x = $c2 * (1 - abs(fmod($h / 60, 2) - 1));
            $m2 = $v - $c2;
            if ($h < 60) { $r1 = $c2; $g1 = $x; $b1 = 0; }
            elseif ($h < 120) { $r1 = $x; $g1 = $c2; $b1 = 0; }
            elseif ($h < 180) { $r1 = 0; $g1 = $c2; $b1 = $x; }
            elseif ($h < 240) { $r1 = 0; $g1 = $x; $b1 = $c2; }
            elseif ($h < 300) { $r1 = $x; $g1 = 0; $b1 = $c2; }
            else { $r1 = $c2; $g1 = 0; $b1 = $x; }
            $r = (int)round(($r1 + $m2) * 255);
            $g = (int)round(($g1 + $m2) * 255);
            $b = (int)round(($b1 + $m2) * 255);
        }

        if ($r === null) {
            return json_encode(['error' => 'Could not parse color format. Try: #ff3366, rgb(255,51,102), hsl(340,100%,60%), or hsv(340,80%,100%)']);
        }

        // Clamp
        $r = max(0, min(255, $r));
        $g = max(0, min(255, $g));
        $b = max(0, min(255, $b));

        // Convert to hex
        $hex = '#' . str_pad(dechex($r), 2, '0', STR_PAD_LEFT)
                    . str_pad(dechex($g), 2, '0', STR_PAD_LEFT)
                    . str_pad(dechex($b), 2, '0', STR_PAD_LEFT);

        // RGB to HSL
        $rf = $r / 255;
        $gf = $g / 255;
        $bf = $b / 255;
        $max = max($rf, $gf, $bf);
        $min = min($rf, $gf, $bf);
        $delta = $max - $min;

        $h = 0;
        $s = 0;
        $l = ($max + $min) / 2;

        if ($delta > 0.0001) {
            $s = $l <= 0.5 ? $delta / ($max + $min) : $delta / (2 - $max - $min);
            if ($max === $rf) {
                $h = 60 * fmod(($gf - $bf) / $delta, 6);
            } elseif ($max === $gf) {
                $h = 60 * (($bf - $rf) / $delta + 2);
            } else {
                $h = 60 * (($rf - $gf) / $delta + 4);
            }
            if ($h < 0) $h += 360;
        }
        $hsl_h = round($h, 1);
        $hsl_s = round($s * 100, 1);
        $hsl_l = round($l * 100, 1);

        // RGB to HSV
        $hsv_s = 0;
        $hsv_v = 0;
        $h2 = 0;
        if ($max > 0.0001) {
            $hsv_s = ($delta / $max) * 100;
        }
        $hsv_v = $max * 100;
        if ($delta > 0.0001) {
            if ($max === $rf) {
                $h2 = 60 * fmod(($gf - $bf) / $delta, 6);
            } elseif ($max === $gf) {
                $h2 = 60 * (($bf - $rf) / $delta + 2);
            } else {
                $h2 = 60 * (($rf - $gf) / $delta + 4);
            }
            if ($h2 < 0) $h2 += 360;
        }

        $hsv_h = round($h2, 1);
        $hsv_s = round($hsv_s, 1);
        $hsv_v = round($hsv_v, 1);

        $result = [
            'hex' => $hex,
            'rgb' => "rgb({$r},{$g},{$b})",
            'hsl' => "hsl({$hsl_h},{$hsl_s}%,{$hsl_l}%)",
            'hsv' => "hsv({$hsv_h},{$hsv_s}%,{$hsv_v}%)",
            'components' => [
                'r' => $r, 'g' => $g, 'b' => $b,
                'hue' => $hsl_h, 'saturation' => $hsl_s, 'lightness' => $hsl_l,
                'hue_hsv' => $hsv_h, 'saturation_hsv' => $hsv_s, 'value' => $hsv_v,
            ]
        ];

        if ($format !== 'all') {
            return json_encode(['input' => $color, 'output_format' => $format, 'value' => $result[$format]]);
        }

        return json_encode(['input' => $color, 'result' => $result]);
    }
}
