<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_conway_game_of_life = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'conway_game_of_life',
    'description' => 'Simulate Conway\'s Game of Life cellular automaton on a 2D grid. Takes a grid pattern and number of steps, returns resulting grid. Supports preset starting patterns (glider, blinker, block, beacon, pulsar, glider_gun, random). Output grid can be piped to emoji_art_renderer or data_heatmap. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'pattern' => 
        array (
          'type' => 'string',
          'description' => 'Preset pattern: \'glider\', \'blinker\', \'block\', \'beacon\', \'pulsar\', \'glider_gun\', \'random\'. Or \'custom\' to provide your own grid.',
        ),
        'width' => 
        array (
          'type' => 'integer',
          'description' => 'Grid width in cells (default: 20)',
        ),
        'height' => 
        array (
          'type' => 'integer',
          'description' => 'Grid height in cells (default: 20)',
        ),
        'steps' => 
        array (
          'type' => 'integer',
          'description' => 'Number of simulation steps to run (default: 10)',
        ),
        'custom_grid' => 
        array (
          'type' => 'array',
          'description' => 'Custom 2D array (array of rows of 0/1 values). Used when pattern=\'custom\'.',
          'items' => 
          array (
            'type' => 'array',
            'items' => 
            array (
              'type' => 'integer',
            ),
          ),
        ),
        'alive_char' => 
        array (
          'type' => 'string',
          'description' => 'Character for alive cells (default: \'█\')',
        ),
        'dead_char' => 
        array (
          'type' => 'string',
          'description' => 'Character for dead cells (default: \' \')',
        ),
      ),
    ),
  ),
);

if (! function_exists('conway_game_of_life')) {
    function conway_game_of_life($pattern = null, $width = null, $height = null, $steps = null, $custom_grid = null, $alive_char = null, $dead_char = null)
    {
        // Conway's Game of Life
        $pattern=isset($pattern)?(string)$pattern:'glider';
        $width=isset($width)?min(max((int)$width,3),100):20;
        $height=isset($height)?min(max((int)$height,3),100):20;
        $steps=isset($steps)?min(max((int)$steps,0),500):10;
        $alive=isset($alive_char)?(string)$alive_char:'█';
        $dead=isset($dead_char)?(string)$dead_char:' ';

        $grid=[];

        // Init grid from pattern or custom
        if($pattern==='custom'&&isset($custom_grid)&&is_array($custom_grid)){
            $grid=$custom_grid;
        }else{
            $grid=array_fill(0,$height,array_fill(0,$width,0));
            $patterns=[
                'glider'=>[[0,1],[1,2],[2,0],[2,1],[2,2]],
                'blinker'=>[[1,0],[1,1],[1,2]],
                'block'=>[[0,0],[0,1],[1,0],[1,1]],
                'beacon'=>[[0,0],[0,1],[1,0],[2,3],[3,2],[3,3]],
                'pulsar'=>[[0,2],[0,3],[0,4],[2,0],[2,5],[3,0],[3,5],[4,0],[4,5],[5,2],[5,3],[5,4]],
                'glider_gun'=>[[0,24],[1,22],[1,24],[2,12],[2,13],[2,20],[2,21],[2,34],[2,35],[3,11],[3,15],[3,20],[3,21],[3,34],[3,35],[4,0],[4,1],[4,10],[4,16],[4,20],[4,21],[5,0],[5,1],[5,10],[5,14],[5,16],[5,17],[5,22],[5,24],[6,10],[6,16],[6,24],[7,11],[7,15],[8,12],[8,13]],
            ];
            if(isset($patterns[$pattern])){
                foreach($patterns[$pattern] as$cell){
                    $r=$cell[0];$c=$cell[1];
                    if($r<$height&&$c<$width)$grid[$r][$c]=1;
                }
            }else{
                // Random
                for($r=0;$r<$height;$r++)
                    for($c=0;$c<$width;$c++)
                        $grid[$r][$c]=rand(0,1);
            }
        }

        // Simulate
        $history=[];
        for($s=0;$s<$steps;$s++){
            $new=array_fill(0,$height,array_fill(0,$width,0));
            $alive_count=0;
            for($r=0;$r<$height;$r++){
                for($c=0;$c<$width;$c++){
                    $n=0;
                    for($dr=-1;$dr<=1;$dr++)
                        for($dc=-1;$dc<=1;$dc++)
                            if(!($dr===0&&$dc===0)){
                                $nr=$r+$dr;$nc=$c+$dc;
                                if($nr>=0&&$nr<$height&&$nc>=0&&$nc<$width&&$grid[$nr][$nc])$n++;
                            }
                    if($grid[$r][$c]){$new[$r][$c]=($n===2||$n===3)?1:0;}
                    else{$new[$r][$c]=($n===3)?1:0;}
                    if($new[$r][$c])$alive_count++;
                }
            }
            $history[]=['step'=>$s+1,'alive'=>$alive_count];
            if($alive_count===0)break;
            $grid=$new;
        }

        // Render
        $out='';
        for($r=0;$r<$height;$r++){
            for($c=0;$c<$width;$c++)$out.=$grid[$r][$c]?$alive:$dead;
            $out.="\n";
        }

        return['success'=>true,'pattern'=>$pattern,'steps_taken'=>count($history),'final_alive'=>$history?end($history)['alive']:0,'grid_size'=>"{$width}x{$height}",'grid'=>$out,'history'=>$history];
    }
}
