<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_coordinate_grid_renderer = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'coordinate_grid_renderer',
    'description' => 'Read a text_coordinate_grid and render it as a 2D array ready for emoji_art_renderer. Scans the bounding box of all placed tokens, fills empty cells with a background character, and returns a 2D grid of tokens. Pure function (reads from the persistent coordinate grid).',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'grid_name' => 
        array (
          'type' => 'string',
          'description' => 'Name of the coordinate grid to render.',
        ),
        'fill' => 
        array (
          'type' => 'string',
          'description' => 'Character/emoji for empty cells (default: \'⬜\').',
        ),
        'border' => 
        array (
          'type' => 'integer',
          'description' => 'Optional border margin in cells around the content (default: 0).',
        ),
      ),
      'required' => 
      array (
        0 => 'grid_name',
      ),
    ),
  ),
);

if (! function_exists('coordinate_grid_renderer')) {
    function coordinate_grid_renderer($grid_name, $fill = null, $border = null)
    {
        // Match the storage format used by text_coordinate_grid
        $notesDir = __DIR__ . '/../../workspace/notes';
        $filePath = $notesDir . '/' . md5('coord_grid_' . $grid_name) . '.grid.json';
        $fill = $fill ?? '⬜';
        $border = $border ?? 0;

        if (!file_exists($filePath)) {
            return ['error' => 'Grid not found: ' . $grid_name, 'grid' => []];
        }

        $data = json_decode(file_get_contents($filePath), true);
        if (!$data || !is_array($data)) {
            return ['error' => 'Invalid grid data', 'grid' => []];
        }

        $cells = $data;
        if (empty($cells)) {
            return ['error' => 'Empty grid', 'grid' => []];
        }

        // The grid stores cells as associative array with "x,y" keys, each with x,y,token
        // Find bounding box
        $minX = $minY = PHP_INT_MAX;
        $maxX = $maxY = PHP_INT_MIN;
        foreach ($cells as $cell) {
            $x = (int)$cell['x'];
            $y = (int)$cell['y'];
            if ($x < $minX) $minX = $x;
            if ($y < $minY) $minY = $y;
            if ($x > $maxX) $maxX = $x;
            if ($y > $maxY) $maxY = $y;
        }

        // Build lookup by "x,y" key
        $lookup = [];
        foreach ($cells as $cell) {
            $lookup[$cell['x'] . ',' . $cell['y']] = $cell['token'];
        }

        $width = $maxX - $minX + 1 + 2 * $border;
        $height = $maxY - $minY + 1 + 2 * $border;

        $grid = [];
        for ($row = 0; $row < $height; $row++) {
            $gridRow = [];
            for ($col = 0; $col < $width; $col++) {
                $worldX = $minX - $border + $col;
                $worldY = $minY - $border + $row;
                $cellKey = $worldX . ',' . $worldY;
                $gridRow[] = isset($lookup[$cellKey]) ? $lookup[$cellKey] : $fill;
            }
            $grid[] = $gridRow;
        }

        return [
            'grid_name' => $grid_name,
            'grid' => $grid,
            'width' => $width,
            'height' => $height,
            'bounding_box' => ['minX' => $minX, 'minY' => $minY, 'maxX' => $maxX, 'maxY' => $maxY],
            'cells_placed' => count($cells),
        ];
    }
}
