<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_cron_parser = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'cron_parser',
    'description' => 'Parse cron expressions (5-field standard: minute hour dom month dow) and compute the next N execution times. Supports all standard syntax: * (every), */n (every n), n-m (range), n,m,o (list), n-m/step (range with step), month names (JAN-DEC), day names (SUN-SAT). Returns a human-readable description of the schedule and a list of future run times. First scheduling/time-expression tool in the ecosystem. Pure PHP, no extensions. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'expression' => 
        array (
          'type' => 'string',
          'description' => 'Cron expression (5 fields: minute hour day-of-month month day-of-week). E.g. \'*/15 * * * *\', \'0 9 * * 1-5\', \'0 0 1 */3 *\'. Required.',
        ),
        'count' => 
        array (
          'type' => 'integer',
          'description' => 'Number of future run times to compute (1-20, default: 5).',
        ),
        'start_time' => 
        array (
          'type' => 'string',
          'description' => 'Reference time as ISO 8601 string (e.g. \'2025-01-15 08:30:00\'). Default: current time.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (1-10, default: 5).',
        ),
      ),
      'required' => 
      array (
        0 => 'expression',
      ),
    ),
  ),
);

if (! function_exists('cron_parser')) {
    function cron_parser($expression, $count = null, $start_time = null, $timeout = null)
    {
        $expression = trim($expression ?? '');
        $count = $count ?? 5;
        $count = max(1, min(20, (int)$count));
        $start_time = $start_time ?? '';
        $start = microtime(true);

        if (empty($expression)) {
            return ['error' => 'No cron expression provided.'];
        }

        $monthMap = [
            'JAN' => 1, 'FEB' => 2, 'MAR' => 3, 'APR' => 4, 'MAY' => 5, 'JUN' => 6,
            'JUL' => 7, 'AUG' => 8, 'SEP' => 9, 'OCT' => 10, 'NOV' => 11, 'DEC' => 12,
        ];
        $dayMap = [
            'SUN' => 0, 'MON' => 1, 'TUE' => 2, 'WED' => 3, 'THU' => 4, 'FRI' => 5, 'SAT' => 6,
        ];

        $fields = preg_split('/\s+/', $expression);
        if (count($fields) !== 5) {
            return ['error' => 'Cron expression must have exactly 5 fields (minute hour dom month dow). Got ' . count($fields) . ' fields.'];
        }

        // Parse a single cron field into a set of allowed values
        $parseField = function($field, $min, $max, $nameMap = []) {
            $values = [];
            $parts = explode(',', $field);
            foreach ($parts as $part) {
                $part = trim($part);
                $upper = strtoupper($part);
                if (isset($nameMap[$upper])) {
                    $values[] = $nameMap[$upper];
                    continue;
                }
                if (preg_match('/^(.+)\/(\d+)$/', $part, $m)) {
                    $range = $m[1]; $step = max(1, (int)$m[2]);
                    if ($range === '*') {
                        for ($v = $min; $v <= $max; $v += $step) $values[] = $v;
                    } elseif (preg_match('/^(\d+)-(\d+)$/', $range, $rm)) {
                        for ($v = max($min, (int)$rm[1]); $v <= min($max, (int)$rm[2]); $v += $step) $values[] = $v;
                    } else {
                        for ($v = max($min, min($max, (int)$range)); $v <= $max; $v += $step) $values[] = $v;
                    }
                } elseif ($part === '*') {
                    for ($v = $min; $v <= $max; $v++) $values[] = $v;
                } elseif (preg_match('/^(\d+)-(\d+)$/', $part, $m)) {
                    for ($v = max($min, (int)$m[1]); $v <= min($max, (int)$m[2]); $v++) $values[] = $v;
                } else {
                    $v = (int)$part;
                    if ($v >= $min && $v <= $max) $values[] = $v;
                }
            }
            return array_unique($values);
        };

        try {
            $fExpr = $expression;
            foreach ($monthMap as $name => $num) {
                $fExpr = preg_replace('/\b' . $name . '\b/i', (string)$num, $fExpr);
            }
            foreach ($dayMap as $name => $num) {
                $fExpr = preg_replace('/\b' . $name . '\b/i', (string)$num, $fExpr);
            }
            $fFields = preg_split('/\s+/', $fExpr);
            
            $minutes = $parseField($fFields[0], 0, 59);
            $hours = $parseField($fFields[1], 0, 23);
            $daysOfMonth = $parseField($fFields[2], 1, 31);
            $months = $parseField($fFields[3], 1, 12);
            $daysOfWeek = $parseField($fFields[4], 0, 6);
            
            if (empty($minutes) || empty($hours) || empty($daysOfMonth) || empty($months)) {
                return ['error' => 'One or more cron fields resolved to empty set.'];
            }
            
            $hasDomWildcard = ($fFields[2] === '*');
            $hasDowWildcard = ($fFields[4] === '*');
        } catch (\Throwable $e) {
            return ['error' => 'Failed to parse: ' . $e->getMessage()];
        }

        // Start time
        try {
            $current = !empty($start_time) ? new DateTime($start_time) : new DateTime('now');
        } catch (\Throwable $e) {
            return ['error' => 'Invalid start_time: ' . $e->getMessage()];
        }
        $current->setTime((int)$current->format('H'), (int)$current->format('i'), 0);
        $current->modify('+1 minute');

        $runs = [];
        $maxIterations = 1051200; // 2 years of minutes
        $iterations = 0;

        while (count($runs) < $count && $iterations < $maxIterations) {
            $month = (int)$current->format('n');
            $day = (int)$current->format('j');
            $hour = (int)$current->format('G');
            $minute = (int)$current->format('i');
            $dow = (int)$current->format('w');
            
            $dateMatch = in_array($month, $months, true);
            if ($dateMatch) {
                if (!$hasDomWildcard && !$hasDowWildcard) {
                    $dateMatch = in_array($day, $daysOfMonth, true) || in_array($dow, $daysOfWeek, true);
                } elseif ($hasDomWildcard && !$hasDowWildcard) {
                    $dateMatch = in_array($dow, $daysOfWeek, true);
                } elseif (!$hasDomWildcard && $hasDowWildcard) {
                    $dateMatch = in_array($day, $daysOfMonth, true);
                }
            }
            
            if ($dateMatch && in_array($hour, $hours, true) && in_array($minute, $minutes, true)) {
                $runs[] = $current->format('Y-m-d H:i');
            }
            
            $current->modify('+1 minute');
            $iterations++;
        }

        // Describe a field for human-readable output
        $describeField = function($rawField, $vals, $allCount, $name) use ($monthMap, $dayMap) {
            sort($vals);
            if (count($vals) === $allCount) return "every $name";
            if (count($vals) <= 6) {
                return "$name=" . implode(',', $vals);
            }
            // Check if it's a contiguous range
            $isContiguous = ($vals[count($vals)-1] - $vals[0] + 1) === count($vals);
            if ($isContiguous) {
                return "$name={$vals[0]}-{$vals[count($vals)-1]}";
            }
            return "$name=" . implode(',', array_slice($vals, 0, 4)) . '...';
        };

        $parts = [];
        $parts[] = $describeField($fields[0], $minutes, 60, 'minute');
        $parts[] = $describeField($fields[1], $hours, 24, 'hour');
        $parts[] = $describeField($fields[2], $daysOfMonth, 31, 'day');
        $parts[] = $describeField($fields[3], $months, 12, 'month');
        $parts[] = $describeField($fields[4], $daysOfWeek, 7, 'dow');

        $description = implode(', ', $parts);
        $elapsed = round(microtime(true) - $start, 4);

        return [
            'success' => true,
            'expression' => $expression,
            'description' => $description,
            'next_runs' => $runs,
            'count' => count($runs),
            'start_time' => $start_time ?: 'now',
            'fields' => [
                'minute' => array_values($minutes),
                'hour' => array_values($hours),
                'day_of_month' => array_values($daysOfMonth),
                'month' => array_values($months),
                'day_of_week' => array_values($daysOfWeek),
            ],
            'has_wildcard_dom' => $hasDomWildcard,
            'has_wildcard_dow' => $hasDowWildcard,
            'elapsed_seconds' => $elapsed,
        ];
    }
}
