<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_data_quantile_calculator = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'data_quantile_calculator',
    'description' => 'Compute arbitrary quantiles/percentiles from an array of numbers. Supports multiple interpolation methods (linear, lower, upper, nearest, midpoint). Pure function, no side effects. Composes well with data_simulator, math_statistics, data_bin_sorter.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'numbers' => 
        array (
          'type' => 'array',
          'description' => 'Array of numeric values to compute quantiles for',
          'items' => 
          array (
            'type' => 'number',
          ),
        ),
        'probs' => 
        array (
          'type' => 'array',
          'description' => 'Array of probability values (0 to 1) for quantile computation, e.g. [0.25,0.5,0.75]. Default: [0,0.25,0.5,0.75,1]',
          'items' => 
          array (
            'type' => 'number',
          ),
        ),
        'method' => 
        array (
          'type' => 'string',
          'description' => 'Interpolation method: \'linear\' (default R type 7), \'lower\', \'higher\', \'nearest\', \'midpoint\'. Default: \'linear\'.',
        ),
      ),
      'required' => 
      array (
        0 => 'numbers',
      ),
    ),
  ),
);

if (! function_exists('data_quantile_calculator')) {
    function data_quantile_calculator($numbers, $probs = null, $method = null)
    {
        $vals = $numbers;
        $probs = $probs ?? [0, 0.25, 0.5, 0.75, 1];
        $method = $method ?? 'linear';

        if (empty($vals)) {
            return json_encode(['error' => 'Numbers array cannot be empty']);
        }

        $n = count($vals);
        sort($vals);
        $min = $vals[0];
        $max = $vals[$n - 1];

        $validMethods = ['linear', 'lower', 'higher', 'nearest', 'midpoint'];
        if (!in_array($method, $validMethods)) {
            return json_encode(['error' => "Invalid method. Must be one of: " . implode(', ', $validMethods)]);
        }

        $quantiles = [];
        foreach ($probs as $p) {
            if ($p < 0 || $p > 1) {
                return json_encode(['error' => "Probabilities must be between 0 and 1, got $p"]);
            }
            
            // R-type 7 interpolation (used by default in R, numpy)
            $index = ($n - 1) * $p;
            $lo = (int)floor($index);
            $hi = (int)ceil($index);
            $frac = $index - $lo;
            
            if ($method === 'lower') {
                $val = $vals[$lo];
            } elseif ($method === 'higher') {
                $val = $vals[min($hi, $n - 1)];
            } elseif ($method === 'nearest') {
                $idx = (int)round($index);
                $val = $vals[max(0, min($n - 1, $idx))];
            } elseif ($method === 'midpoint') {
                $val = ($vals[$lo] + $vals[min($hi, $n - 1)]) / 2;
            } else {
                // linear interpolation
                if ($lo === $hi || $frac == 0) {
                    $val = $vals[$lo];
                } else {
                    $val = $vals[$lo] * (1 - $frac) + $vals[min($hi, $n - 1)] * $frac;
                }
            }
            
            $quantiles[] = [
                'prob' => $p,
                'value' => round($val, 6),
                'label' => $p == 0.25 ? 'Q1' : ($p == 0.5 ? 'Q2 (median)' : ($p == 0.75 ? 'Q3' : ($p == 0 ? 'minimum' : ($p == 1 ? 'maximum' : $p)))),
            ];
        }

        // Also compute IQR if we have Q1 and Q3
        $iqr = null;
        $q1 = null; $q3 = null;
        foreach ($quantiles as $q) {
            if ($q['prob'] == 0.25) $q1 = $q['value'];
            if ($q['prob'] == 0.75) $q3 = $q['value'];
        }
        if ($q1 !== null && $q3 !== null) {
            $iqr = $q3 - $q1;
        }

        // Identify mild and extreme outliers using IQR
        $outliers = ['mild' => [], 'extreme' => []];
        if ($iqr !== null && $iqr > 0) {
            $lowerFence = $q1 - 1.5 * $iqr;
            $upperFence = $q3 + 1.5 * $iqr;
            $lowerExtreme = $q1 - 3 * $iqr;
            $upperExtreme = $q3 + 3 * $iqr;
            
            foreach ($vals as $v) {
                if ($v < $lowerExtreme || $v > $upperExtreme) {
                    $outliers['extreme'][] = $v;
                } elseif ($v < $lowerFence || $v > $upperFence) {
                    $outliers['mild'][] = $v;
                }
            }
        }

        $summary = [
            'n' => $n,
            'min' => $min,
            'max' => $max,
            'range' => $max - $min,
            'iqr' => $iqr !== null ? round($iqr, 6) : null,
            'median' => $quantiles[array_search(0.5, array_column($quantiles, 'prob'))]['value'] ?? null,
        ];

        return json_encode([
            'method' => $method,
            'quantiles' => $quantiles,
            'summary' => $summary,
            'outliers' => $outliers,
            'sorted_data' => $vals,
        ]);
    }
}
