<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_data_correlator = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'data_correlator',
    'description' => 'Compute Pearson correlation coefficient (r) and p-value approximation between two arrays of numbers. Also returns covariance, means, and standard deviations. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'x' => 
        array (
          'type' => 'array',
          'description' => 'First array (independent variable)',
          'items' => 
          array (
            'type' => 'number',
          ),
        ),
        'y' => 
        array (
          'type' => 'array',
          'description' => 'Second array (dependent variable)',
          'items' => 
          array (
            'type' => 'number',
          ),
        ),
      ),
      'required' => 
      array (
        0 => 'x',
        1 => 'y',
      ),
    ),
  ),
);

if (! function_exists('data_correlator')) {
    function data_correlator($x, $y)
    {
        $nX = count($x);
        $nY = count($y);
        if ($nX !== $nY || $nX < 3) {
            return json_encode(['error' => 'Both arrays must have the same length and at least 3 data points']);
        }
        $n = $nX;

        $sumX = array_sum($x);
        $sumY = array_sum($y);
        $meanX = $sumX / $n;
        $meanY = $sumY / $n;

        $ssX = 0; $ssY = 0; $cov = 0;
        for ($i = 0; $i < $n; $i++) {
            $dx = $x[$i] - $meanX;
            $dy = $y[$i] - $meanY;
            $ssX += $dx * $dx;
            $ssY += $dy * $dy;
            $cov += $dx * $dy;
        }
        $varX = $ssX / ($n - 1);
        $varY = $ssY / ($n - 1);
        $stdX = sqrt($varX);
        $stdY = sqrt($varY);
        $covXY = $cov / ($n - 1);

        // Pearson r
        $denom = sqrt($ssX * $ssY);
        $r = $denom > 0 ? $cov / $denom : 0;
        $r = max(-1, min(1, $r));

        // Approximate p-value using t-distribution (no lgamma - uses simple approximation)
        $t = $r * sqrt(($n - 2) / max(1e-10, (1 - $r * $r)));
        $df = $n - 2;
        $p = 0;
        if ($df > 0 && is_finite($t)) {
            $abs_t = abs($t);
            // Simple approximation of the t-distribution survival function
            // P(T > |t|) using a rational approximation
            $x = $df / ($df + $abs_t * $abs_t);
            // Approximation: P(T > t) ~= exp(-t^2/2) / (sqrt(2*pi)) * (2 + 2/df + ...)
            // This is a rough approximation sufficient for educational purposes
            $p_tail = exp(-$abs_t * $abs_t / 2.0) / sqrt(2.0 * M_PI);
            // Scale factor for degrees of freedom
            $scale = 1.0 + 1.0 / max(1, $df) + 1.0 / max(1, $df * $df);
            $p = 2.0 * min(0.5, $p_tail * $scale); // two-tailed, capped at 1.0
            $p = max(0, min(1, $p));
        }

        // Interpretation
        $interpretation = '';
        if (abs($r) < 0.1) $interpretation = 'negligible correlation';
        elseif (abs($r) < 0.3) $interpretation = 'weak ' . ($r > 0 ? 'positive' : 'negative') . ' correlation';
        elseif (abs($r) < 0.5) $interpretation = 'moderate ' . ($r > 0 ? 'positive' : 'negative') . ' correlation';
        elseif (abs($r) < 0.7) $interpretation = 'strong ' . ($r > 0 ? 'positive' : 'negative') . ' correlation';
        elseif (abs($r) < 0.9) $interpretation = 'very strong ' . ($r > 0 ? 'positive' : 'negative') . ' correlation';
        else $interpretation = 'near-perfect ' . ($r > 0 ? 'positive' : 'negative') . ' correlation';

        return json_encode([
            'n' => $n,
            'pearson_r' => round($r, 6),
            'r_squared' => round($r * $r, 6),
            'p_value_approx' => round($p, 6),
            'significant_at_005' => $p < 0.05,
            'covariance' => round($covXY, 6),
            'mean_x' => round($meanX, 4),
            'mean_y' => round($meanY, 4),
            'std_dev_x' => round($stdX, 4),
            'std_dev_y' => round($stdY, 4),
            'interpretation' => $interpretation,
            'formula' => 'r = cov(X,Y) / (sx * sy)',
        ]);
    }
}
