<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_data_to_report = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'data_to_report',
    'description' => 'Full data-to-report pipeline in one call: runs a SQL query against a SQLite database, generates a bar chart from the results, creates a PDF report with the embedded chart, and returns all file paths. Composes sqlite_query + chart_generator + pdf_generator into a single end-to-end pipeline. First multi-capability composition tool in the ecosystem — demonstrates the power of composing database, graphics, and document generation. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'sql' => 
        array (
          'type' => 'string',
          'description' => 'SQL query to execute (e.g. \'SELECT name, value FROM items ORDER BY value DESC\'). First column = labels, second column = values for the chart.',
        ),
        'db_name' => 
        array (
          'type' => 'string',
          'description' => 'SQLite database filename in workspace (default: \'harvested_data.sqlite\').',
        ),
        'title' => 
        array (
          'type' => 'string',
          'description' => 'Report title (default: \'Data Report\').',
        ),
        'chart_title' => 
        array (
          'type' => 'string',
          'description' => 'Chart title (default: same as report title).',
        ),
        'report_filename' => 
        array (
          'type' => 'string',
          'description' => 'Output PDF filename (default: auto-generated).',
        ),
        'params' => 
        array (
          'type' => 'array',
          'description' => 'Optional parameter values for prepared statement placeholders (?).',
          'items' => 
          (object) array(
          ),
        ),
        'max_rows' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum rows for chart (5-50, default: 15).',
        ),
      ),
      'required' => 
      array (
        0 => 'sql',
      ),
    ),
  ),
);

if (! function_exists('data_to_report')) {
    function data_to_report($sql, $db_name = null, $title = null, $chart_title = null, $report_filename = null, $params = null, $max_rows = null)
    {
        // Data-to-Report Pipeline: SQL -> Chart -> PDF in one call
        $sql = isset($sql) ? (string)$sql : '';
        $db_name = isset($db_name) ? (string)$db_name : 'harvested_data.sqlite';
        $title = isset($title) ? (string)$title : 'Data Report';
        $chart_title = isset($chart_title) ? (string)$chart_title : $title;
        $report_fn = isset($report_filename) ? (string)$report_filename : 'report_' . time() . '.pdf';
        $params = isset($params) ? (array)$params : [];
        $max_rows = isset($max_rows) ? min(max((int)$max_rows, 5), 50) : 15;

        if ($sql === '') return ['error' => 'SQL query is required'];

        // Resolve workspace: tools dir is ../../workspace from tool file location
        $tools_dir = __DIR__;
        $storage_dir = dirname($tools_dir);    // storage/agent
        $agent_dir = dirname($storage_dir);    // storage
        $project_root = dirname($agent_dir);   // project root
        $workspace_dir = $storage_dir . DIRECTORY_SEPARATOR . 'workspace';
        $db_path = $workspace_dir . DIRECTORY_SEPARATOR . $db_name;

        if (!file_exists($db_path)) {
            return ['error' => "Database not found: {$db_name}"];
        }

        $chart_fn = 'chart_' . time() . '.png';
        $chart_path = $workspace_dir . DIRECTORY_SEPARATOR . $chart_fn;
        $report_path = $workspace_dir . DIRECTORY_SEPARATOR . $report_fn;

        try {
            // Phase 1: SQL
            $pdo = new PDO("sqlite:{$db_path}");
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $stmt = $pdo->prepare($sql);
            $stmt->execute($params);
            $rows = $stmt->fetchAll(PDO::FETCH_NUM);
            if (count($rows) === 0) return ['error' => 'Query returned no rows'];
            if (count($rows[0]) < 2) return ['error' => 'Need 2 columns'];
            
            $labels = array_map(fn($r) => (string)$r[0], $rows);
            $values = array_map(fn($r) => (float)$r[1], $rows);
            $total_rows = count($rows);
            if (count($labels) > $max_rows) { $labels = array_slice($labels, 0, $max_rows); $values = array_slice($values, 0, $max_rows); }
            
            // Phase 2: Chart via GD
            if (!extension_loaded('gd')) return ['error' => 'GD not loaded'];
            
            $cw = min(800, max(400, count($labels) * 38 + 80));
            $ch = 300;
            $img = imagecreatetruecolor($cw, $ch);
            if (!$img) return ['error' => 'Image create failed'];
            
            $bg = imagecolorallocate($img,255,255,255);
            $bd = imagecolorallocate($img,200,200,200);
            $bc = imagecolorallocate($img,51,102,204);
            $tc = imagecolorallocate($img,50,50,50);
            $gc = imagecolorallocate($img,230,230,230);
            $tl = imagecolorallocate($img,30,30,30);
            $ax = imagecolorallocate($img,80,80,80);
            
            imagefill($img,0,0,$bg);
            $ml=60;$mr=20;$mt=50;$mb=45;$pw=$cw-$ml-$mr;$ph=$ch-$mt-$mb;
            
            $tlen = strlen($chart_title);
            $tfont = $tlen > 30 ? 2 : 5;
            $tx = max(2, (int)(($cw - $tlen * imagefontwidth($tfont))/2));
            imagestring($img, $tfont, $tx, 8, $chart_title, $tl);
            
            $mv = max(array_map('abs',$values)); if($mv==0)$mv=1;
            $scale = $ph/$mv;
            
            for($i=0;$i<=5;$i++){
                $gy=(int)($mt+$ph-($ph*$i/5));
                imageline($img,$ml,$gy,$cw-$mr,$gy,$gc);
                $v=$mv*$i/5;
                $vl=$v>=1000000?round($v/1000000,1).'M':($v>=1000?round($v/1000,1).'K':(int)$v);
                imagestring($img,1,5,$gy-4,(string)$vl,$ax);
            }
            
            $nc = count($values);
            $bw = max(3,min(35,(int)(($pw-10)/$nc-2)));
            $sp = max(2,min(4,(int)(($pw-$bw*$nc)/($nc+1))));
            $x=$ml+$sp;
            
            for($i=0;$i<$nc;$i++){
                $bh=(int)($values[$i]*$scale);
                $by=$mt+$ph-$bh;
                imagefilledrectangle($img,$x,$by,$x+$bw,$mt+$ph,$bc);
                imagerectangle($img,$x,$by,$x+$bw,$mt+$ph,$bd);
                $lb=strlen($labels[$i])>6?substr($labels[$i],0,5).'.':$labels[$i];
                $lx=(int)($x+($bw-strlen($lb)*imagefontwidth(1))/2);
                imagestring($img,1,max($x,$lx),$mt+$ph+3,$lb,$tc);
                $x+=$bw+$sp;
            }
            
            imageline($img,$ml,$mt,$ml,$mt+$ph,$ax);
            imageline($img,$ml,$mt+$ph,$cw-$mr,$mt+$ph,$ax);
            imagepng($img,$chart_path);
            imagedestroy($img);
            $chart_size = filesize($chart_path);
            
            // Phase 3: PDF
            $page_w=595;$page_h=842;$margins=50;$left=$margins;$fs=11;
            $uw=$page_w-2*$margins;
            $y=$page_h-$margins;
            
            $pages=[];$pn=1;$cp="BT /F1 {$fs} Tf\n";
            $img_obs=[];$inc=0;
            
            $np = function() use(&$cp,&$pages,&$pn,&$y,$page_h,$margins,$fs){
                $cp.=sprintf("BT /F1 9 Tf %d %d Td (Page %d) Tj ET\n",$margins,$margins-5,$pn);
                $pages[]=$cp;$pn++;$cp="BT /F1 {$fs} Tf\n";$y=$page_h-$margins;
            };
            $cpb = function($n) use(&$y,$margins,&$np){if($y-$n<$margins+30)$np();};
            
            // Title
            $cpb(30);$cp.="/F1 18 Tf\n";
            $s=str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$title);
            $cp.=sprintf("%d %d Td (%s) Tj\n",$left,$y,$s);$y-=28;$cp.="/F1 {$fs} Tf\n";
            
            $dt='Generated: '.date('Y-m-d H:i:s');
            $s=str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$dt);
            $cp.="/F1 9 Tf\n";$cp.=sprintf("%d %d Td (%s) Tj\n",$left,$y,$s);$y-=16;$cp.="/F1 {$fs} Tf\n";
            
            $info="Rows: {$total_rows}, chart shows {$max_rows}";
            $s=str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$info);
            $cp.=sprintf("%d %d Td (%s) Tj\n",$left,$y,$s);$y-=24;
            
            // Embed chart
            $ii=@getimagesize($chart_path);
            if($ii){
                list($ow,$oh)=$ii;
                $sc=min(1.0,460/$ow);$dw=(int)($ow*$sc);$dh=(int)($oh*$sc);
                $cpb($dh+20);$inc++;$in='Im'.$inc;
                $bd_=file_get_contents($chart_path);
                $img_obs[]=['n'=>$in,'w'=>$ow,'h'=>$oh,'d'=>$bd_,'cs'=>'/DeviceRGB'];
                $ix=$left;$iy=$y-$dh;
                $cp.="q\n".sprintf("%.2f 0 0 %.2f %.2f %.2f cm\n",$dw,$dh,$ix,$iy).sprintf("/%s Do\n",$in)."Q\n";
                $y-=$dh+15;
            }
            
            // Data
            $cp.="/F1 9 Tf\n";
            for($i=0;$i<min(30,count($labels));$i++){
                $cpb(12);
                $rt=" {$labels[$i]}: {$values[$i]}";
                $s=str_replace(['\\','(',')'],['\\\\','\\(','\\)'],$rt);
                $cp.=sprintf("%d %d Td (%s) Tj\n",$left,$y,$s);$y-=12;
            }
            
            $cp.=sprintf("BT /F1 9 Tf %d %d Td (Page %d) Tj ET\n",$margins,$margins-5,$pn);
            $pages[]=$cp;$pc=count($pages);
            
            // Build PDF bytes
            $pdf="%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
            $on=0;$off=[];$no=function()use(&$on){return++$on;};
            $oc=$no();$op=$no();
            $oim=[];foreach($img_obs as $im)$oim[$im['n']]=$no();
            $of=$no();$ops=[];$oss=[];
            for($i=0;$i<$pc;$i++){$ops[]=$no();$oss[]=$no();}
            
            $off[$oc]=strlen($pdf);$pdf.="{$oc} 0 obj\n<< /Type /Catalog /Pages {$op} 0 R >>\nendobj\n";
            $ks='['.implode(' ',$ops).']';
            $off[$op]=strlen($pdf);$pdf.="{$op} 0 obj\n<< /Type /Pages /Kids {$ks} /Count {$pc} >>\nendobj\n";
            
            foreach($img_obs as $im){
                $o=$oim[$im['n']];$off[$o]=strlen($pdf);
                $d=$im['d'];
                $pdf.="{$o} 0 obj\n<< /Type /XObject /Subtype /Image /Width {$im['w']} /Height {$im['h']} /ColorSpace {$im['cs']} /BitsPerComponent 8 /Filter /FlateDecode /Length ".strlen($d)." >>\nstream\n{$d}\nendstream\nendobj\n";
            }
            
            $off[$of]=strlen($pdf);$pdf.="{$of} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>\nendobj\n";
            $xr='';foreach($img_obs as $im)$xr.="/{$im['n']} {$oim[$im['n']]} 0 R ";
            $res="<< /Font << /F1 {$of} 0 R >>".($xr?" /XObject << {$xr} >>":"")." /ProcSet [/PDF /Text /ImageC] >>";
            
            for($i=0;$i<$pc;$i++){
                $s=$oss[$i];$p=$ops[$i];$ct=$pages[$i];
                $cz=@gzcompress($ct);
                $sd=($cz!==false&&strlen($cz)<strlen($ct))?$cz:$ct;
                $sf=($cz!==false&&strlen($cz)<strlen($ct))?"/Filter /FlateDecode":"";
                $off[$s]=strlen($pdf);$pdf.="{$s} 0 obj\n<< /Length ".strlen($sd)." {$sf} >>\nstream\n{$sd}\nendstream\nendobj\n";
                $off[$p]=strlen($pdf);$pdf.="{$p} 0 obj\n<< /Type /Page /Parent {$op} 0 R /MediaBox [0 0 {$page_w} {$page_h}] /Contents {$s} 0 R /Resources {$res} >>\nendobj\n";
            }
            
            $mo=max(array_keys($off));$xr2=strlen($pdf);
            $pdf.="xref\n0 {$mo}\n0000000000 65535 f \n";
            for($i=1;$i<=$mo;$i++)$pdf.=sprintf("%010d 00000 n \n",$off[$i]??0);
            $pdf.="trailer\n<< /Size {$mo} /Root {$oc} 0 R /Info << /Title ({$title}) /Producer (PHP Data-to-Report) >> >>\nstartxref\n{$xr2}\n%%EOF\n";
            
            file_put_contents($report_path,$pdf);
            $report_size=filesize($report_path);
            
            return [
                'success'=>true,
                'report_file'=>$report_fn,
                'report_size'=>$report_size,
                'chart_file'=>$chart_fn,
                'chart_size'=>$chart_size,
                'total_rows'=>$total_rows,
                'chart_rows'=>count($labels),
                'pages'=>$pc,
            ];
            
        } catch (\Throwable $e) {
            return ['error' => 'Pipeline failed: ' . $e->getMessage()];
        }
    }
}
