<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_domain_intel = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'domain_intel',
    'description' => 'Full domain intelligence report: DNS + WHOIS + SSL cert + IP geolocation in one pass.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'domain' => 
        array (
          'type' => 'string',
          'description' => 'Domain to analyze.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout per source in seconds (5-30). Default: 15.',
        ),
      ),
      'required' => 
      array (
        0 => 'domain',
      ),
    ),
  ),
);

if (! function_exists('domain_intel')) {
    function domain_intel($domain, $timeout = null)
    {
        // Full domain intelligence: DNS + WHOIS + SSL + IP in one pass
        $d=isset($domain)?(string)$domain:'';
        $t=isset($timeout)?min(max((int)$t,5),30):15;
        if($d==='')return['error'=>'Domain required'];

        $r=['domain'=>$d,'timestamp'=>date('c')];

        // DNS
        $dns_r=[];
        foreach(['A'=>DNS_A,'AAAA'=>DNS_AAAA,'MX'=>DNS_MX,'NS'=>DNS_NS,'TXT'=>DNS_TXT,'SOA'=>DNS_SOA]as$n=>$f){
            $recs=@dns_get_record($d,$f);
            if($recs&&count($recs)>0)$dns_r[$n]=$recs;
        }
        $r['dns']=$dns_r;

        // IPs
        $ips=[];
        if(isset($dns_r['A']))foreach($dns_r['A']as$rec)$ips[]=$rec['ip'];
        if(isset($dns_r['AAAA']))foreach($dns_r['AAAA']as$rec)$ips[]=$rec['ipv6']??'';
        $ips=array_unique(array_filter($ips));
        $r['ips']=$ips;
        if(count($ips)>0){
            $gd=@file_get_contents("http://ip-api.com/json/{$ips[0]}",false,stream_context_create(['http'=>['timeout'=>$t]]));
            if($gd)$r['geo']=json_decode($gd,true);
        }

        // SSL
        try{
            $sk=@stream_socket_client("tls://{$d}:443",$e,$s,$t,STREAM_CLIENT_CONNECT,stream_context_create(['ssl'=>['capture_peer_cert'=>true,'verify_peer'=>false,'verify_peer_name'=>false]]));
            if($sk){
                $p=stream_context_get_params($sk);
                if(isset($p['options']['ssl']['peer_certificate'])){
                    $c=openssl_x509_parse($p['options']['ssl']['peer_certificate']);
                    if($c)$r['ssl']=['subject'=>$c['subject']??null,'issuer'=>$c['issuer']??null,'from'=>date('Y-m-d',$c['validFrom_time_t']??time()),'to'=>date('Y-m-d',$c['validTo_time_t']??time()),'days'=>isset($c['validTo_time_t'])?(int)(($c['validTo_time_t']-time())/86400):null];
                }
                fclose($sk);
            }
        }catch(\Throwable$e){$r['ssl_err']=$e->getMessage();}

        // WHOIS
        try{
            $ws=@stream_socket_client("tcp://whois.iana.org:43",$e,$s,10);
            if($ws){
                fwrite($ws,"{$d}\r\n");
                $wr='';while(!feof($ws))$wr.=fread($ws,4096);
                fclose($ws);
                if(preg_match('/whois:\s*(.+)/i',$wr,$m))$r['whois_server']=trim($m[1]);
                $r['whois_preview']=substr($wr,0,300);
            }
        }catch(\Throwable$e){$r['whois_err']=$e->getMessage();}

        return $r;
    }
}
