<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_file_read_lines = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'file_read_lines',
    'description' => 'Read specific line numbers from a file within the project directory. Returns the content of only the requested lines (1-indexed). Useful for reading excerpts of large files without the full content. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'path' => 
        array (
          'type' => 'string',
          'description' => 'File path relative to project root.',
        ),
        'start_line' => 
        array (
          'type' => 'integer',
          'description' => 'First line number to read (1-indexed).',
        ),
        'end_line' => 
        array (
          'type' => 'integer',
          'description' => 'Last line number to read (inclusive). If omitted, reads just start_line.',
        ),
      ),
      'required' => 
      array (
        0 => 'path',
        1 => 'start_line',
      ),
    ),
  ),
);

if (! function_exists('file_read_lines')) {
    function file_read_lines($path, $start_line, $end_line = null)
    {
        $base = realpath(__DIR__ . '/../../..');
        $full = realpath($base . '/' . ltrim($path, '/'));
        if ($full === false || strpos($full, $base) !== 0) {
            return json_encode(['error' => 'Invalid or restricted path']);
        }
        $restricted = ['/.env', '/.git/', '/vendor/'];
        foreach ($restricted as $r) {
            if (strpos($full, $base . $r) !== false) {
                return json_encode(['error' => 'Access denied: restricted file']);
            }
        }
        if (!is_file($full) || !is_readable($full)) {
            return json_encode(['error' => 'File not found or not readable']);
        }
        $lines = file($full, FILE_IGNORE_NEW_LINES);
        if ($lines === false) {
            return json_encode(['error' => 'Failed to read file']);
        }
        $start = max(1, (int)$start_line);
        $end = isset($end_line) ? min(count($lines), (int)$end_line) : $start;
        if ($start > count($lines)) {
            return json_encode(['error' => "Start line $start exceeds total lines " . count($lines)]);
        }
        $extracted = array_slice($lines, $start - 1, $end - $start + 1);
        return json_encode([
            'file' => $path,
            'total_lines' => count($lines),
            'lines_requested' => $start . '-' . $end,
            'content' => implode("\n", $extracted),
        ]);
    }
}
