<?php

// Generated by make_tool. Do not edit by hand unless you know why.
// FIXED: null guard on ltrim to prevent PHP 8.1+ deprecation

$toolDefinition_file_surgery = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'file_surgery',
    'description' => 'Edit a text file by surgically replacing, inserting, deleting, or appending lines. Reads the file, applies the edit with array_splice, writes back. More efficient than full rewrite for small changes. Handles cross-platform paths (Windows/Unix). Path relative to project root. Restricted: .env, vendor/, .git/.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'path' => 
        array (
          'type' => 'string',
          'description' => 'File path relative to project root, e.g. \'storage/agent/tools/some_tool.php\'',
        ),
        'operation' => 
        array (
          'type' => 'string',
          'description' => '\'replace\' - replace lines start_line to end_line with new_lines, \'insert\' - add before start_line, \'delete\' - remove lines start_line to end_line, \'append\' - add new_lines at end',
        ),
        'start_line' => 
        array (
          'type' => 'integer',
          'description' => '1-indexed start line number',
        ),
        'end_line' => 
        array (
          'type' => 'integer',
          'description' => '1-indexed end line number (required for replace and delete)',
        ),
        'new_lines' => 
        array (
          'type' => 'array',
          'description' => 'Lines to insert/replace/append',
          'items' => 
          array (
            'type' => 'string',
          ),
        ),
      ),
      'required' => 
      array (
        0 => 'path',
        1 => 'operation',
        2 => 'start_line',
      ),
    ),
  ),
);

if (! function_exists('file_surgery')) {
    function file_surgery($path, $operation, $start_line, $end_line = null, $new_lines = null)
    {
        $base = str_replace('\\', '/', realpath(__DIR__ . '/../../..'));
        if (!$base) return json_encode(['error' => 'Cannot resolve base path']);
        $safePath = ltrim($path ?? '', '/\\');
        $full = $base . '/' . $safePath;
        $dir = dirname($full);
        if (!is_dir($dir)) @mkdir($dir, 0755, true);
        $resolvedDir = str_replace('\\', '/', realpath($dir));
        if (!$resolvedDir || strpos($resolvedDir, $base) !== 0) return json_encode(['error' => 'Path outside project root']);
        $full = $resolvedDir . '/' . basename($full);
        foreach (['/.env', '/.git/', '/vendor/'] as $r) {
            if (strpos($full, $base . $r) !== false) return json_encode(['error' => 'Access denied: ' . $r]);
        }
        if (!file_exists($full)) return json_encode(['error' => 'File not found: ' . $path]);
        $content = file_get_contents($full);
        if ($content === false) return json_encode(['error' => 'Cannot read file']);
        $lines = explode("\n", $content);
        $count = count($lines);
        switch ($operation) {
            case 'replace':
                if (!isset($end_line)) return json_encode(['error' => 'end_line required for replace']);
                if ($start_line < 1 || $end_line > $count || $start_line > $end_line) return json_encode(['error' => "Invalid line range 1-$count"]);
                array_splice($lines, $start_line - 1, $end_line - $start_line + 1, $new_lines ?? []);
                break;
            case 'insert':
                if ($start_line < 1 || $start_line > $count + 1) return json_encode(['error' => "Invalid line $start_line, file has $count lines"]);
                array_splice($lines, $start_line - 1, 0, $new_lines ?? []);
                break;
            case 'delete':
                if (!isset($end_line)) return json_encode(['error' => 'end_line required for delete']);
                if ($start_line < 1 || $end_line > $count || $start_line > $end_line) return json_encode(['error' => "Invalid line range 1-$count"]);
                array_splice($lines, $start_line - 1, $end_line - $start_line + 1);
                break;
            case 'append':
                $lines = array_merge($lines, $new_lines ?? []);
                break;
            default: return json_encode(['error' => "Unknown operation: $operation"]);
        }
        $newContent = implode("\n", $lines);
        $bytes = file_put_contents($full, $newContent);
        if ($bytes === false) return json_encode(['error' => 'Failed to write file']);
        return json_encode(['path' => $path, 'bytes_written' => $bytes, 'lines_before' => $count, 'lines_after' => count(explode("\n", $newContent))]);
    }
}
