<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_gif_animator = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'gif_animator',
    'description' => 'Generate animated GIF images using PHP\'s GD library. Creates multi-frame animations from procedural frame data (shapes, gradients, text, patterns) or from existing images. Supports configurable frame delay, loop count, disposal method, and frame transitions (fade, slide, bounce, pulse). Each frame is rendered dynamically via GD, then assembled into an animated GIF with proper Graphics Control Extension blocks. First animation/motion capability in the ecosystem — no other tool creates moving images. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'mode' => 
        array (
          'type' => 'string',
          'description' => 'Animation type: \'bouncing_ball\', \'pulse\' (pulsating circle), \'fade_in\' (text fades in), \'rainbow\' (color cycling), \'slide\' (text slides across), \'blink\' (on/off blinking), \'loading\' (spinning indicator), \'counter\' (counting numbers), \'wave\' (sine wave animation). Default: \'bouncing_ball\'.',
        ),
        'width' => 
        array (
          'type' => 'integer',
          'description' => 'Frame width in pixels (16-512, default: 200).',
        ),
        'height' => 
        array (
          'type' => 'integer',
          'description' => 'Frame height in pixels (16-512, default: 200).',
        ),
        'frames' => 
        array (
          'type' => 'integer',
          'description' => 'Number of frames (2-100, default: 16).',
        ),
        'delay' => 
        array (
          'type' => 'integer',
          'description' => 'Delay between frames in centiseconds (1-100, default: 5 = 50ms).',
        ),
        'loops' => 
        array (
          'type' => 'integer',
          'description' => 'Number of loops (0 = infinite, default: 0).',
        ),
        'text' => 
        array (
          'type' => 'string',
          'description' => 'Text to display (for fade_in, slide, counter modes). Default: \'Agent!\'.',
        ),
        'color1' => 
        array (
          'type' => 'string',
          'description' => 'Primary color as hex (e.g. \'#3366CC\'). Default varies.',
        ),
        'color2' => 
        array (
          'type' => 'string',
          'description' => 'Secondary color as hex. Default varies.',
        ),
        'background' => 
        array (
          'type' => 'string',
          'description' => 'Background color as hex (e.g. \'#FFFFFF\'). Default: \'#1a1a2e\'.',
        ),
        'filename' => 
        array (
          'type' => 'string',
          'description' => 'Output filename (without path, .gif added). Default: auto-generated.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (5-30, default: 15).',
        ),
      ),
      'required' => 
      array (
      ),
    ),
  ),
);

if (! function_exists('gif_animator')) {
    function gif_animator($mode = null, $width = null, $height = null, $frames = null, $delay = null, $loops = null, $text = null, $color1 = null, $color2 = null, $background = null, $filename = null, $timeout = null)
    {
        // Animated GIF generator — creates multi-frame animations via GD
        $mode = $mode ?? 'bouncing_ball';
        $width = $width ?? 200;
        $width = max(16, min(512, (int)$width));
        $height = $height ?? 200;
        $height = max(16, min(512, (int)$height));
        $frames = $frames ?? 16;
        $frames = max(2, min(100, $frames));
        $delay = $delay ?? 5;
        $delay = max(1, min(100, $delay));
        $loops = $loops ?? 0;
        $loops = max(0, min(1000, $loops));
        $text = $text ?? 'Agent!';
        $color1 = $color1 ?? '';
        $color2 = $color2 ?? '';
        $background = $background ?? '#1a1a2e';
        $filename = $filename ?? '';
        $timeout = $timeout ?? 15;

        // Parse hex color
        $hexToRgb = function($hex) {
            $hex = ltrim($hex, '#');
            if (strlen($hex) === 3) {
                $hex = $hex[0] . $hex[0] . $hex[1] . $hex[1] . $hex[2] . $hex[2];
            }
            $r = hexdec(substr($hex, 0, 2));
            $g = hexdec(substr($hex, 2, 2));
            $b = hexdec(substr($hex, 4, 2));
            return [$r, $g, $b];
        };

        // Generate a frame as a GD image
        $renderFrame = function($frame_num, $total_frames) use ($mode, $width, $height, $text, $hexToRgb, $color1, $color2, $background) {
            $im = imagecreatetruecolor($width, $height);
            
            $bgRgb = $hexToRgb($background);
            $bg = imagecolorallocate($im, $bgRgb[0], $bgRgb[1], $bgRgb[2]);
            imagefill($im, 0, 0, $bg);
            
            $progress = $total_frames > 1 ? $frame_num / ($total_frames - 1) : 0;
            $angle = $progress * 2 * M_PI;
            
            $c1 = empty($color1) ? '#3366CC' : $color1;
            $c2 = empty($color2) ? '#FF3366' : $color2;
            $c1Rgb = $hexToRgb($c1);
            $c2Rgb = $hexToRgb($c2);
            
            $halfW = $width / 2;
            $halfH = $height / 2;
            
            if ($mode === 'bouncing_ball') {
                // Ball bounces vertically with slight horizontal drift
                $bounceY = abs(sin($angle)) * ($height - 30);
                $driftX = sin($angle * 1.5) * ($width / 4);
                $ballX = $halfW + $driftX;
                $ballY = $height - 15 - $bounceY;
                $radius = 12 + 4 * abs(cos($angle));
                
                // Ball color interpolates
                $r = (int)($c1Rgb[0] + ($c2Rgb[0] - $c1Rgb[0]) * $progress);
                $g = (int)($c1Rgb[1] + ($c2Rgb[1] - $c1Rgb[1]) * $progress);
                $b = (int)($c1Rgb[2] + ($c2Rgb[2] - $c1Rgb[2]) * $progress);
                $ballColor = imagecolorallocate($im, $r, $g, $b);
                
                imagefilledellipse($im, (int)$ballX, (int)$ballY, (int)($radius*2), (int)($radius*2), $ballColor);
                imageellipse($im, (int)$ballX, (int)$ballY, (int)($radius*2), (int)($radius*2), 
                    imagecolorallocate($im, 255, 255, 255));
                
                // Shadow
                $shadowY = $height - 10;
                $shadowSize = 6 + 10 * (1 - abs($bounceY / ($height - 30)));
                imagefilledellipse($im, (int)$ballX, $shadowY, (int)$shadowSize, 4, 
                    imagecolorallocatealpha($im, 0, 0, 0, 60));
            } elseif ($mode === 'pulse') {
                $radius = 20 + 40 * abs(sin($angle));
                $r = (int)($c1Rgb[0] + ($c2Rgb[0] - $c1Rgb[0]) * $progress);
                $g = (int)($c1Rgb[1] + ($c2Rgb[1] - $c1Rgb[1]) * $progress);
                $b = (int)($c1Rgb[2] + ($c2Rgb[2] - $c1Rgb[2]) * $progress);
                $col = imagecolorallocate($im, $r, $g, $b);
                imagefilledellipse($im, (int)$halfW, (int)$halfH, (int)($radius*2), (int)($radius*2), $col);
                
                // Outer ring
                $ringR = $radius + 8;
                $ringCol = imagecolorallocatealpha($im, $r, $g, $b, 40);
                imageellipse($im, (int)$halfW, (int)$halfH, (int)($ringR*2), (int)($ringR*2), $ringCol);
            } elseif ($mode === 'fade_in') {
                // Text that fades in
                $alpha = (int)(127 * (1 - $progress));
                $textCol = imagecolorallocatealpha($im, 255, 255, 255, $alpha);
                $font = 5;
                $tw = imagefontwidth($font) * strlen($text);
                $th = imagefontheight($font);
                $tx = (int)(($width - $tw) / 2);
                $ty = (int)(($height - $th) / 2);
                imagestring($im, $font, $tx, $ty, $text, $textCol);
            } elseif ($mode === 'slide') {
                $tw = imagefontwidth(5) * strlen($text);
                $totalDist = $width + $tw;
                $slideX = $width - $progress * $totalDist;
                $textCol = imagecolorallocate($im, 255, 255, 255);
                imagestring($im, 5, (int)$slideX, (int)(($height - 16) / 2), $text, $textCol);
            } elseif ($mode === 'blink') {
                $on = ($frame_num % 2 === 0);
                if ($on) {
                    $r = $c1Rgb[0]; $g = $c1Rgb[1]; $b = $c1Rgb[2];
                    $col = imagecolorallocate($im, $r, $g, $b);
                    imagefilledellipse($im, (int)$halfW, (int)$halfH, (int)($width*0.6), (int)($height*0.6), $col);
                    $textCol = imagecolorallocate($im, 255, 255, 255);
                    $tw = imagefontwidth(5) * strlen($text);
                    imagestring($im, 5, (int)(($width - $tw) / 2), (int)(($height - 16) / 2), $text, $textCol);
                }
            } elseif ($mode === 'loading') {
                // Spinning arc
                $startAngle = (int)($progress * 360);
                $arcLen = 60;
                $r = $c1Rgb[0]; $g = $c1Rgb[1]; $b = $c1Rgb[2];
                $col = imagecolorallocate($im, $r, $g, $b);
                $cx = (int)$halfW; $cy = (int)$halfH;
                $rx = (int)($width * 0.35); $ry = (int)($height * 0.35);
                imagefilledarc($im, $cx, $cy, $rx*2, $ry*2, $startAngle, $startAngle + $arcLen, $col, IMG_ARC_PIE);
                imagefilledellipse($im, $cx, $cy, 8, 8, imagecolorallocate($im, $bgRgb[0], $bgRgb[1], $bgRgb[2]));
            } elseif ($mode === 'counter') {
                $display = (string)((int)($progress * 99) + 1);
                $textCol = imagecolorallocate($im, $c1Rgb[0], $c1Rgb[1], $c1Rgb[2]);
                $font = 5;
                $tw = imagefontwidth($font) * strlen($display);
                imagestring($im, $font, (int)(($width - $tw) / 2), (int)(($height - 16) / 2), $display, $textCol);
                
                // Progress bar
                $barY = $height - 20;
                $barW = $width - 40;
                $filledW = (int)($barW * $progress);
                $barCol = imagecolorallocate($im, $c2Rgb[0], $c2Rgb[1], $c2Rgb[2]);
                imagefilledrectangle($im, 20, $barY, 20 + $filledW, $barY + 8, $barCol);
                imagerectangle($im, 20, $barY, 20 + $barW, $barY + 8, imagecolorallocate($im, 200, 200, 200));
            } elseif ($mode === 'wave') {
                // Animated sine wave
                $col = imagecolorallocate($im, $c1Rgb[0], $c1Rgb[1], $c1Rgb[2]);
                $amp = $height * 0.3;
                $freq = 4;
                for ($x = 0; $x < $width; $x++) {
                    $y = $halfH + $amp * sin(($x / $width) * 2 * M_PI * $freq + $angle * 2);
                    imagesetpixel($im, $x, (int)$y, $col);
                    if ($x > 0) {
                        $prevY = $halfH + $amp * sin((($x-1) / $width) * 2 * M_PI * $freq + $angle * 2);
                        imageline($im, $x-1, (int)$prevY, $x, (int)$y, $col);
                    }
                }
                // Wave fill
                for ($x = 0; $x < $width; $x++) {
                    $y = $halfH + $amp * sin(($x / $width) * 2 * M_PI * $freq + $angle * 2);
                    $alphaCol = imagecolorallocatealpha($im, $c1Rgb[0], $c1Rgb[1], $c1Rgb[2], 80);
                    imageline($im, $x, (int)$halfH, $x, (int)$y, $alphaCol);
                }
            } else {
                // Default: bouncing ball
                $bounceY = abs(sin($angle)) * ($height - 30);
                $driftX = sin($angle * 1.5) * ($width / 4);
                $ballX = $halfW + $driftX;
                $ballY = $height - 15 - $bounceY;
                $ballColor = imagecolorallocate($im, $c1Rgb[0], $c1Rgb[1], $c1Rgb[2]);
                imagefilledellipse($im, (int)$ballX, (int)$ballY, 24, 24, $ballColor);
                imageellipse($im, (int)$ballX, (int)$ballY, 24, 24, 
                    imagecolorallocate($im, 255, 255, 255));
            }
            
            return $im;
        };

        // Capture each frame as raw GIF binary
        $frames_data = [];

        for ($i = 0; $i < $frames; $i++) {
            $im = $renderFrame($i, $frames);
            
            // Capture GIF into a string
            ob_start();
            imagegif($im);
            $gif_data = ob_get_clean();
            imagedestroy($im);
            
            $frames_data[] = $gif_data;
        }

        // Build animated GIF manually from frame data
        // Parse the first frame's header
        $first = $frames_data[0];
        $header_len = 6; // "GIF89a"
        $screen_descriptor_len = 7;

        // Check for global color table (bit 7 of packed field at offset 10)
        $packed = ord($first[10]);
        $has_gct = ($packed & 0x80) !== 0;
        $gct_size = $has_gct ? (3 * pow(2, ($packed & 0x07) + 1)) : 0;

        $header_end = 6 + 7 + $gct_size; // Header + SD + GCT

        // Start building output
        $output = substr($first, 0, $header_end); // Include full header + GCT from first frame

        // Netscape Application Extension for loop count
        $output .= "\x21\xFF\x0BNETSCAPE2.0\x03\x01";
        $output .= pack('v', $loops);
        $output .= "\x00";

        foreach ($frames_data as $idx => $frame_data) {
            // Find the image data in each frame (after header/SD/GCT)
            // For frame 0, skip the header we already wrote
            $start_pos = ($idx === 0) ? $header_end : 0;
            
            // Graphics Control Extension
            $output .= "\x21\xF9\x04"; // GCE intro
            $disposal = 2; // Background disposal
            $packed_gce = ($disposal << 2) | 0; // No user input, no transparency
            $output .= chr($packed_gce);
            $output .= pack('v', $delay); // Delay in centiseconds
            $output .= "\x00"; // Transparent color index (unused)
            $output .= "\x00"; // GCE terminator
            
            // Find the Image Descriptor in this frame
            // In GD output, after the header/SD/GCT, we should find \x2C (Image Descriptor)
            if ($idx === 0) {
                // First frame: use everything after the header
                $image_start = $header_end;
                // Skip the GCE that GD might have added
                if (substr($frame_data, $image_start, 2) === "\x21\xF9") {
                    // Skip GCE
                    $image_start += 2 + 1 + 4 + 1 + 1; // 2 header + 1 size + 4 data + 1 terminator... actually
                    // GCE: 21 F9 04 [4 bytes] 00 = 8 bytes total
                    $image_start += 8;
                }
            } else {
                // Subsequent frames: find the image descriptor in the raw frame
                $image_start = 0;
            }
            
            // Find the Image Descriptor marker \x2C in the frame data
            if ($idx > 0) {
                $pos = strpos($frame_data, "\x2C");
                if ($pos !== false) {
                    $image_start = $pos;
                } else {
                    $image_start = $header_end;
                }
            }
            
            // Write from Image Descriptor to end (including LZW data + trailer)
            $image_data = substr($frame_data, $image_start);
            
            // Remove the trailer byte (0x3B) if present — we'll add it at the very end
            if (substr($image_data, -1) === "\x3B") {
                $image_data = substr($image_data, 0, -1);
            }
            
            $output .= $image_data;
        }

        // Trailer
        $output .= "\x3B";

        // Write to file
        $workspace = getcwd() . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'agent' . DIRECTORY_SEPARATOR . 'workspace';
        if (!is_dir($workspace)) {
            @mkdir($workspace, 0755, true);
        }

        if (empty($filename)) {
            $ts = date('Ymd_His');
            $filename = "animation_{$mode}_{$ts}.gif";
        }
        if (!str_ends_with($filename, '.gif')) {
            $filename .= '.gif';
        }
        $filename = preg_replace('/[^a-zA-Z0-9_.-]/', '_', $filename);
        $out_path = $workspace . DIRECTORY_SEPARATOR . $filename;

        $written = @file_put_contents($out_path, $output);
        if ($written === false) {
            return ['error' => 'Failed to write GIF file to: ' . $out_path];
        }

        // Verify with finfo
        $mime = '';
        if (function_exists('finfo_open')) {
            $fi = finfo_open(FILEINFO_MIME_TYPE);
            $mime = finfo_file($fi, $out_path);
            finfo_close($fi);
        }

        return [
            'success' => true,
            'file' => $filename,
            'file_path' => 'storage/agent/workspace/' . $filename,
            'file_size_bytes' => $written,
            'mime_type' => $mime ?: 'image/gif',
            'mode' => $mode,
            'frames' => $frames,
            'dimensions' => $width . 'x' . $height,
            'delay_cs' => $delay,
            'delay_ms' => $delay * 10,
            'loops' => $loops,
            'duration_seconds' => round($frames * $delay * 0.01, 2),
        ];
    }
}
