<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_http_send = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'http_send',
    'description' => 'Send HTTP requests with configurable method (GET, POST, PUT, PATCH, DELETE), body (JSON or form data), custom headers, timeout, and max redirects. Returns status code, response headers, decoded JSON body, and honest error info. Uses PHP streams with HTTP context. Complements http_fetch (GET-only) by adding write capabilities. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'url' => 
        array (
          'type' => 'string',
          'description' => 'The URL to send the request to (http:// or https://).',
        ),
        'method' => 
        array (
          'type' => 'string',
          'description' => 'HTTP method: \'GET\', \'POST\', \'PUT\', \'PATCH\', \'DELETE\'. Default: \'POST\'.',
        ),
        'data' => 
        array (
          'type' => 'object',
          'description' => 'Data to send. If content_type is \'json\', this is encoded as JSON. If \'form\', encoded as application/x-www-form-urlencoded. Example: {"key":"value", "name":"test"}',
        ),
        'content_type' => 
        array (
          'type' => 'string',
          'description' => 'Content type: \'json\' (application/json) or \'form\' (application/x-www-form-urlencoded). Default: \'json\'.',
        ),
        'headers' => 
        array (
          'type' => 'object',
          'description' => 'Optional additional headers, e.g. {"Authorization":"Bearer token123", "Accept":"application/json"}',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (1-40, default 20).',
        ),
        'max_redirects' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum HTTP redirects to follow (0-20, default 5).',
        ),
        'body_limit' => 
        array (
          'type' => 'integer',
          'description' => 'Max body bytes to return (1024-10485760, default 1048576 = 1MB).',
        ),
      ),
      'required' => 
      array (
        0 => 'url',
      ),
    ),
  ),
);

if (! function_exists('http_send')) {
    function http_send($url, $method = null, $data = null, $content_type = null, $headers = null, $timeout = null, $max_redirects = null, $body_limit = null)
    {
        if (!is_string($url) || $url === '') {
            return ['error' => 'URL is required.', 'status' => 0, 'headers' => [], 'body' => null];
        }

        $scheme = parse_url($url, PHP_URL_SCHEME);
        if (!in_array($scheme, ['http', 'https'], true)) {
            return ['error' => 'Only http:// and https:// URLs are supported.', 'status' => 0, 'headers' => [], 'body' => null];
        }

        $method = isset($method) ? strtoupper(trim($method)) : 'POST';
        $allowed = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];
        if (!in_array($method, $allowed, true)) {
            return ['error' => "Unsupported method '$method'. Allowed: " . implode(', ', $allowed), 'status' => 0, 'headers' => [], 'body' => null];
        }

        $timeout = isset($timeout) ? max(1, min(40, (int)$timeout)) : 20;
        $max_redirects = isset($max_redirects) ? max(0, min(20, (int)$max_redirects)) : 5;
        $body_limit = isset($body_limit) ? max(1024, min(10485760, (int)$body_limit)) : 1048576;
        $content_type = isset($content_type) ? strtolower(trim($content_type)) : 'json';

        // Build headers
        $ctx_headers = ['User-Agent: self-bootstrapping-agent/1.0'];

        // Encode body
        $body_content = '';
        $has_body = in_array($method, ['POST', 'PUT', 'PATCH']);
        if ($has_body && isset($data) && is_array($data)) {
            if ($content_type === 'form') {
                $body_content = http_build_query($data, '', '&');
                $ctx_headers[] = 'Content-Type: application/x-www-form-urlencoded';
            } else {
                $body_content = json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
                $ctx_headers[] = 'Content-Type: application/json';
            }
            $ctx_headers[] = 'Content-Length: ' . strlen($body_content);
        }

        // Custom headers from caller
        if (isset($headers) && is_array($headers)) {
            foreach ($headers as $name => $value) {
                // Don't let caller override Content-Type or Content-Length
                $lower = strtolower($name);
                if ($lower !== 'content-type' && $lower !== 'content-length') {
                    $ctx_headers[] = "$name: $value";
                }
            }
        }

        $ctx_opts = [
            'http' => [
                'method' => $method,
                'header' => implode("\r\n", $ctx_headers),
                'content' => $body_content,
                'timeout' => $timeout,
                'max_redirects' => $max_redirects,
                'follow_location' => $max_redirects > 0 ? 1 : 0,
                'ignore_errors' => true,
            ],
            'ssl' => [
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => false,
            ],
        ];

        $context = stream_context_create($ctx_opts);

        $error_msg = null;
        set_error_handler(function ($severity, $message) use (&$error_msg) {
            $error_msg = $message;
            return true;
        });

        $start_time = microtime(true);
        $response = @file_get_contents($url, false, $context);
        $elapsed = microtime(true) - $start_time;

        restore_error_handler();

        if ($response === false) {
            $reason = $error_msg ?? 'Unknown error during request.';
            if (preg_match('/Failed to open stream: (.+)$/', $reason, $m)) {
                $reason = trim($m[1]);
            }
            return [
                'error' => $reason,
                'status' => 0,
                'headers' => [],
                'body' => null,
                'timing' => ['elapsed_seconds' => round($elapsed, 3)],
            ];
        }

        // Parse response headers
        $response_headers_raw = $http_response_header ?? [];
        $status_code = 0;
        $parsed_headers = [];

        foreach ($response_headers_raw as $i => $line) {
            if ($i === 0) {
                if (preg_match('#HTTP/\d+\.\d+ (\d+)#', $line, $m)) {
                    $status_code = (int)$m[1];
                }
                continue;
            }
            if (str_contains($line, ': ')) {
                [$name, $value] = explode(': ', $line, 2);
                $parsed_headers[strtolower($name)] = $value;
            }
        }

        // Truncate body if needed
        $body_len = strlen($response);
        $truncated = false;
        if ($body_len > $body_limit) {
            $response = substr($response, 0, $body_limit);
            $truncated = true;
        }

        // Auto-decode JSON body
        $response_content_type = $parsed_headers['content-type'] ?? '';
        $decoded = null;
        $parse_error = null;
        if (str_contains($response_content_type, 'json')) {
            $decoded = json_decode($response, true);
            if ($decoded === null && json_last_error() !== JSON_ERROR_NONE) {
                $parse_error = json_last_error_msg();
            }
        }

        return [
            'status' => $status_code,
            'headers' => $parsed_headers,
            'body' => $decoded !== null ? $decoded : $response,
            'body_decoded' => $decoded !== null,
            'body_size_bytes' => $body_len,
            'body_truncated' => $truncated,
            'content_type' => $response_content_type,
            'timing' => [
                'elapsed_seconds' => round($elapsed, 3),
                'timeout_setting' => $timeout,
            ],
            'request' => [
                'method' => $method,
                'url' => $url,
                'content_type' => $has_body ? $content_type : null,
                'body_size' => strlen($body_content),
            ],
            'parse_error' => $parse_error,
            'error' => null,
        ];
    }
}
