<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_http_post = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'http_post',
    'description' => 'Send HTTP POST, PUT, PATCH, and DELETE requests to REST APIs with configurable body, content type, headers, and timeouts. Supports JSON, form-encoded, plain text, and binary bodies. Auto-sets Content-Type and Content-Length headers. Returns status code, response headers, body, and timing. The complement to http_fetch (GET-only) — enables full REST API client capability. Uses PHP streams with HTTP context. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'url' => 
        array (
          'type' => 'string',
          'description' => 'The URL to send the request to (http:// or https://). Required.',
        ),
        'method' => 
        array (
          'type' => 'string',
          'description' => 'HTTP method: \'POST\', \'PUT\', \'PATCH\', \'DELETE\'. Default: \'POST\'.',
        ),
        'body' => 
        array (
          'type' => 'string',
          'description' => 'Request body content. For JSON, use json_encoded string. For form data, use http_build_query format. Default: empty.',
        ),
        'content_type' => 
        array (
          'type' => 'string',
          'description' => 'Content-Type header value. Auto-set based on body_format if not provided. Default: auto-detect.',
        ),
        'body_format' => 
        array (
          'type' => 'string',
          'description' => '\'json\' — auto-encode body as JSON (sets Content-Type: application/json). \'form\' — treat body as form-encoded (sets Content-Type: application/x-www-form-urlencoded). \'text\' — plain text (sets Content-Type: text/plain). \'auto\' — detect from body content. Default: \'auto\'.',
        ),
        'headers' => 
        array (
          'type' => 'object',
          'description' => 'Optional associative array of custom headers, e.g. {"Authorization":"Bearer token123","Accept":"application/json"}. Default User-Agent is provided.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (1-40, default: 20).',
        ),
        'max_redirects' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum HTTP redirects to follow (0-10, default: 3).',
        ),
        'body_limit' => 
        array (
          'type' => 'integer',
          'description' => 'Max response body bytes to return (1024-10485760, default: 1048576 = 1MB).',
        ),
        'verify' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, verify SSL peer. Default: false (for compatibility).',
        ),
      ),
      'required' => 
      array (
        0 => 'url',
      ),
    ),
  ),
);

if (! function_exists('http_post')) {
    function http_post($url, $method = null, $body = null, $content_type = null, $body_format = null, $headers = null, $timeout = null, $max_redirects = null, $body_limit = null, $verify = null)
    {
        // HTTP POST/PUT/PATCH/DELETE client — full REST API support
        // Complements http_fetch (GET-only) by enabling write operations

        $timeout = min(40, max(1, $timeout ?? 20));
        $bodyLimit = min(10485760, max(1024, $body_limit ?? 1048576));
        $maxRedirects = min(10, max(0, $max_redirects ?? 3));
        $url = $url ?? '';
        $method = strtoupper($method ?? 'POST');
        $rawBody = $body ?? '';
        $bodyFormat = $body_format ?? 'auto';
        $customHeaders = $headers ?? [];
        $verifyPeer = $verify ?? false;

        // Validate URL
        if (empty($url) || !preg_match('#^https?://#i', $url)) {
            return ['success' => false, 'error' => 'Valid http:// or https:// URL is required.', 'url' => $url];
        }

        // Validate method
        $validMethods = ['POST', 'PUT', 'PATCH', 'DELETE'];
        if (!in_array($method, $validMethods)) {
            return ['success' => false, 'error' => "Invalid method '$method'. Must be one of: " . implode(', ', $validMethods), 'method' => $method];
        }

        try {
            // Ensure body is a string
            if (is_array($rawBody)) {
                $rawBody = json_encode($rawBody);
            } elseif (is_object($rawBody)) {
                $rawBody = json_encode($rawBody);
            }

            // Prepare the body
            $requestBody = (string)$rawBody;
            $contentType = null;

            if ($bodyFormat === 'json' || ($bodyFormat === 'auto' && preg_match('/^[\s]*[\[{]/', $requestBody))) {
                // Validate JSON
                if (!empty($requestBody)) {
                    $parsed = json_decode($requestBody, true);
                    if ($parsed === null && json_last_error() !== JSON_ERROR_NONE) {
                        return ['success' => false, 'error' => 'Invalid JSON body: ' . json_last_error_msg(), 'body' => mb_substr($requestBody, 0, 200)];
                    }
                    // Re-encode for clean formatting
                    $requestBody = json_encode($parsed, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
                }
                $contentType = 'application/json';
            } elseif ($bodyFormat === 'form' || ($bodyFormat === 'auto' && preg_match('/^[a-zA-Z0-9_%.+-]+=[^&]*(&[a-zA-Z0-9_%.+-]+=[^&]*)*$/', $requestBody))) {
                $contentType = 'application/x-www-form-urlencoded';
            } elseif ($bodyFormat === 'text' || $bodyFormat === 'auto') {
                $contentType = 'text/plain; charset=utf-8';
            }

            // If custom Content-Type header provided, override
            foreach ($customHeaders as $key => $value) {
                if (strtolower($key) === 'content-type') {
                    $contentType = $value;
                    break;
                }
            }

            // Build HTTP header lines
            $headerLines = "User-Agent: HTTPPostClient/1.0\r\n";
            if ($contentType !== null) {
                $headerLines .= "Content-Type: $contentType\r\n";
            }
            if (!empty($requestBody)) {
                $headerLines .= "Content-Length: " . strlen($requestBody) . "\r\n";
            }
            // Custom headers
            foreach ($customHeaders as $key => $value) {
                $lowerKey = strtolower($key);
                if (!in_array($lowerKey, ['content-type', 'content-length', 'user-agent'])) {
                    $headerLines .= "$key: $value\r\n";
                }
            }
            $headerLines .= "Accept: */*\r\n";

            // Build stream context
            $httpOptions = [
                'method' => $method,
                'timeout' => $timeout,
                'header' => $headerLines,
                'ignore_errors' => true,
                'max_redirects' => $maxRedirects,
            ];
            if (!empty($requestBody)) {
                $httpOptions['content'] = $requestBody;
            }

            $ctx = stream_context_create([
                'http' => $httpOptions,
                'ssl' => [
                    'verify_peer' => $verifyPeer,
                    'verify_peer_name' => $verifyPeer,
                    'allow_self_signed' => !$verifyPeer,
                ],
            ]);

            $startTime = microtime(true);
            $responseBody = @file_get_contents($url, false, $ctx);
            $elapsed = (microtime(true) - $startTime) * 1000;

            // Parse response headers
            $statusCode = 0;
            $responseHeaders = [];
            if (isset($http_response_header)) {
                preg_match('/HTTP\/\d\.\d\s+(\d+)/', $http_response_header[0], $m);
                $statusCode = (int)($m[1] ?? 0);
                foreach ($http_response_header as $line) {
                    if (strpos($line, ': ') !== false) {
                        list($key, $value) = explode(': ', $line, 2);
                        $responseHeaders[strtolower($key)] = $value;
                    }
                }
            }

            // Handle response
            $truncated = false;
            if ($responseBody !== false && strlen($responseBody) > $bodyLimit) {
                $responseBody = substr($responseBody, 0, $bodyLimit);
                $truncated = true;
            }

            $result = [
                'success' => $responseBody !== false || $statusCode > 0,
                'url' => $url,
                'method' => $method,
                'status_code' => $statusCode,
                'response_time_ms' => round($elapsed, 1),
                'content_type' => $responseHeaders['content-type'] ?? '',
                'headers' => $responseHeaders,
                'body_truncated' => $truncated,
            ];

            if ($responseBody !== false) {
                $result['body'] = $responseBody;
                $result['body_size_bytes'] = strlen($responseBody);
                // Try to parse JSON response
                $jsonParsed = json_decode($responseBody, true);
                if ($jsonParsed !== null) {
                    $result['body_parsed'] = $jsonParsed;
                }
            } elseif ($statusCode > 0) {
                $result['body'] = '(empty or binary response)';
                $result['body_size_bytes'] = 0;
            } else {
                $error = error_get_last();
                $result['error'] = $error['message'] ?? 'Failed to send request';
            }

            return $result;

        } catch (\Exception $e) {
            return ['success' => false, 'error' => $e->getMessage(), 'url' => $url, 'method' => $method];
        }
    }
}
