<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_image_search = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'image_search',
    'description' => 'Search for images from Wikimedia Commons using the free MediaWiki API (no API key required). Searches by keyword, fetches the top image results with metadata (dimensions, file size, MIME type, description URL), and downloads the best match to the workspace. Verifies download integrity using image_info. First visual media search capability in the ecosystem. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'query' => 
        array (
          'type' => 'string',
          'description' => 'Search keyword(s) for the image (e.g. \'golden gate bridge\', \'panda\', \'moon landing\'). Required.',
        ),
        'max_results' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum search results to return (1-20, default: 5).',
        ),
        'download_best' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, download the highest-resolution result to workspace (default: true).',
        ),
        'min_width' => 
        array (
          'type' => 'integer',
          'description' => 'Minimum image width in pixels for filtering (default: 200).',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds for API requests (5-30, default: 15).',
        ),
      ),
      'required' => 
      array (
        0 => 'query',
      ),
    ),
  ),
);

if (! function_exists('image_search')) {
    function image_search($query, $max_results = null, $download_best = null, $min_width = null, $timeout = null)
    {
            $query = $query ?? '';
            $max_results = $max_results ?? 5;
            $download_best = $download_best ?? true;
            $min_width = $min_width ?? 200;
            $timeout = $timeout ?? 15;

            $timeout = max(5, min(30, (int)$timeout));
            $max_results = max(1, min(20, (int)$max_results));
            $min_width = max(0, min(10000, (int)$min_width));

            if (empty(trim($query))) {
                return ['success' => false, 'error' => 'Search query is required.'];
            }

            $workspace = __DIR__ . '/../workspace';

            // Helper: fetch JSON from API
            $fetch_json = function($url, $t) {
                $ctx = stream_context_create([
                    'http' => ['method' => 'GET', 'timeout' => $t, 'header' => "User-Agent: image_search/1.0\r\n", 'ignore_errors' => true],
                    'ssl' => ['verify_peer' => false, 'verify_peer_name' => false],
                ]);
                $body = @file_get_contents($url, false, $ctx);
                if ($body === false) return ['error' => error_get_last()['message'] ?? 'fetch failed', 'success' => false];
                $status = 200;
                if (isset($http_response_header)) {
                    foreach ($http_response_header as $h) {
                        if (preg_match('#^HTTP/\d+\.\d+ (\d+)#', $h, $m)) { $status = (int)$m[1]; break; }
                    }
                }
                if ($status >= 400) return ['error' => "HTTP $status", 'success' => false];
                $data = @json_decode($body, true);
                if ($data === null) return ['error' => 'Invalid JSON', 'success' => false];
                return ['data' => $data, 'status' => $status, 'success' => true];
            };

            // Helper: download a file with proper error checking
            $download_file = function($url, $path, $t) {
                $ctx = stream_context_create([
                    'http' => ['method' => 'GET', 'timeout' => $t, 'header' => "User-Agent: Mozilla/5.0 (compatible; image_search/1.0)\r\n", 'ignore_errors' => true, 'follow_location' => 1],
                    'ssl' => ['verify_peer' => false, 'verify_peer_name' => false],
                ]);
                $body = @file_get_contents($url, false, $ctx);
                if ($body === false) {
                    return ['success' => false, 'error' => error_get_last()['message'] ?? 'Download failed'];
                }
                // Check HTTP status
                $status = 200;
                $content_type = '';
                if (isset($http_response_header)) {
                    foreach ($http_response_header as $h) {
                        if (preg_match('#^HTTP/\d+\.\d+ (\d+)#', $h, $m)) { $status = (int)$m[1]; }
                        if (stripos($h, 'Content-Type:') === 0) { $content_type = trim(substr($h, 13)); }
                    }
                }
                if ($status >= 400) {
                    return ['success' => false, 'error' => "HTTP $status", 'status' => $status, 'content_type' => $content_type];
                }
                // Check if response is actually an image
                if (strpos($content_type, 'image/') !== 0 && strpos($content_type, 'application/octet-stream') !== 0) {
                    // Might be an error page or redirect
                    if (strlen($body) < 5000 && strpos($content_type, 'text/html') !== false) {
                        return ['success' => false, 'error' => "Server returned HTML (status $status) instead of image — may be rate limited or blocked.", 'status' => $status, 'content_type' => $content_type];
                    }
                }
                file_put_contents($path, $body);
                return ['success' => true, 'size' => strlen($body), 'content_type' => $content_type, 'status' => $status];
            };

            $api_base = 'https://commons.wikimedia.org/w/api.php';

            // Step 1: Search for images (namespace 6 = File)
            $search_url = $api_base . '?action=query&list=search&srsearch=' . urlencode($query) . '&srnamespace=6&srlimit=' . $max_results . '&format=json';
            $search_result = $fetch_json($search_url, $timeout);

            if (!$search_result['success']) {
                return ['success' => false, 'error' => 'Wikimedia API search failed: ' . $search_result['error']];
            }

            $results = $search_result['data']['query']['search'] ?? [];

            if (empty($results)) {
                return [
                    'success' => true, 'query' => $query, 'total_results' => 0,
                    'note' => 'No images found. Try different keywords.',
                    'results' => [], 'downloaded' => null,
                ];
            }

            // Step 2: Get image info for all results
            $title_list = '';
            foreach ($results as $i => $r) {
                if ($i > 0) $title_list .= '|';
                $title_list .= $r['title'];
            }

            $info_url = $api_base . '?action=query&titles=' . urlencode($title_list) . '&prop=imageinfo&iiprop=url|size|mime|extmetadata&format=json';
            $info_result = $fetch_json($info_url, $timeout);

            $image_info_map = [];
            if ($info_result['success']) {
                $pages = $info_result['data']['query']['pages'] ?? [];
                foreach ($pages as $page_id => $page) {
                    if ((int)$page_id < 0) continue;
                    $infos = $page['imageinfo'] ?? [];
                    if (!empty($infos)) {
                        $image_info_map[$page['title']] = $infos[0];
                    }
                }
            }

            // Step 3: Build structured results
            $image_results = [];
            foreach ($results as $r) {
                $title = $r['title'];
                $info = $image_info_map[$title] ?? [];

                $url = $info['url'] ?? '';
                $width = (int)($info['width'] ?? 0);
                $height = (int)($info['height'] ?? 0);
                $mime = $info['mime'] ?? '';
                $size_bytes = (int)($info['size'] ?? 0);

                if ($width <= 0 || $height <= 0) continue;
                if ($width < $min_width) continue;

                $desc = '';
                if (isset($info['extmetadata']['ImageDescription']['value'])) {
                    $desc = $info['extmetadata']['ImageDescription']['value'];
                } elseif (isset($info['extmetadata']['ObjectName']['value'])) {
                    $desc = $info['extmetadata']['ObjectName']['value'];
                }
                $desc = strip_tags($desc);
                if (strlen($desc) > 300) $desc = substr($desc, 0, 300) . '...';

                $artist_raw = $info['extmetadata']['Artist']['value'] ?? '';
                $artist = strip_tags($artist_raw);
                if (strlen($artist) > 100) $artist = substr($artist, 0, 100) . '...';

                $license = $info['extmetadata']['LicenseShortName']['value'] ?? '';
                $page_url = 'https://commons.wikimedia.org/wiki/' . str_replace(' ', '_', $title);

                $image_results[] = [
                    'title' => $title,
                    'page_url' => $page_url,
                    'direct_url' => $url,
                    'width' => $width, 'height' => $height,
                    'mime_type' => $mime, 'size_bytes' => $size_bytes,
                    'description' => $desc, 'artist' => $artist, 'license' => $license,
                ];
            }

            // Step 4: Download the best match
            $downloaded = null;
            if ($download_best && !empty($image_results)) {
                usort($image_results, fn($a, $b) => ($b['width'] * $b['height']) - ($a['width'] * $a['height']));
                $best = $image_results[0];

                if (!empty($best['direct_url'])) {
                    $dl_dir = $workspace . '/downloads';
                    if (!is_dir($dl_dir)) @mkdir($dl_dir, 0777, true);

                    // Determine extension from MIME type
                    $mime_to_ext = [
                        'image/jpeg' => 'jpg', 'image/png' => 'png', 'image/gif' => 'gif',
                        'image/webp' => 'webp', 'image/svg+xml' => 'svg', 'image/bmp' => 'bmp',
                    ];
                    $ext = $mime_to_ext[$best['mime_type']] ?? 'bin';

                    // Sanitize filename
                    $safe_name = preg_replace('/[^a-zA-Z0-9_-]/', '_', str_replace(' ', '_', $best['title']));
                    $safe_name = preg_replace('/^File_/', '', $safe_name);
                    $safe_name = substr($safe_name, 0, 80);
                    $filename = $safe_name . '.' . $ext;
                    $filepath = $dl_dir . '/' . $filename;

                    // Download with error checking
                    $dl_result = $download_file($best['direct_url'], $filepath, $timeout);

                    if ($dl_result['success']) {
                        // Verify with finfo
                        $detected_mime = 'unknown';
                        if (function_exists('finfo_open')) {
                            $finfo = @finfo_open(FILEINFO_MIME_TYPE);
                            if ($finfo) {
                                $detected_mime = @finfo_file($finfo, $filepath) ?: 'unknown';
                                @finfo_close($finfo);
                            }
                        }
                        $valid = strpos($detected_mime, 'image/') === 0;

                        $downloaded = [
                            'filename' => 'downloads/' . $filename,
                            'full_path' => 'storage/agent/workspace/downloads/' . $filename,
                            'file_size_bytes' => $dl_result['size'],
                            'detected_mime' => $detected_mime,
                            'expected_dimensions' => $best['width'] . 'x' . $best['height'],
                            'valid_image' => $valid,
                            'source_url' => $best['direct_url'],
                            'http_status' => $dl_result['status'],
                        ];
                    } else {
                        $downloaded = [
                            'error' => $dl_result['error'],
                            'http_status' => $dl_result['status'] ?? null,
                            'content_type' => $dl_result['content_type'] ?? null,
                            'source_url' => $best['direct_url'],
                        ];

                        // Clean up partial download
                        if (file_exists($filepath)) @unlink($filepath);
                    }
                }
            }

            return [
                'success' => true,
                'query' => $query,
                'total_results' => count($image_results),
                'total_api_hits' => count($results),
                'results' => $image_results,
                'downloaded' => $downloaded,
            ];
    }
}
