<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_image_analysis = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'image_analysis',
    'description' => 'Process an image file using PHP\'s GD extension: find dominant colors, compute color histogram, detect if mostly dark/light, extract average brightness, and report primary color palette. Takes any image path relative to project root (JPEG, PNG, GIF, WEBP, BMP). First tool in the ecosystem to perform pixel-level image analysis. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'path' => 
        array (
          'type' => 'string',
          'description' => 'Path to the image file relative to project root (e.g. \'storage/agent/workspace/downloads/image.png\').',
        ),
        'max_colors' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum dominant colors to return (1-20, default: 8).',
        ),
        'histogram_buckets' => 
        array (
          'type' => 'integer',
          'description' => 'Number of buckets for the brightness histogram (2-32, default: 10).',
        ),
      ),
      'required' => 
      array (
        0 => 'path',
      ),
    ),
  ),
);

if (! function_exists('image_analysis')) {
    function image_analysis($path, $max_colors = null, $histogram_buckets = null)
    {
        // Image Analysis v3 — fixed project root path resolution
        $path = $path ?? '';
        $max_colors = $max_colors ?? 8;
        $histogram_buckets = $histogram_buckets ?? 10;

        if (empty($path)) return ['error' => 'path is required', 'success' => false];
        $max_colors = max(1, min(20, (int)$max_colors));
        $histogram_buckets = max(2, min(32, (int)$histogram_buckets));

        // Tools dir: /project/storage/agent/tools/
        // Project root: /project/
        $project_root = realpath(__DIR__ . '/../../../');
        $full_path = $project_root . '/' . ltrim($path, '/');

        if (!file_exists($full_path)) {
            return ['error' => "File not found: $path", 'success' => false];
        }

        $info = @getimagesize($full_path);
        if ($info === false) return ['error' => 'Not a valid image or format not supported', 'success' => false];

        $width = $info[0];
        $height = $info[1];
        $mime = $info['mime'];
        $file_size = filesize($full_path);

        $img = null;
        switch ($mime) {
            case 'image/jpeg': case 'image/jpg': $img = @imagecreatefromjpeg($full_path); break;
            case 'image/png':  $img = @imagecreatefrompng($full_path); break;
            case 'image/gif':  $img = @imagecreatefromgif($full_path); break;
            case 'image/webp': $img = @imagecreatefromwebp($full_path); break;
            case 'image/bmp':  $img = @imagecreatefrombmp($full_path); break;
            default: return ['error' => "Unsupported format: $mime", 'success' => false];
        }
        if ($img === false) return ['error' => 'GD failed to load image', 'success' => false];

        $sw = imagesx($img);
        $sh = imagesy($img);
        $total_pixels = $sw * $sh;

        // Adaptive sampling for performance
        $sample = 1;
        if ($total_pixels > 500000) $sample = max(2, (int)ceil(sqrt($total_pixels / 500000)));

        $pixel_count = 0;
        $color_counts = [];
        $sum_r = 0; $sum_g = 0; $sum_b = 0;
        $hist_buckets = array_fill(0, $histogram_buckets, 0);

        for ($y = 0; $y < $sh; $y += $sample) {
            for ($x = 0; $x < $sw; $x += $sample) {
                $rgb = imagecolorat($img, $x, $y);
                $r = ($rgb >> 16) & 0xFF;
                $g = ($rgb >> 8) & 0xFF;
                $b = $rgb & 0xFF;
                
                $sum_r += $r; $sum_g += $g; $sum_b += $b;
                
                // Quantize to 32-step for dominant color detection
                $key = sprintf('%02x%02x%02x',
                    (int)(min(255, round($r / 32) * 32)),
                    (int)(min(255, round($g / 32) * 32)),
                    (int)(min(255, round($b / 32) * 32))
                );
                if (!isset($color_counts[$key])) $color_counts[$key] = 0;
                $color_counts[$key]++;
                
                $lum = 0.2126 * $r + 0.7152 * $g + 0.0722 * $b;
                $bi = (int)min($histogram_buckets - 1, max(0, floor($lum / 256 * $histogram_buckets)));
                $hist_buckets[$bi]++;
                
                $pixel_count++;
            }
        }
        imagedestroy($img);

        if ($pixel_count === 0) return ['error' => 'No pixels sampled', 'success' => false];

        $avg_r = (int)round($sum_r / $pixel_count);
        $avg_g = (int)round($sum_g / $pixel_count);
        $avg_b = (int)round($sum_b / $pixel_count);
        $avg_hex = sprintf('%02x%02x%02x', $avg_r, $avg_g, $avg_b);
        $avg_lum = round(($sum_r * 0.2126 + $sum_g * 0.7152 + $sum_b * 0.0722) / $pixel_count, 1);

        // Dominant colors
        arsort($color_counts);
        $dominant = [];
        $i = 0;
        foreach ($color_counts as $hex => $cnt) {
            $i++;
            $pct = round($cnt / $pixel_count * 100, 2);
            $cr = hexdec(substr($hex, 0, 2));
            $cg = hexdec(substr($hex, 2, 2));
            $cb = hexdec(substr($hex, 4, 2));
            $dominant[] = [
                'rank' => $i, 'hex' => '#' . $hex,
                'rgb' => ['r' => $cr, 'g' => $cg, 'b' => $cb],
                'percentage' => $pct,
            ];
            if ($i >= $max_colors) break;
        }

        // Brightness histogram
        $histogram = [];
        $bsize = 256 / $histogram_buckets;
        foreach ($hist_buckets as $bi => $cnt) {
            $lo = (int)($bi * $bsize);
            $hi = (int)(($bi + 1) * $bsize - 1);
            $histogram[] = [
                'bucket' => $bi + 1, 'range' => "$lo-$hi",
                'label' => $lo < 85 ? 'Dark' : ($lo < 171 ? 'Mid' : 'Light'),
                'percentage' => round($cnt / $pixel_count * 100, 2),
            ];
        }

        // Overall tone
        $dark = array_sum(array_column(array_filter($histogram, fn($b) => $b['label'] === 'Dark'), 'percentage'));
        $light = array_sum(array_column(array_filter($histogram, fn($b) => $b['label'] === 'Light'), 'percentage'));
        $tone = $dark > 60 ? 'Mostly Dark' : ($light > 60 ? 'Mostly Light' : 'Balanced');

        // Colorfulness
        $colorfulness = round(sqrt(($avg_r - $avg_g)**2 + ($avg_r - $avg_b)**2 + ($avg_g - $avg_b)**2), 1);

        return [
            'success' => true,
            'image' => [
                'path' => $path, 'file_size' => $file_size,
                'width' => $width, 'height' => $height,
                'mime_type' => $mime,
                'orientation' => $width > $height ? 'landscape' : ($width < $height ? 'portrait' : 'square'),
            ],
            'analysis' => [
                'pixels_sampled' => $pixel_count,
                'sample_rate' => $sample,
                'average_color' => '#' . $avg_hex,
                'average_rgb' => ['r' => $avg_r, 'g' => $avg_g, 'b' => $avg_b],
                'average_brightness' => $avg_lum,
                'average_brightness_pct' => round($avg_lum / 255 * 100, 1),
                'overall_tone' => $tone,
                'colorfulness' => $colorfulness,
                'colorfulness_label' => $colorfulness < 20 ? 'Grayscale' : ($colorfulness < 60 ? 'Desaturated' : ($colorfulness < 120 ? 'Moderate' : 'Vibrant')),
            ],
            'dominant_colors' => $dominant,
            'brightness_histogram' => $histogram,
        ];
    }
}
