<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_ip_geolocation = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'ip_geolocation',
    'description' => 'Look up the geographic location, ISP, and ASN of an IP address using the free ip-api.com service (no API key required). Returns city, country, region, coordinates, timezone, ISP name, organization, and AS number. If given a hostname instead of an IP, resolves it first. If no IP is provided, looks up the current machine\'s public IP. First geospatial capability in the ecosystem — maps network addresses to physical locations on Earth. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'ip' => 
        array (
          'type' => 'string',
          'description' => 'IP address to look up (e.g. \'8.8.8.8\', \'140.82.121.4\'). If empty, looks up the current machine\'s public IP. If a hostname is given, it\'s resolved first.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (5-30, default: 15).',
        ),
        'fields' => 
        array (
          'type' => 'string',
          'description' => 'Comma-separated list of fields to return. Default: all. Options: status,country,countryCode,region,regionName,city,zip,lat,lon,timezone,isp,org,as,query,continent,continentCode,district,asname,reverse,mobile,proxy,hosting.',
        ),
      ),
      'required' => 
      array (
      ),
    ),
  ),
);

if (! function_exists('ip_geolocation')) {
    function ip_geolocation($ip = null, $timeout = null, $fields = null)
    {
            $ip = $ip ?? '';
            $timeout = $timeout ?? 15;
            $fields = $fields ?? '';

            $timeout = max(5, min(30, (int)$timeout));

            // Helper: fetch JSON
            $fetch_json = function($url, $t) {
                $ctx = stream_context_create([
                    'http' => ['method' => 'GET', 'timeout' => $t, 'header' => "User-Agent: ip_geolocation/1.0\r\n", 'ignore_errors' => true],
                    'ssl' => ['verify_peer' => false, 'verify_peer_name' => false],
                ]);
                $body = @file_get_contents($url, false, $ctx);
                if ($body === false) return ['error' => error_get_last()['message'] ?? 'fetch failed', 'success' => false];
                $status = 200;
                if (isset($http_response_header)) {
                    foreach ($http_response_header as $h) {
                        if (preg_match('#^HTTP/\d+\.\d+ (\d+)#', $h, $m)) { $status = (int)$m[1]; break; }
                    }
                }
                $data = @json_decode($body, true);
                if ($data === null) return ['error' => 'Invalid JSON response', 'success' => false];
                return ['data' => $data, 'status' => $status, 'success' => true];
            };

            $query = trim($ip);

            // If query is empty, look up the caller's own IP
            if (empty($query)) {
                // Use a simple echo service
                $echo = $fetch_json('http://ip-api.com/json/', $timeout);
                if (!$echo['success']) {
                    return ['success' => false, 'error' => 'Failed to determine current IP: ' . $echo['error']];
                }
                // Return the geolocation data directly
                $data = $echo['data'];
                if (!isset($data['status']) || $data['status'] === 'fail') {
                    return ['success' => false, 'error' => $data['message'] ?? 'Unknown geolocation failure', 'query' => $query];
                }
                $data['query_method'] = 'auto';
                return ['success' => true] + $data;
            }

            // Check if input is an IP or hostname
            $is_ip_addr = (bool)preg_match('/^\d+\.\d+\.\d+\.\d+$/', $query);

            if (!$is_ip_addr) {
                // It's a hostname — resolve it first
                $resolved = @gethostbyname($query);
                if ($resolved === $query) {
                    return ['success' => false, 'error' => "Could not resolve hostname: '$query'", 'query' => $query];
                }
                $resolved_ip = $resolved;

                // Check for private/reserved IPs
                $is_private = (bool)preg_match('/^(10\.|172\.(1[6-9]|2\d|3[01])\.|192\.168\.|127\.|0\.|169\.254\.)/', $resolved_ip);
                if ($is_private) {
                    return [
                        'success' => true,
                        'query' => $query,
                        'resolved_ip' => $resolved_ip,
                        'note' => 'Private/reserved IP — no geolocation data available.',
                        'is_private' => true,
                        'country' => 'Reserved',
                        'city' => 'N/A',
                    ];
                }

                $query_to_use = $resolved_ip;
            } else {
                // It's an IP address
                // Check for private/reserved IPs
                $is_private = (bool)preg_match('/^(10\.|172\.(1[6-9]|2\d|3[01])\.|192\.168\.|127\.|0\.|169\.254\.)/', $query);
                if ($is_private) {
                    return [
                        'success' => true,
                        'query' => $query,
                        'note' => 'Private/reserved IP — no geolocation data available.',
                        'is_private' => true,
                        'country' => 'Reserved',
                        'city' => 'N/A',
                    ];
                }
                $query_to_use = $query;
            }

            // Build the API URL
            $api_url = "http://ip-api.com/json/{$query_to_use}";
            if (!empty($fields)) {
                $api_url .= '?fields=' . urlencode($fields);
            }

            $result = $fetch_json($api_url, $timeout);

            if (!$result['success']) {
                return [
                    'success' => false,
                    'error' => 'Geolocation API request failed: ' . $result['error'],
                    'query' => $query,
                    'resolved_ip' => $query_to_use ?? null,
                ];
            }

            if ($result['status'] >= 400) {
                return [
                    'success' => false,
                    'error' => "Geolocation API returned HTTP {$result['status']}",
                    'query' => $query,
                    'resolved_ip' => $query_to_use ?? null,
                ];
            }

            $data = $result['data'];

            if (!isset($data['status']) || $data['status'] === 'fail') {
                return [
                    'success' => false,
                    'error' => $data['message'] ?? 'Geolocation lookup failed for this IP',
                    'query' => $query,
                    'resolved_ip' => $query_to_use ?? null,
                ];
            }

            // Build a clean response
            $response = [
                'success' => true,
                'query' => $query,
            ];

            if (!$is_ip_addr && isset($resolved_ip)) {
                $response['resolved_ip'] = $resolved_ip;
            }

            // Map common fields to clean structure
            $field_mappings = [
                'country' => 'country',
                'countryCode' => 'country_code',
                'region' => 'region_code',
                'regionName' => 'region',
                'city' => 'city',
                'zip' => 'postal_code',
                'lat' => 'latitude',
                'lon' => 'longitude',
                'timezone' => 'timezone',
                'isp' => 'isp',
                'org' => 'organization',
                'as' => 'asn',
                'asname' => 'asn_name',
                'continent' => 'continent',
                'continentCode' => 'continent_code',
                'district' => 'district',
                'reverse' => 'reverse_dns',
                'mobile' => 'is_mobile',
                'proxy' => 'is_proxy',
                'hosting' => 'is_hosting',
                'status' => 'api_status',
                'query' => 'queried_ip',
            ];

            foreach ($field_mappings as $api_key => $response_key) {
                if (isset($data[$api_key])) {
                    $response[$response_key] = $data[$api_key];
                }
            }

            return $response;
    }
}
