<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_markdown_table_export = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'markdown_table_export',
    'description' => 'Export the results of a SQL query (from any SQLite database in the workspace) as a formatted Markdown table. Useful for composing SQL queries into reports, documentation, or feeding results to scheduled_report. Pure read-only — never modifies the source database. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'sql' => 
        array (
          'type' => 'string',
          'description' => 'SQL SELECT query to execute.',
        ),
        'db_name' => 
        array (
          'type' => 'string',
          'description' => 'SQLite database filename in workspace (default: \'rss_archive.sqlite\').',
        ),
        'params' => 
        array (
          'type' => 'array',
          'description' => 'Optional parameter values for prepared statement placeholders (?).',
          'items' => 
          (object) array(
          ),
        ),
        'max_rows' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum rows to include in table (0=all, default: 20).',
        ),
        'title' => 
        array (
          'type' => 'string',
          'description' => 'Optional H2 title above the table.',
        ),
      ),
      'required' => 
      array (
        0 => 'sql',
      ),
    ),
  ),
);

if (! function_exists('markdown_table_export')) {
    function markdown_table_export($sql, $db_name = null, $params = null, $max_rows = null, $title = null)
    {
        // Markdown table export from SQLite
        $sql=isset($sql)?(string)$sql:'';
        $db_name=isset($db_name)?(string)$db_name:'rss_archive.sqlite';
        $params=isset($params)?(array)$params:[];
        $max_rows=isset($max_rows)?max(0,(int)$max_rows):20;
        $title=isset($title)?(string)$title:'';
        if($sql==='')return['error'=>'SQL required'];

        $ws=realpath(__DIR__.'/../../workspace');
        $db=$ws.'/'.$db_name;
        if(!file_exists($db))return['error'=>"DB not found: {$db_name}"];

        try{
            $pdo=new PDO("sqlite:{$db}");
            $pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
            $stmt=$pdo->prepare($sql);
            $stmt->execute($params);
            $rows=$stmt->fetchAll(PDO::FETCH_ASSOC);
            
            if(count($rows)===0)return['success'=>true,'markdown'=>'_(no rows)_','row_count'=>0];
            
            $cols=array_keys($rows[0]);
            $display_rows=$max_rows>0?array_slice($rows,0,$max_rows):$rows;
            $truncated=count($rows)>count($display_rows);
            
            $md='';
            if($title!=='')$md.="## {$title}\n\n";
            
            // Header
            $md.='| '.implode(' | ',array_map('escapeMd',$cols))." |\n";
            $md.='| '.implode(' | ',array_fill(0,count($cols),'---'))." |\n";
            
            // Rows
            foreach($display_rows as$row){
                $vals=array_map(function($v){
                    if($v===null)return '*null*';
                    $s=str_replace('|','\\|',(string)$v);
                    if(strlen($s)>100)$s=substr($s,0,97).'...';
                    return $s;
                },array_values($row));
                $md.='| '.implode(' | ',$vals)." |\n";
            }
            
            if($truncated)$md.="\n_Showing {$max_rows} of ".count($rows)." rows_\n";
            
            return[
                'success'=>true,
                'markdown'=>$md,
                'row_count'=>count($rows),
                'rows_shown'=>count($display_rows),
                'truncated'=>$truncated,
                'columns'=>$cols,
            ];
            
        }catch(\Throwable$e){return['error'=>'Query failed: '.$e->getMessage()];}

        function escapeMd($s){return str_replace(['|','[',']'],['\\|','\\[','\\]'],(string)$s);}
    }
}
