<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_markdown_to_html = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'markdown_to_html',
    'description' => 'Convert Markdown text to clean HTML. Supports: headings (# to h1-h6), bold/italic (**strong** *em*), links [text](url), images ![alt](src), inline code (`), fenced code blocks (``` with language), ordered/unordered lists (-, 1.), blockquotes (>), horizontal rules (---), tables (|), and paragraphs. Handles nested formatting. Complements html_to_markdown (HTML→MD) by providing the inverse conversion. First Markdown rendering tool in the ecosystem. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'markdown' => 
        array (
          'type' => 'string',
          'description' => 'Markdown text to convert to HTML. Required.',
        ),
        'add_wrapper' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, wrap output in <div class=\'markdown\'> ... </div> (default: false).',
        ),
        'escape_html' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, escape HTML reserved characters in text content (< > &) (default: true).',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (1-10, default: 5).',
        ),
      ),
      'required' => 
      array (
        0 => 'markdown',
      ),
    ),
  ),
);

if (! function_exists('markdown_to_html')) {
    function markdown_to_html($markdown, $add_wrapper = null, $escape_html = null, $timeout = null)
    {
        $markdown = $markdown ?? '';
        $add_wrapper = $add_wrapper ?? false;
        $escape_html = $escape_html ?? true;
        $timeout = $timeout ?? 5;

        if (empty($markdown)) {
            return ['error' => 'No markdown content provided.'];
        }

        $start = microtime(true);

        $esc = function($text) use ($escape_html) {
            if (!$escape_html) return $text;
            return htmlspecialchars($text, ENT_QUOTES | ENT_HTML5, 'UTF-8', false);
        };

        // Convert inline Markdown to HTML — code backticks processed first to protect content
        $inline = function($text) use ($esc) {
            // Step 1: Extract code spans and replace with placeholders
            $code_spans = [];
            $text = preg_replace_callback('/`([^`]+)`/', function($m) use (&$code_spans, $esc) {
                $idx = count($code_spans);
                $code_spans[] = '<code>' . $esc($m[1]) . '</code>';
                return "\x00CODE{$idx}\x00";
            }, $text);
            
            // Step 2: Apply other inline formatting
            // Images: ![alt](src)
            $text = preg_replace_callback('/!\[([^\]]*)\]\(([^)]+)\)/', function($m) use ($esc) {
                return '<img src="' . $esc($m[2]) . '" alt="' . $esc($m[1]) . '">';
            }, $text);
            
            // Links: [text](url)
            $text = preg_replace_callback('/\[([^\]]+)\]\(([^)]+)\)/', function($m) use ($esc) {
                return '<a href="' . $esc($m[2]) . '">' . $m[1] . '</a>';
            }, $text);
            
            // Bold: **text** or __text__
            $text = preg_replace('/\*\*(.+?)\*\*/', '<strong>$1</strong>', $text);
            $text = preg_replace('/__(.+?)__/', '<strong>$1</strong>', $text);
            
            // Italic: *text* or _text_
            $text = preg_replace('/\*(.+?)\*/', '<em>$1</em>', $text);
            $text = preg_replace('/_(.+?)_/', '<em>$1</em>', $text);
            
            // Strikethrough: ~~text~~
            $text = preg_replace('/~~(.+?)~~/', '<del>$1</del>', $text);
            
            // Step 3: Restore code spans
            foreach ($code_spans as $idx => $code_html) {
                $text = str_replace("\x00CODE{$idx}\x00", $code_html, $text);
            }
            
            return $text;
        };

        $lines = explode("\n", $markdown);
        $html = '';
        $i = 0;
        $inCode = false;

        while ($i < count($lines)) {
            $line = rtrim($lines[$i]);
            $next = ($i + 1 < count($lines)) ? rtrim($lines[$i + 1]) : '';
            
            // Fenced code blocks
            if (preg_match('/^```(\w*)/', $line, $m)) {
                if ($inCode) {
                    $html .= "</code></pre>\n\n";
                    $inCode = false;
                } else {
                    $lang = $m[1];
                    $html .= "<pre><code" . ($lang ? " class=\"language-{$lang}\"" : '') . ">\n";
                    $inCode = true;
                }
                $i++;
                continue;
            }
            
            if ($inCode) {
                $html .= $esc($line) . "\n";
                $i++;
                continue;
            }
            
            // Horizontal rule
            if (preg_match('/^[-*_]{3,}\s*$/', $line)) {
                $html = rtrim($html) . "\n<hr>\n\n";
                $i++;
                continue;
            }
            
            // Headings
            if (preg_match('/^(#{1,6})\s+(.+)$/', $line, $m)) {
                $level = strlen($m[1]);
                $html .= "<h{$level}>" . $inline(trim($m[2])) . "</h{$level}>\n\n";
                $i++;
                continue;
            }
            
            // Blockquotes — handle multi-line
            if (preg_match('/^>\s?(.*)$/', $line, $m)) {
                $bq_lines = [];
                while ($i < count($lines)) {
                    $bl = rtrim($lines[$i]);
                    if (!preg_match('/^>\s?(.*)$/', $bl, $bm)) break;
                    $bq_lines[] = $bm[1];
                    $i++;
                }
                $bq_text = implode("\n", $bq_lines);
                $bq_paras = preg_split('/\n\n+/', trim($bq_text));
                $html .= "<blockquote>\n";
                foreach ($bq_paras as $bp) {
                    if (trim($bp) !== '') {
                        $html .= "<p>" . $inline(trim($bp)) . "</p>\n";
                    }
                }
                $html .= "</blockquote>\n\n";
                continue;
            }
            
            // Tables
            if (strpos($line, '|') !== false && preg_match('/^\|/', $line)) {
                $rows = [];
                while ($i < count($lines)) {
                    $tl = rtrim($lines[$i]);
                    if (!preg_match('/^\|/', $tl)) break;
                    $cells = array_map('trim', explode('|', trim($tl, '|')));
                    
                    // Skip separator row (|---|---|)
                    if (preg_match('/^[\s\|:-]+$/', str_replace('|', '', implode('', $cells)))) {
                        $i++;
                        continue;
                    }
                    $rows[] = $cells;
                    $i++;
                }
                
                if (!empty($rows)) {
                    $html .= "<table>\n<thead>\n<tr>\n";
                    foreach ($rows[0] as $cell) {
                        $html .= "  <th>" . $inline($cell) . "</th>\n";
                    }
                    $html .= "</tr>\n</thead>\n";
                    if (count($rows) > 1) {
                        $html .= "<tbody>\n";
                        for ($r = 1; $r < count($rows); $r++) {
                            $html .= "<tr>\n";
                            foreach ($rows[$r] as $cell) {
                                $html .= "  <td>" . $inline($cell) . "</td>\n";
                            }
                            $html .= "</tr>\n";
                        }
                        $html .= "</tbody>\n";
                    }
                    $html .= "</table>\n\n";
                }
                continue;
            }
            
            // Unordered list
            if (preg_match('/^[-*+]\s+(.+)$/', $line, $m)) {
                $html .= "<ul>\n";
                while ($i < count($lines)) {
                    $ll = rtrim($lines[$i]);
                    if (preg_match('/^[-*+]\s+(.+)$/', $ll, $lm)) {
                        $html .= "<li>" . $inline($lm[1]) . "</li>\n";
                        $i++;
                    } elseif (trim($ll) === '') {
                        $i++;
                        break;
                    } else {
                        break;
                    }
                }
                $html .= "</ul>\n\n";
                continue;
            }
            
            // Ordered list
            if (preg_match('/^\d+\.\s+(.+)$/', $line, $m)) {
                $html .= "<ol>\n";
                while ($i < count($lines)) {
                    $ll = rtrim($lines[$i]);
                    if (preg_match('/^\d+\.\s+(.+)$/', $ll, $lm)) {
                        $html .= "<li>" . $inline($lm[1]) . "</li>\n";
                        $i++;
                    } elseif (trim($ll) === '') {
                        $i++;
                        break;
                    } else {
                        break;
                    }
                }
                $html .= "</ol>\n\n";
                continue;
            }
            
            // Empty line
            if (trim($line) === '') {
                $i++;
                continue;
            }
            
            // Regular paragraph (may span multiple lines)
            $paragraph = $line;
            $i++;
            while ($i < count($lines)) {
                $nl = rtrim($lines[$i]);
                if ($nl === '' || preg_match('/^(#|>|[-*+]\s|\d+\.\s|\||---)/', $nl)) break;
                $paragraph .= ' ' . $nl;
                $i++;
            }
            $html .= "<p>" . $inline($paragraph) . "</p>\n\n";
        }

        if ($inCode) $html .= "</code></pre>\n";

        $html = trim($html);
        if ($add_wrapper) {
            $html = "<div class=\"markdown\">\n" . $html . "\n</div>";
        }

        $elapsed = round(microtime(true) - $start, 4);

        $stats = [
            'headings' => preg_match_all('/<\/h[1-6]>/', $html),
            'paragraphs' => preg_match_all('/<\/p>/', $html),
            'links' => preg_match_all('/<\/a>/', $html),
            'images' => preg_match_all('/<img /', $html),
            'code_blocks' => preg_match_all('/<\/code><\/pre>/', $html),
            'lists' => preg_match_all('/<\/[ou]l>/', $html),
            'blockquotes' => preg_match_all('/<\/blockquote>/', $html),
            'tables' => preg_match_all('/<\/table>/', $html),
        ];

        return [
            'success' => true,
            'html' => $html,
            'output_length' => strlen($html),
            'input_length' => strlen($markdown),
            'stats' => $stats,
            'elapsed_seconds' => $elapsed,
        ];
    }
}
