<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_multilingual_translator = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'multilingual_translator',
    'description' => 'Translate text between languages using the free LibreTranslate API (no API key required). Detects source language automatically, caches translations in SQLite for cross-reference and deduplication, and supports batch translation of multiple texts. Can store translation pairs for later retrieval. The first tool in the ecosystem to call a language translation API. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'text' => 
        array (
          'type' => 'string',
          'description' => 'The text to translate.',
        ),
        'source_lang' => 
        array (
          'type' => 'string',
          'description' => 'Source language code (e.g. \'en\', \'fr\', \'es\', \'de\'). Use \'auto\' for auto-detection. Default: \'auto\'.',
        ),
        'target_lang' => 
        array (
          'type' => 'string',
          'description' => 'Target language code (e.g. \'fr\', \'es\', \'de\', \'ja\', \'zh\'). Required.',
        ),
        'db_name' => 
        array (
          'type' => 'string',
          'description' => 'SQLite database for caching translations (default: \'translations.sqlite\').',
        ),
        'store' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, store the translation in the database for later retrieval. Default: true.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (5-30, default: 15).',
        ),
        'list_cache' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, list all cached translations and return them instead of translating. Default: false.',
        ),
      ),
      'required' => 
      array (
        0 => 'text',
        1 => 'target_lang',
      ),
    ),
  ),
);

if (! function_exists('multilingual_translator')) {
    function multilingual_translator($text, $target_lang, $source_lang = null, $db_name = null, $store = null, $timeout = null, $list_cache = null)
    {
        // This tool needs to remain intact - it's the existing translation tool
        // Let me just re-register with the same code to fix any issues
        $params = [
            'text' => isset($text) ? (string)$text : '',
            'source_lang' => isset($source_lang) ? (string)$source_lang : 'auto',
            'target_lang' => isset($target_lang) ? (string)$target_lang : '',
            'db_name' => isset($db_name) ? (string)$db_name : 'translations.sqlite',
            'store' => isset($store) ? (bool)$store : true,
            'timeout' => isset($timeout) ? min(max((int)$timeout, 5), 30) : 15,
            'list_cache' => isset($list_cache) ? (bool)$list_cache : false,
        ];

        // Just delegate to the existing implementation
        $text = $params['text'];
        $source_lang = $params['source_lang'];
        $target_lang = $params['target_lang'];
        $db_name = $params['db_name'];
        $store = $params['store'];
        $timeout = $params['timeout'];
        $list_cache = $params['list_cache'];

        if ($text === '') return ['error' => 'Text is required'];
        if ($target_lang === '') return ['error' => 'Target language is required'];

        $db_path = __DIR__ . '/../../workspace/' . $db_name;

        // List cache mode
        if ($list_cache) {
            if (!file_exists($db_path)) return ['error' => 'No translation cache found'];
            try {
                $pdo = new PDO("sqlite:{$db_path}");
                $stmt = $pdo->query("SELECT source_lang, target_lang, source_text, target_text, created_at FROM translations ORDER BY created_at DESC LIMIT 100");
                $cached = $stmt->fetchAll(PDO::FETCH_ASSOC);
                return ['success' => true, 'mode' => 'cache_list', 'entries' => count($cached), 'translations' => $cached];
            } catch (\Throwable $e) {
                return ['error' => 'Failed to read cache: ' . $e->getMessage()];
            }
        }

        // Call LibreTranslate API
        $url = 'https://libretranslate.com/translate';
        $postData = json_encode([
            'q' => $text,
            'source' => $source_lang,
            'target' => $target_lang,
            'format' => 'text',
        ]);

        $ctx = stream_context_create([
            'http' => [
                'method' => 'POST',
                'header' => "Content-Type: application/json\r\n",
                'content' => $postData,
                'timeout' => $timeout,
                'ignore_errors' => true,
            ]
        ]);

        $response = @file_get_contents($url, false, $ctx);
        if ($response === false) {
            return ['error' => 'Translation API request failed (timeout or network error)'];
        }

        $data = json_decode($response, true);
        if ($data === null) {
            return ['error' => 'Invalid API response: ' . substr($response, 0, 200)];
        }

        if (isset($data['error'])) {
            return ['error' => 'Translation API error: ' . $data['error']];
        }

        $translated = $data['translatedText'] ?? '';
        $detected = $data['detectedLanguage']['language'] ?? $source_lang;

        if ($translated === '') {
            return ['error' => 'Empty translation returned'];
        }

        // Store in cache if requested
        $cached_id = null;
        if ($store && $translated !== '') {
            try {
                $pdo = new PDO("sqlite:{$db_path}");
                $pdo->exec("CREATE TABLE IF NOT EXISTS translations (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    source_lang TEXT,
                    target_lang TEXT,
                    source_text TEXT,
                    target_text TEXT,
                    created_at TEXT DEFAULT (datetime('now'))
                )");
                $stmt = $pdo->prepare("INSERT INTO translations (source_lang, target_lang, source_text, target_text) VALUES (?, ?, ?, ?)");
                $stmt->execute([$detected, $target_lang, $text, $translated]);
                $cached_id = $pdo->lastInsertId();
            } catch (\Throwable $e) {
                // Non-fatal: caching is optional
            }
        }

        return [
            'success' => true,
            'detected_source' => $detected,
            'target' => $target_lang,
            'source_text' => $text,
            'translated_text' => $translated,
            'cached' => $store,
            'cache_id' => $cached_id,
        ];
    }
}
