<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_natural_date_parser = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'natural_date_parser',
    'description' => 'Parse human-readable natural language date/time expressions into structured date information. Supports: relative dates (\'tomorrow\', \'next Friday\', \'last Monday\', \'in 3 days\', \'2 weeks from now\', \'3 months ago\'), named days (\'today\', \'yesterday\', \'day after tomorrow\'), week-anchored (\'next week\', \'last week\', \'this Tuesday\'), month boundaries (\'beginning of month\', \'end of month\', \'first day of next month\', \'last day of this month\'), year boundaries (\'beginning of year\', \'end of year\'), weekday-of-month (\'third Monday of next month\', \'last Friday of this month\'), relative time (\'in 2 hours\', \'30 minutes from now\', \'1 hour ago\'), and absolute formats (\'2025-01-15\', \'Jan 15\', \'15 January 2025\'). Returns ISO date, timestamp, human-readable description, day of week, and structural components. First natural language temporal parsing tool in the ecosystem. Pure PHP, no extensions needed. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'expression' => 
        array (
          'type' => 'string',
          'description' => 'Natural language date/time expression to parse. Examples: \'tomorrow\', \'next Friday\', \'in 3 days\', \'last day of month\', \'2 weeks from now\', \'third Monday of next month\', \'next week\', \'end of month\', \'in 2 hours\', \'Jan 15 2025\'. Required.',
        ),
        'reference_date' => 
        array (
          'type' => 'string',
          'description' => 'Reference date for relative expressions, in YYYY-MM-DD format. Default: current date.',
        ),
        'timezone' => 
        array (
          'type' => 'string',
          'description' => 'Timezone for the result (e.g. \'UTC\', \'America/New_York\', \'Asia/Tokyo\'). Default: \'UTC\'.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (1-10, default: 5).',
        ),
      ),
      'required' => 
      array (
        0 => 'expression',
      ),
    ),
  ),
);

if (! function_exists('natural_date_parser')) {
    function natural_date_parser($expression, $reference_date = null, $timezone = null, $timeout = null)
    {
        // Natural Language Date Parser
        // Parses human-readable date/time expressions into structured date info
        // Pure PHP, no extensions, no eval

        $timeout = min(10, max(1, $timeout ?? 5));
        $expression = trim($expression ?? '');
        $referenceDate = $reference_date ?? '';
        $timezone = $timezone ?? 'UTC';

        if (empty($expression)) {
            return ['success' => false, 'error' => 'Expression is required.', 'expression' => $expression];
        }

        try {
            // Day name mapping
            $dayNames = ['monday' => 1, 'tuesday' => 2, 'wednesday' => 3, 'thursday' => 4, 'friday' => 5, 'saturday' => 6, 'sunday' => 7];
            $dayNamesShort = ['mon' => 1, 'tue' => 2, 'wed' => 3, 'thu' => 4, 'fri' => 5, 'sat' => 6, 'sun' => 7];
            $allDayNames = array_merge($dayNames, $dayNamesShort);

            // Month name mapping
            $monthNames = ['january' => 1, 'february' => 2, 'march' => 3, 'april' => 4, 'may' => 5, 'june' => 6,
                'july' => 7, 'august' => 8, 'september' => 9, 'october' => 10, 'november' => 11, 'december' => 12];
            $monthNamesShort = ['jan' => 1, 'feb' => 2, 'mar' => 3, 'apr' => 4, 'may' => 5, 'jun' => 6,
                'jul' => 7, 'aug' => 8, 'sep' => 9, 'oct' => 10, 'nov' => 11, 'dec' => 12];
            $allMonthNames = array_merge($monthNames, $monthNamesShort);

            $ordinals = ['first' => 1, 'second' => 2, 'third' => 3, 'fourth' => 4, 'fifth' => 5, 'last' => -1];
            $numberWords = ['one' => 1, 'two' => 2, 'three' => 3, 'four' => 4, 'five' => 5, 'six' => 6, 'seven' => 7, 'eight' => 8, 'nine' => 9, 'ten' => 10];

            // Set reference time
            $refTs = $referenceDate ? strtotime($referenceDate) : time();
            if ($refTs === false) {
                return ['success' => false, 'error' => "Invalid reference date: '$referenceDate'. Use YYYY-MM-DD format.", 'expression' => $expression];
            }

            $refYear = (int)date('Y', $refTs);
            $refMonth = (int)date('n', $refTs);
            $refDay = (int)date('j', $refTs);
            $refDow = (int)date('N', $refTs); // 1=Monday, 7=Sunday

            $resultTs = null;
            $description = '';

            // Normalize expression
            $expr = strtolower(trim($expression));
            $expr = preg_replace('/\s+/', ' ', $expr);

            // Helper: start of day timestamp
            $tsToDayStart = function($ts) {
                return mktime(0, 0, 0, (int)date('n', $ts), (int)date('j', $ts), (int)date('Y', $ts));
            };

            // Helper: get day of week
            $dayOfWeekFn = function($ts) {
                return (int)date('N', $ts);
            };

            // Helper: get Nth weekday of a month
            $getNthWeekday = function($year, $month, $n, $dow) use ($dayOfWeekFn) {
                $startDay = mktime(0, 0, 0, $month, 1, $year);
                $daysInMonth = (int)date('t', $startDay);

                if ($n === -1) {
                    // Last occurrence
                    $endDay = mktime(0, 0, 0, $month, $daysInMonth, $year);
                    $endDow = $dayOfWeekFn($endDay);
                    $diff = $dow - $endDow;
                    if ($diff > 0) $diff -= 7;
                    return $daysInMonth + $diff;
                }

                // First, second, etc.
                $firstDow = $dayOfWeekFn($startDay);
                $diff = $dow - $firstDow;
                if ($diff < 0) $diff += 7;
                $day = 1 + $diff + ($n - 1) * 7;
                if ($day > $daysInMonth) return null;
                return $day;
            };

            $refDayStart = $tsToDayStart($refTs);

            // ====== PARSE EXPRESSIONS ======

            // --- Absolute date formats ---
            if (preg_match('/^(\d{4})-(\d{1,2})-(\d{1,2})$/', $expr, $m)) {
                $resultTs = mktime(0, 0, 0, (int)$m[2], (int)$m[3], (int)$m[1]);
                $description = date('F j, Y', $resultTs);
            }
            elseif (preg_match('/^(\d{4})[\/\.](\d{1,2})[\/\.](\d{1,2})$/', $expr, $m)) {
                $resultTs = mktime(0, 0, 0, (int)$m[2], (int)$m[3], (int)$m[1]);
                $description = date('F j, Y', $resultTs);
            }
            elseif (preg_match('/^([a-z]+)\s+(\d{1,2})[,]?\s*(\d{4})$/', $expr, $m)) {
                $mn = $allMonthNames[strtolower($m[1])] ?? null;
                if ($mn) {
                    $resultTs = mktime(0, 0, 0, $mn, (int)$m[2], (int)$m[3]);
                    $description = date('F j, Y', $resultTs);
                }
            }
            elseif (preg_match('/^(\d{1,2})\s+([a-z]+)\s+(\d{4})$/', $expr, $m)) {
                $mn = $allMonthNames[strtolower($m[2])] ?? null;
                if ($mn) {
                    $resultTs = mktime(0, 0, 0, $mn, (int)$m[1], (int)$m[3]);
                    $description = date('F j, Y', $resultTs);
                }
            }
            elseif (preg_match('/^([a-z]+)\s+(\d{1,2})$/', $expr, $m)) {
                $mn = $allMonthNames[strtolower($m[1])] ?? null;
                if ($mn) {
                    $resultTs = mktime(0, 0, 0, $mn, (int)$m[2], $refYear);
                    if ($resultTs < $refDayStart) {
                        $resultTs = mktime(0, 0, 0, $mn, (int)$m[2], $refYear + 1);
                    }
                    $description = date('F j, Y', $resultTs);
                }
            }

            // --- "today" / "now" ---
            elseif ($expr === 'today' || $expr === 'now') {
                $resultTs = $refDayStart;
                $description = 'today (' . date('F j, Y', $resultTs) . ')';
            }
            elseif ($expr === 'tomorrow') {
                $resultTs = $refDayStart + 86400;
                $description = 'tomorrow (' . date('F j, Y', $resultTs) . ')';
            }
            elseif ($expr === 'yesterday') {
                $resultTs = $refDayStart - 86400;
                $description = 'yesterday (' . date('F j, Y', $resultTs) . ')';
            }
            elseif ($expr === 'day after tomorrow') {
                $resultTs = $refDayStart + 86400 * 2;
                $description = 'day after tomorrow (' . date('F j, Y', $resultTs) . ')';
            }
            elseif ($expr === 'day before yesterday') {
                $resultTs = $refDayStart - 86400 * 2;
                $description = 'day before yesterday (' . date('F j, Y', $resultTs) . ')';
            }

            // --- "this Monday/Tuesday/..." ---
            elseif (preg_match('/^this\s+(' . implode('|', array_keys($allDayNames)) . ')$/', $expr, $m)) {
                $targetDow = $allDayNames[strtolower($m[1])];
                $diff = $targetDow - $refDow;
                $resultTs = $refDayStart + ($diff >= 0 ? $diff : $diff + 7) * 86400;
                $description = 'this ' . ucfirst($m[1]) . ' (' . date('F j, Y', $resultTs) . ')';
            }
            // --- "next Monday/Tuesday/..." ---
            elseif (preg_match('/^next\s+(' . implode('|', array_keys($allDayNames)) . ')$/', $expr, $m)) {
                $targetDow = $allDayNames[strtolower($m[1])];
                $diff = $targetDow - $refDow;
                if ($diff <= 0) $diff += 7;
                $resultTs = $refDayStart + $diff * 86400;
                $description = 'next ' . ucfirst($m[1]) . ' (' . date('F j, Y', $resultTs) . ')';
            }
            // --- "last Monday/Tuesday/..." ---
            elseif (preg_match('/^last\s+(' . implode('|', array_keys($allDayNames)) . ')$/', $expr, $m)) {
                $targetDow = $allDayNames[strtolower($m[1])];
                $diff = $targetDow - $refDow;
                if ($diff >= 0) $diff -= 7;
                $resultTs = $refDayStart + $diff * 86400;
                $description = 'last ' . ucfirst($m[1]) . ' (' . date('F j, Y', $resultTs) . ')';
            }

            // --- "next week" ---
            elseif ($expr === 'next week') {
                $diff = (8 - $refDow) % 7;
                if ($diff === 0) $diff = 7;
                $resultTs = $refDayStart + $diff * 86400;
                $description = 'next week (starting ' . date('F j, Y', $resultTs) . ')';
            }
            elseif ($expr === 'last week') {
                $diff = $refDow - 1;
                if ($diff === 0) $diff = 7;
                $resultTs = $refDayStart - $diff * 86400 - 7 * 86400;
                $description = 'last week (starting ' . date('F j, Y', $resultTs) . ')';
            }

            // --- "next month" ---
            elseif ($expr === 'next month') {
                $resultTs = mktime(0, 0, 0, $refMonth + 1, 1, $refYear);
                $description = 'next month (' . date('F Y', $resultTs) . ')';
            }
            elseif ($expr === 'last month') {
                $resultTs = mktime(0, 0, 0, $refMonth - 1, 1, $refYear);
                $description = 'last month (' . date('F Y', $resultTs) . ')';
            }

            // --- "beginning/start of month", "end of month" ---
            elseif ($expr === 'beginning of month' || $expr === 'start of month' || $expr === 'first day of month') {
                $resultTs = mktime(0, 0, 0, $refMonth, 1, $refYear);
                $description = 'beginning of ' . date('F Y', $resultTs);
            }
            elseif ($expr === 'end of month' || $expr === 'last day of month') {
                $resultTs = mktime(0, 0, 0, $refMonth, (int)date('t', $refTs), $refYear);
                $description = 'end of ' . date('F Y', $resultTs);
            }
            elseif ($expr === 'beginning of next month' || $expr === 'start of next month' || $expr === 'first day of next month') {
                $resultTs = mktime(0, 0, 0, $refMonth + 1, 1, $refYear);
                $description = 'beginning of ' . date('F Y', $resultTs);
            }
            elseif ($expr === 'end of next month' || $expr === 'last day of next month') {
                $nextMonth = $refMonth + 1;
                $nextYear = $refYear;
                if ($nextMonth > 12) { $nextMonth = 1; $nextYear++; }
                $resultTs = mktime(0, 0, 0, $nextMonth, (int)date('t', mktime(0, 0, 0, $nextMonth, 1, $nextYear)), $nextYear);
                $description = 'end of ' . date('F Y', $resultTs);
            }
            elseif ($expr === 'beginning of year' || $expr === 'start of year' || $expr === 'first day of year') {
                $resultTs = mktime(0, 0, 0, 1, 1, $refYear);
                $description = 'beginning of ' . date('Y', $resultTs);
            }
            elseif ($expr === 'end of year' || $expr === 'last day of year') {
                $resultTs = mktime(0, 0, 0, 12, 31, $refYear);
                $description = 'end of ' . date('Y', $resultTs);
            }

            // --- "in N days/weeks/months" ---
            elseif (preg_match('/^in\s+(\d+)\s+(day|days|week|weeks|month|months|year|years|hour|hours|minute|minutes)(?:\s+from\s+now)?$/', $expr, $m)) {
                $num = (int)$m[1];
                $unit = rtrim($m[2], 's');
                $multipliers = ['day' => 86400, 'week' => 604800, 'month' => 2592000, 'year' => 31536000, 'hour' => 3600, 'minute' => 60];
                $mul = $multipliers[$unit] ?? 86400;
                $resultTs = $refDayStart + $num * $mul;
                $description = "$num $unit" . ($num !== 1 ? 's' : '') . ' from now (' . date('F j, Y', $resultTs) . ')';
            }

            // --- "N days/weeks/months ago" ---
            elseif (preg_match('/^(\d+)\s+(day|days|week|weeks|month|months|year|years)\s+ago$/', $expr, $m)) {
                $num = (int)$m[1];
                $unit = rtrim($m[2], 's');
                $multipliers = ['day' => 86400, 'week' => 604800, 'month' => 2592000, 'year' => 31536000];
                $mul = $multipliers[$unit] ?? 86400;
                $resultTs = $refDayStart - $num * $mul;
                $description = $num . ' ' . $unit . ($num !== 1 ? 's' : '') . ' ago (' . date('F j, Y', $resultTs) . ')';
            }

            // --- "N days from now" ---
            elseif (preg_match('/^(\d+)\s+(day|days|week|weeks)\s+from\s+now$/', $expr, $m)) {
                $num = (int)$m[1];
                $unit = rtrim($m[2], 's');
                $multipliers = ['day' => 86400, 'week' => 604800];
                $mul = $multipliers[$unit] ?? 86400;
                $resultTs = $refDayStart + $num * $mul;
                $description = $num . ' ' . $unit . ($num !== 1 ? 's' : '') . ' from now (' . date('F j, Y', $resultTs) . ')';
            }

            // --- "in N hours", "N hours from now" ---
            elseif (preg_match('/^in\s+(\d+)\s+(hour|hours)$/', $expr, $m)) {
                $resultTs = $refTs + (int)$m[1] * 3600;
                $description = (int)$m[1] . ' hours from now';
            }
            elseif (preg_match('/^(\d+)\s+(hour|hours)\s+from\s+now$/', $expr, $m)) {
                $resultTs = $refTs + (int)$m[1] * 3600;
                $description = (int)$m[1] . ' hours from now';
            }
            elseif (preg_match('/^(\d+)\s+(minute|minutes)\s+from\s+now$/', $expr, $m)) {
                $resultTs = $refTs + (int)$m[1] * 60;
                $description = (int)$m[1] . ' minutes from now';
            }
            elseif (preg_match('/^(\d+)\s+(hour|hours)\s+ago$/', $expr, $m)) {
                $resultTs = $refTs - (int)$m[1] * 3600;
                $description = (int)$m[1] . ' hours ago';
            }
            elseif (preg_match('/^(\d+)\s+(minute|minutes)\s+ago$/', $expr, $m)) {
                $resultTs = $refTs - (int)$m[1] * 60;
                $description = (int)$m[1] . ' minutes ago';
            }

            // --- "first/second/third/last Monday/Tuesday of next/this month" ---
            elseif (preg_match('/^(first|second|third|fourth|fifth|last)\s+(' . implode('|', array_keys($allDayNames)) . ')\s+of\s+(this|next)\s+month$/', $expr, $m)) {
                $ord = $ordinals[$m[1]];
                $dow = $allDayNames[strtolower($m[2])];
                $monthOffset = $m[3] === 'next' ? 1 : 0;
                $targetMonth = $refMonth + $monthOffset;
                $targetYear = $refYear;
                if ($targetMonth > 12) { $targetMonth = 1; $targetYear++; }
                $day = $getNthWeekday($targetYear, $targetMonth, $ord, $dow);
                if ($day === null) {
                    return ['success' => false, 'error' => "The {$m[1]} {$m[2]} does not exist in the specified month.", 'expression' => $expression];
                }
                $resultTs = mktime(0, 0, 0, $targetMonth, $day, $targetYear);
                $description = $m[1] . ' ' . ucfirst($m[2]) . ' of ' . ($monthOffset === 0 ? 'this' : 'next') . ' month (' . date('F j, Y', $resultTs) . ')';
            }

            // --- "first/second/third/last Monday/Tuesday of month" ---
            elseif (preg_match('/^(first|second|third|fourth|fifth|last)\s+(' . implode('|', array_keys($allDayNames)) . ')\s+of\s+month$/', $expr, $m)) {
                $ord = $ordinals[$m[1]];
                $dow = $allDayNames[strtolower($m[2])];
                $day = $getNthWeekday($refYear, $refMonth, $ord, $dow);
                if ($day === null) {
                    return ['success' => false, 'error' => "The {$m[1]} {$m[2]} does not exist this month.", 'expression' => $expression];
                }
                $resultTs = mktime(0, 0, 0, $refMonth, $day, $refYear);
                if ($resultTs < $refDayStart) {
                    $description = 'past ' . $m[1] . ' ' . ucfirst($m[2]) . ' of this month (' . date('F j, Y', $resultTs) . ')';
                } else {
                    $description = $m[1] . ' ' . ucfirst($m[2]) . ' of this month (' . date('F j, Y', $resultTs) . ')';
                }
            }

            // --- "+N days/weeks/months" or "-N days/weeks/months" ---
            elseif (preg_match('/^([+-]?\d+)\s*(day|days|week|weeks|month|months|year|years)$/', $expr, $m)) {
                $num = (int)$m[1];
                $unit = rtrim($m[2], 's');
                $multipliers = ['day' => 86400, 'week' => 604800, 'month' => 2592000, 'year' => 31536000];
                $mul = $multipliers[$unit] ?? 86400;
                $resultTs = $refDayStart + $num * $mul;
                $description = ($num > 0 ? '+' : '') . $num . ' ' . $unit . ($num !== 1 && $num !== -1 ? 's' : '') . ' (' . date('F j, Y', $resultTs) . ')';
            }

            if ($resultTs === null) {
                // Fallback: try PHP's built-in strtotime
                $fallback = @strtotime($expression, $refTs);
                if ($fallback !== false) {
                    $resultTs = $fallback;
                    $description = 'parsed via strtotime: ' . date('F j, Y H:i:s', $resultTs);
                } else {
                    return ['success' => false, 'error' => "Unable to parse date expression: '$expression'", 'expression' => $expression];
                }
            }

            // Build result
            $result = [
                'success' => true,
                'expression' => $expression,
                'description' => $description,
                'iso_date' => date('Y-m-d', $resultTs),
                'iso_datetime' => date('Y-m-d H:i:s', $resultTs),
                'timestamp' => $resultTs,
                'year' => (int)date('Y', $resultTs),
                'month' => (int)date('n', $resultTs),
                'day' => (int)date('j', $resultTs),
                'hour' => (int)date('G', $resultTs),
                'minute' => (int)date('i', $resultTs),
                'day_of_week' => (int)date('N', $resultTs),
                'day_of_week_name' => date('l', $resultTs),
                'day_of_year' => (int)date('z', $resultTs) + 1,
                'week_of_year' => (int)date('oW', $resultTs),
                'iso_8601' => date('c', $resultTs),
                'relative_to' => date('Y-m-d', $refTs),
            ];

            return $result;

        } catch (\Exception $e) {
            return ['success' => false, 'error' => $e->getMessage(), 'expression' => $expression];
        }
    }
}
