<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_number_to_words = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'number_to_words',
    'description' => 'Convert numbers to English words. Supports integers from -999,999,999,999,999 to +999,999,999,999,999, with proper punctuation (and, commas, hyphenated tens). Great for composing with text generators, story tools, and number_sequences. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'number' => 
        array (
          'type' => 'number',
          'description' => 'The number to convert to words (integer, supports up to quadrillions).',
        ),
        'capitalize' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, capitalize the first letter (default: true)',
        ),
      ),
      'required' => 
      array (
        0 => 'number',
      ),
    ),
  ),
);

if (! function_exists('number_to_words')) {
    function number_to_words($number, $capitalize = null)
    {
        $num = (int)$number;
        $cap = $capitalize ?? true;

        if ($num === 0) {
            return json_encode(['number' => 0, 'words' => 'zero', 'capitalized' => 'Zero']);
        }

        $negative = $num < 0;
        $num = abs($num);

        $units = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
                   'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen',
                   'Seventeen', 'Eighteen', 'Nineteen'];
        $tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

        // Make a lowercase copy for non-capitalized mode
        $unitsLower = array_map('strtolower', $units);
        $tensLower = array_map('strtolower', $tens);
        $useUnits = $cap ? $units : $unitsLower;
        $useTens = $cap ? $tens : $tensLower;
        $scaleSuffix = $cap ? ['', 'Thousand', 'Million', 'Billion', 'Trillion', 'Quadrillion']
                           : ['', 'thousand', 'million', 'billion', 'trillion', 'quadrillion'];

        $convertBelow1000 = function($n) use (&$useUnits, &$useTens, $cap) {
            $words = '';
            if ($n >= 100) {
                $words .= $useUnits[(int)($n / 100)] . ($cap ? ' Hundred' : ' hundred');
                $n %= 100;
                if ($n > 0) $words .= ' ';
            }
            if ($n >= 20) {
                $words .= $useTens[(int)($n / 10)];
                $n %= 10;
                if ($n > 0) $words .= '-' . ($cap ? $useUnits[$n] : strtolower($useUnits[$n]));
            } elseif ($n > 0) {
                $words .= $useUnits[$n];
            }
            return $words;
        };

        $parts = [];
        $remaining = $num;
        $scaleIdx = 0;

        while ($remaining > 0) {
            $chunk = $remaining % 1000;
            if ($chunk > 0) {
                $chunkWords = $convertBelow1000($chunk);
                if ($scaleIdx > 0) {
                    $chunkWords .= ' ' . $scaleSuffix[$scaleIdx];
                }
                $parts[] = $chunkWords;
            }
            $remaining = (int)($remaining / 1000);
            $scaleIdx++;
        }

        $parts = array_reverse($parts);

        // Join with commas and 'and'
        $result = '';
        $lastIdx = count($parts) - 1;
        for ($i = 0; $i < count($parts); $i++) {
            if ($i > 0 && $i === $lastIdx) {
                $result .= ' and ';
            } elseif ($i > 0) {
                $result .= ', ';
            }
            $result .= $parts[$i];
        }

        if ($negative) {
            $result = ($cap ? 'Negative ' : 'negative ') . $result;
        }

        return json_encode([
            'number' => (int)$number,
            'words' => $result,
            'capitalized' => $cap ? $result : ucfirst($result),
            'word_count' => str_word_count($result),
            'character_count' => strlen($result),
        ]);
    }
}
