<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_openlibrary_search = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'openlibrary_search',
    'description' => 'Search books via the free Open Library API (no API key required). Returns book titles, authors, ISBNs, cover images, first publish year, subjects, and more. Supports keyword search and detailed lookup by ISBN or Open Library ID. Cover image URLs can be used with image_downloader for fetching book covers. First book/literature data capability in the ecosystem. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'query' => 
        array (
          'type' => 'string',
          'description' => 'Search keyword(s) for the book (e.g. \'The Lord of the Rings\', \'Asimov Foundation\').',
        ),
        'mode' => 
        array (
          'type' => 'string',
          'description' => '\'search\' — search by keyword. \'details\' — get book details by ISBN or Open Library ID (use identifier param). Default: \'search\'.',
        ),
        'identifier' => 
        array (
          'type' => 'string',
          'description' => 'ISBN (e.g. \'9780547928227\') or Open Library ID (e.g. \'OL27448W\') for details mode.',
        ),
        'max_results' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum results to return (1-50, default: 10).',
        ),
        'language' => 
        array (
          'type' => 'string',
          'description' => 'Filter by language code (e.g. \'eng\', \'fre\', \'spa\'). Default: all.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (5-30, default: 15).',
        ),
        'include_cover' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, include cover image URLs. Default: true.',
        ),
      ),
      'required' => 
      array (
        0 => 'query',
      ),
    ),
  ),
);

if (! function_exists('openlibrary_search')) {
    function openlibrary_search($query, $mode = null, $identifier = null, $max_results = null, $language = null, $timeout = null, $include_cover = null)
    {
            $query = $query ?? '';
            $mode = $mode ?? 'search';
            $identifier = $identifier ?? '';
            $max_results = $max_results ?? 10;
            $language = $language ?? '';
            $timeout = $timeout ?? 15;
            $include_cover = $include_cover ?? true;

            $timeout = max(5, min(30, (int)$timeout));
            $max_results = max(1, min(50, (int)$max_results));

            // Helper: fetch JSON
            $fetch_json = function($url, $t) {
                $ctx = stream_context_create([
                    'http' => ['method' => 'GET', 'timeout' => $t, 'header' => "User-Agent: openlibrary_search/1.0\r\n", 'ignore_errors' => true],
                    'ssl' => ['verify_peer' => false, 'verify_peer_name' => false],
                ]);
                $body = @file_get_contents($url, false, $ctx);
                if ($body === false) return ['error' => error_get_last()['message'] ?? 'fetch failed', 'success' => false];
                $status = 200;
                if (isset($http_response_header)) {
                    foreach ($http_response_header as $h) {
                        if (preg_match('#^HTTP/\d+\.\d+ (\d+)#', $h, $m)) { $status = (int)$m[1]; break; }
                    }
                }
                if ($status >= 400) return ['error' => "HTTP $status", 'status' => $status, 'success' => false];
                $data = @json_decode($body, true);
                if ($data === null) return ['error' => 'Invalid JSON', 'success' => false];
                return ['data' => $data, 'status' => $status, 'success' => true];
            };

            // Cover image helper
            $cover_url = function($cover_id, $size = 'M') {
                if (empty($cover_id)) return null;
                return "https://covers.openlibrary.org/b/id/{$cover_id}-{$size}.jpg";
            };

            // MODE: DETAILS by ISBN or OLID
            if ($mode === 'details') {
                $id = trim($identifier);
                if (empty($id)) {
                    return ['success' => false, 'error' => 'identifier (ISBN or OLID) is required for details mode.'];
                }

                // Determine if ISBN or OLID
                $is_isbn = preg_match('/^\d{9}[\dXx]$|^\d{13}$/', $id);
                $api_url = '';
                if ($is_isbn) {
                    $api_url = "https://openlibrary.org/isbn/{$id}.json";
                } else {
                    $api_url = "https://openlibrary.org{$id}.json";
                }

                $result = $fetch_json($api_url, $timeout);
                if (!$result['success']) {
                    return ['success' => false, 'error' => "Book not found: {$result['error']}"];
                }

                $data = $result['data'];
                $works_url = $data['works'][0]['key'] ?? ($data['works'] ?? '');
                if (!empty($works_url) && is_string($works_url)) {
                    $works_url = $works_url;
                } elseif (!empty($data['works']) && is_array($data['works'])) {
                    $works_url = $data['works'][0]['key'] ?? '';
                } else {
                    $works_url = '';
                }

                // Fetch work details for description, subjects
                $description = '';
                $subjects = [];
                if (!empty($works_url)) {
                    $work_result = $fetch_json("https://openlibrary.org{$works_url}.json", $timeout);
                    if ($work_result['success']) {
                        $work = $work_result['data'];
                        $desc = $work['description'] ?? '';
                        if (is_array($desc)) $desc = $desc['value'] ?? '';
                        $description = is_string($desc) ? mb_substr($desc, 0, 2000) : '';
                        $subjects = $work['subjects'] ?? [];
                        $subject_people = $work['subject_people'] ?? [];
                        $subject_places = $work['subject_places'] ?? [];
                        $subject_times = $work['subject_times'] ?? [];
                    }
                }

                // Get all identifiers
                $identifiers = $data['identifiers'] ?? [];
                $isbn_10 = $identifiers['isbn_10'][0] ?? '';
                $isbn_13 = $identifiers['isbn_13'][0] ?? '';
                $lccn = $identifiers['lccn'][0] ?? '';
                $oclc = $identifiers['oclc'][0] ?? '';

                $covers = $data['covers'] ?? [];
                $cover_id_val = $covers[0] ?? null;

                return [
                    'success' => true,
                    'mode' => 'details',
                    'identifier' => $id,
                    'title' => $data['title'] ?? '',
                    'subtitle' => $data['subtitle'] ?? '',
                    'authors' => $data['authors'] ?? [],
                    'publishers' => $data['publishers'] ?? [],
                    'publish_date' => $data['publish_date'] ?? '',
                    'number_of_pages' => $data['number_of_pages'] ?? null,
                    'isbn_10' => $isbn_10,
                    'isbn_13' => $isbn_13,
                    'lccn' => $lccn,
                    'oclc' => $oclc,
                    'subjects' => $subjects,
                    'description' => $description,
                    'cover_url' => ($include_cover && $cover_id_val) ? $cover_url($cover_id_val, 'L') : null,
                    'cover_small' => ($include_cover && $cover_id_val) ? $cover_url($cover_id_val, 'S') : null,
                    'openlibrary_url' => "https://openlibrary.org{$data['key']}",
                ];
            }

            // MODE: SEARCH
            $q = trim($query);
            if (empty($q)) {
                return ['success' => false, 'error' => 'Search query is required.'];
            }

            $search_url = 'https://openlibrary.org/search.json?q=' . urlencode($q) . '&limit=' . $max_results;
            if (!empty($language)) {
                $search_url .= '&lang=' . urlencode($language);
            }

            $result = $fetch_json($search_url, $timeout);
            if (!$result['success']) {
                return ['success' => false, 'error' => 'Search failed: ' . $result['error']];
            }

            $data = $result['data'];
            $num_found = $data['numFound'] ?? 0;
            $docs = $data['docs'] ?? [];

            $books = [];
            foreach ($docs as $doc) {
                $cover_i = $doc['cover_i'] ?? $doc['cover_id'] ?? null;
                $isbn = $doc['isbn'] ?? [];
                $author_keys = [];

                // Build author info
                $authors = $doc['author_name'] ?? $doc['author'] ?? [];
                if (is_string($authors)) $authors = [$authors];

                // Subjects
                $subjects = $doc['subject'] ?? [];
                if (is_string($subjects)) $subjects = [$subjects];
                $subjects = array_slice($subjects, 0, 10);

                // ISBNs
                $isbn_list = $isbn;
                $isbn_10_val = '';
                $isbn_13_val = '';
                foreach ((array)$isbn as $isbn_val) {
                    $isbn_val = preg_replace('/[^0-9Xx]/', '', $isbn_val);
                    if (strlen($isbn_val) === 10) $isbn_10_val = $isbn_val;
                    if (strlen($isbn_val) === 13) $isbn_13_val = $isbn_val;
                }

                // Edition count
                $edition_count = $doc['edition_count'] ?? 0;

                // First publish year
                $first_year = $doc['first_publish_year'] ?? null;

                $book = [
                    'title' => $doc['title'] ?? '',
                    'subtitle' => $doc['subtitle'] ?? '',
                    'authors' => $authors,
                    'author_count' => count($authors),
                    'first_publish_year' => $first_year,
                    'isbn_10' => $isbn_10_val,
                    'isbn_13' => $isbn_13_val,
                    'edition_count' => $edition_count,
                    'number_of_pages' => $doc['number_of_pages_median'] ?? null,
                    'publisher' => isset($doc['publisher'][0]) ? $doc['publisher'][0] : '',
                    'publish_date' => isset($doc['publish_date'][0]) ? $doc['publish_date'][0] : '',
                    'subjects' => $subjects,
                    'subject_count' => count($subjects),
                    'language' => isset($doc['language'][0]) ? $doc['language'][0] : '',
                    'openlibrary_key' => $doc['key'] ?? '',
                    'openlibrary_edition_key' => $doc['edition_key'][0] ?? '',
                    'cover_url' => ($include_cover && $cover_i) ? $cover_url($cover_i, 'M') : null,
                    'cover_small' => ($include_cover && $cover_i) ? $cover_url($cover_i, 'S') : null,
                    'cover_large' => ($include_cover && $cover_i) ? $cover_url($cover_i, 'L') : null,
                    'ratings' => [
                        'average' => $doc['ratings_average'] ?? null,
                        'count' => $doc['ratings_count'] ?? 0,
                    ],
                    'first_sentence' => $doc['first_sentence'] ?? '',
                ];
                $books[] = $book;
            }

            return [
                'success' => true,
                'mode' => 'search',
                'query' => $q,
                'total_results' => $num_found,
                'results_returned' => count($books),
                'query_time_estimate' => $data['query_time'] ?? null,
                'books' => $books,
            ];
    }
}
