<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_package_audit = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'package_audit',
    'description' => 'Fetch metadata about a Composer/Packagist package: latest version, description, downloads, license, dependencies, and security advisories. Uses two APIs: Packagist (package metadata) and the FriendsOfPHP security advisories database (vulnerability lookup). First tool in the ecosystem to reach into the PHP package ecosystem. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'package_name' => 
        array (
          'type' => 'string',
          'description' => 'Full Packagist package name (e.g. \'laravel/framework\', \'monolog/monolog\').',
        ),
        'check_advisories' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, check for known security advisories (default: true).',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (5-30, default: 15).',
        ),
      ),
      'required' => 
      array (
        0 => 'package_name',
      ),
    ),
  ),
);

if (! function_exists('package_audit')) {
    function package_audit($package_name, $check_advisories = null, $timeout = null)
    {
        // Package Audit — query Packagist API for PHP package metadata
        $package_name = $package_name ?? '';
        $check_advisories = $check_advisories ?? true;
        $timeout = $timeout ?? 15;

        if (empty($package_name)) return ['error' => 'package_name is required (e.g. "laravel/framework")', 'success' => false];
        if (!preg_match('#^[a-z0-9_.-]+/[a-z0-9_.-]+$#i', $package_name)) {
            return ['error' => "Invalid package name format. Use 'vendor/package' format.", 'success' => false];
        }
        $timeout = max(5, min(30, (int)$timeout));

        // Helper: fetch JSON
        function pa_fetch($url, $timeout) {
            $ctx = stream_context_create([
                'http' => ['method' => 'GET', 'timeout' => $timeout, 'header' => "User-Agent: package_audit/1.0\r\nAccept: application/json\r\n", 'ignore_errors' => true],
                'ssl' => ['verify_peer' => false, 'verify_peer_name' => false],
            ]);
            $body = @file_get_contents($url, false, $ctx);
            if ($body === false) return ['error' => error_get_last()['message'] ?? 'fetch failed', 'success' => false];
            $status = 200;
            if (isset($http_response_header)) {
                foreach ($http_response_header as $h) {
                    if (preg_match('#^HTTP/\d+\.\d+ (\d+)#', $h, $m)) { $status = (int)$m[1]; break; }
                }
            }
            $data = @json_decode($body, true);
            if ($data === null) return ['error' => 'Invalid JSON', 'status' => $status, 'success' => false];
            return ['data' => $data, 'status' => $status, 'success' => true];
        }

        // 1. Fetch package metadata from Packagist
        $pkg_url = 'https://packagist.org/packages/' . $package_name . '.json';
        $pkg = pa_fetch($pkg_url, $timeout);

        if (!$pkg['success']) {
            return ['error' => 'Packagist API error: ' . ($pkg['error'] ?? 'unknown'), 'success' => false];
        }
        if ($pkg['status'] === 404) {
            return ['error' => "Package '$package_name' not found on Packagist.", 'success' => false];
        }
        if ($pkg['status'] >= 400) {
            return ['error' => "Packagist API returned HTTP {$pkg['status']}", 'success' => false];
        }

        $package = $pkg['data']['package'] ?? [];
        if (empty($package)) {
            return ['error' => 'Empty package data from Packagist', 'success' => false];
        }

        // Extract metadata
        $metadata = $package;
        $latest_version = '';
        $stable_version = '';
        $versions = $metadata['versions'] ?? [];

        // Filter versions to find stable and latest
        $version_list = array_keys($versions);
        $stable_versions = [];
        $dev_versions = [];
        foreach ($version_list as $v) {
            if (strpos($v, 'dev-') === 0 || preg_match('/-(alpha|beta|RC|dev|patch)/i', $v)) {
                $dev_versions[] = $v;
            } else {
                $stable_versions[] = $v;
            }
        }

        // Sort using version_compare (descending)
        usort($stable_versions, function($a, $b) {
            return version_compare($b, $a);
        });
        usort($dev_versions, function($a, $b) {
            return version_compare($b, $a);
        });

        $latest_stable = $stable_versions[0] ?? null;
        $latest_dev = $dev_versions[0] ?? null;
        $all_versions_sorted = array_merge($stable_versions, $dev_versions);
        $latest_version = $all_versions_sorted[0] ?? 'unknown';

        // Get details of the latest stable version
        $latest_detail = $latest_stable && isset($versions[$latest_stable]) ? $versions[$latest_stable] : null;
        if (!$latest_detail && $latest_dev && isset($versions[$latest_dev])) {
            $latest_detail = $versions[$latest_dev];
        }

        // Get description, license, etc.
        $description = $metadata['description'] ?? '';
        $type = $metadata['type'] ?? '';
        $repository = $metadata['repository'] ?? '';
        $github_stars = 0;
        $github_forks = 0;

        // Try to get GitHub stats
        if (preg_match('#github\.com[:/]([^/]+/[^/.]+)#', $repository, $m)) {
            $repo_path = $m[1];
            $gh = pa_fetch("https://api.github.com/repos/$repo_path", $timeout);
            if ($gh['success']) {
                $github_stars = $gh['data']['stargazers_count'] ?? 0;
                $github_forks = $gh['data']['forks_count'] ?? 0;
            }
        }

        // Downloads from packagist stats
        $downloads = $metadata['downloads'] ?? 0;
        $favers = $metadata['favers'] ?? 0;

        // Dependencies
        $require = $latest_detail['require'] ?? [];
        $require_dev = $latest_detail['require-dev'] ?? [];
        $suggest = $latest_detail['suggest'] ?? [];
        $php_version = $require['php'] ?? 'any';
        unset($require['php']); // Remove PHP from package deps

        // License
        $license = $latest_detail['license'] ?? $metadata['license'] ?? [];
        if (is_string($license)) $license = [$license];

        // Authors
        $authors = $metadata['authors'] ?? [];
        $author_names = [];
        foreach ($authors as $a) {
            $author_names[] = $a['name'] ?? 'Unknown';
        }

        // 2. Security advisories
        $advisories = [];
        if ($check_advisories) {
            $adv_url = 'https://api.github.com/repos/FriendsOfPHP/security-advisories/contents/' . $package_name;
            $adv = pa_fetch($adv_url, $timeout);
            if ($adv['success']) {
                // Directory exists - there are advisories for this package
                foreach ($adv['data'] as $file) {
                    if (preg_match('/\.yaml$/', $file['name'] ?? '')) {
                        $advisories[] = [
                            'file' => $file['name'],
                            'url' => $file['html_url'] ?? $file['download_url'] ?? '',
                        ];
                    }
                }
            }

            // Also check packagist.org's advisory endpoint
            $adv2 = pa_fetch("https://packagist.org/api/security-advisories/?packages[]=" . urlencode($package_name), $timeout);
            if ($adv2['success'] && isset($adv2['data']['advisories'][$package_name])) {
                $advisories = array_merge($advisories, $adv2['data']['advisories'][$package_name]);
            }
        }

        // Build version history summary
        $version_summary = [];
        foreach ($stable_versions as $v) {
            if (count($version_summary) >= 10) break;
            $detail = $versions[$v] ?? [];
            $version_summary[$v] = [
                'time' => $detail['time'] ?? '',
                'license' => is_array($detail['license'] ?? null) ? implode(', ', $detail['license']) : ($detail['license'] ?? ''),
                'php_required' => $detail['require']['php'] ?? 'any',
            ];
        }

        return [
            'success' => true,
            'package' => $package_name,
            'description' => $description,
            'type' => $type ?: 'library',
            'latest_stable' => $latest_stable ?: 'none',
            'latest_version_any' => $latest_version,
            'php_required' => $php_version,
            'license' => $license,
            'authors' => $author_names,
            'repository' => $repository,
            'github_stars' => $github_stars,
            'github_forks' => $github_forks,
            'downloads_packagist' => $downloads,
            'favorites' => $favers,
            'dependencies' => [
                'required' => $require,
                'required_dev' => $require_dev,
                'suggested' => $suggest,
            ],
            'total_versions' => count($versions),
            'stable_versions' => count($stable_versions),
            'dev_versions' => count($dev_versions),
            'recent_versions' => $version_summary,
            'security_advisories' => $advisories,
            'advisory_count' => is_array($advisories) ? count($advisories) : 0,
            'data_sources' => [
                'packagist' => $pkg_url,
                'github' => $repository ?: null,
            ],
        ];
    }
}
