<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_php_reflector = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'php_reflector',
    'description' => 'Analyze PHP code using the Reflection API. Safely includes a PHP file and uses ReflectionFunction/ReflectionClass to extract detailed metadata: parameter names, types, default values, return types, docblock descriptions, number of parameters, and whether it\'s a closure or built-in. Falls back to tokenizer analysis if the file can\'t be included. Uses PHP\'s Reflection extension — never before used in this ecosystem. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'source' => 
        array (
          'type' => 'string',
          'description' => 'PHP source code as a string to analyze. The code will be safely evaluated in a sandboxed scope.',
        ),
        'function_name' => 
        array (
          'type' => 'string',
          'description' => 'Optional: specific function name to reflect on (e.g. \'http_fetch\'). If not provided, all functions defined in the source are analyzed.',
        ),
        'mode' => 
        array (
          'type' => 'string',
          'description' => '\'auto\' - try Reflection first, fall back to tokenizer. \'tokenizer\' - use tokenizer only. \'reflect\' - use Reflection only (default: \'auto\').',
        ),
      ),
      'required' => 
      array (
        0 => 'source',
      ),
    ),
  ),
);

if (! function_exists('php_reflector')) {
    function php_reflector($source, $function_name = null, $mode = null)
    {
        if (!is_string($source) || $source === '') {
            return ['error' => 'Source code is required.', 'functions' => []];
        }

        $mode = isset($mode) ? trim($mode) : 'auto';
        if (!in_array($mode, ['auto', 'tokenizer', 'reflect'], true)) {
            $mode = 'auto';
        }

        $functions_analyzed = [];
        $classes_analyzed = [];
        $errors = [];

        // Step 1: Extract function and class names from source using tokenizer
        $tokens = @token_get_all($source);
        $defined_names = []; // function names defined
        $defined_classes = []; // class names defined
        $namespace = '';

        if ($tokens === false) {
            return ['error' => 'Failed to tokenize source code.', 'functions' => []];
        }

        $count = count($tokens);
        for ($i = 0; $i < $count; $i++) {
            if (!is_array($tokens[$i])) continue;
            
            if ($tokens[$i][0] === T_NAMESPACE) {
                $parts = [];
                for ($j = $i + 1; $j < $count; $j++) {
                    if (!is_array($tokens[$j])) break;
                    if ($tokens[$j][0] === T_WHITESPACE) continue;
                    if ($tokens[$j][0] === T_STRING || $tokens[$j][0] === T_NS_SEPARATOR) {
                        $parts[] = $tokens[$j][1];
                    } else break;
                }
                $namespace = implode('', $parts);
            }
            
            if ($tokens[$i][0] === T_FUNCTION) {
                $j = $i + 1;
                while ($j < $count && is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) $j++;
                if ($j < $count && is_string($tokens[$j]) && $tokens[$j] === '&') { $j++; }
                while ($j < $count && is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) $j++;
                if ($j < $count && is_array($tokens[$j]) && $tokens[$j][0] === T_STRING) {
                    $fname = $tokens[$j][1];
                    $fqcn = ($namespace ? $namespace . '\\' : '') . $fname;
                    $defined_names[] = $fqcn;
                }
            }
            
            if (in_array($tokens[$i][0], [T_CLASS, T_INTERFACE, T_TRAIT, T_ENUM], true)) {
                $j = $i + 1;
                while ($j < $count && is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) $j++;
                if ($j < $count && is_array($tokens[$j]) && $tokens[$j][0] === T_STRING) {
                    $cname = $tokens[$j][1];
                    $fqcn = ($namespace ? $namespace . '\\' : '') . $cname;
                    $type_map = [T_CLASS => 'class', T_INTERFACE => 'interface', T_TRAIT => 'trait', T_ENUM => 'enum'];
                    $defined_classes[] = ['name' => $fqcn, 'type' => $type_map[$tokens[$i][0]] ?? 'unknown'];
                }
            }
        }

        // Step 2: If we need Reflection, try to evaluate the source in a sandbox
        $use_reflect = ($mode === 'reflect' || ($mode === 'auto' && !empty($defined_names)));

        if ($use_reflect) {
            // Try to evaluate the source. Wrap in a sandbox function to avoid polluting global scope
            $sandbox_func = function() use ($source, $defined_names, $defined_classes, &$functions_analyzed, &$classes_analyzed, &$errors) {
                // Temporarily store existing functions to detect new ones
                $before_funcs = get_defined_functions()['user'] ?? [];
                $before_classes = get_declared_classes();
                
                try {
                    // Evaluate in a limited scope
                    eval('?>' . $source);
                } catch (\Throwable $e) {
                    $errors[] = 'Eval error: ' . $e->getMessage();
                    return;
                }
                
                $after_funcs = get_defined_functions()['user'] ?? [];
                $new_funcs = array_diff($after_funcs, $before_funcs);
                
                $after_classes = get_declared_classes();
                $new_classes = array_diff($after_classes, $before_classes);
                
                // Analyze each new function with Reflection
                foreach ($new_funcs as $fname) {
                    try {
                        $ref = new ReflectionFunction($fname);
                        
                        $params = [];
                        foreach ($ref->getParameters() as $param) {
                            $p_info = [
                                'name' => $param->getName(),
                                'position' => $param->getPosition(),
                                'has_default' => $param->isDefaultValueAvailable(),
                                'default' => $param->isDefaultValueAvailable() ? 
                                    (is_bool($param->getDefaultValue()) ? ($param->getDefaultValue() ? 'true' : 'false') : 
                                    ($param->getDefaultValue() === null ? 'null' : (string)$param->getDefaultValue())) : null,
                                'allows_null' => $param->allowsNull(),
                                'is_optional' => $param->isOptional(),
                                'is_variadic' => $param->isVariadic(),
                                'has_type' => $param->hasType(),
                                'type' => $param->hasType() ? $param->getType()->getName() : null,
                            ];
                            
                            // Check for built-in type
                            if ($param->hasType()) {
                                $t = $param->getType();
                                if ($t instanceof ReflectionNamedType) {
                                    $p_info['type_class'] = $t->getName();
                                    $p_info['allows_null'] = $t->allowsNull();
                                }
                            }
                            
                            $params[] = $p_info;
                        }
                        
                        $return_type = null;
                        if ($ref->hasReturnType()) {
                            $rt = $ref->getReturnType();
                            if ($rt instanceof ReflectionNamedType) {
                                $return_type = $rt->getName();
                            } else {
                                $return_type = (string)$rt;
                            }
                        }
                        
                        $docblock = $ref->getDocComment();
                        $docblock = $docblock !== false ? $docblock : null;
                        
                        // Get source code info
                        $start_line = $ref->getStartLine();
                        $end_line = $ref->getEndLine();
                        $length = $end_line - $start_line;
                        
                        $is_closure = $ref->isClosure();
                        $is_internal = $ref->isInternal();
                        
                        $functions_analyzed[] = [
                            'name' => $fname,
                            'line' => $start_line,
                            'length_lines' => $length,
                            'number_of_parameters' => count($params),
                            'parameters' => $params,
                            'return_type' => $return_type,
                            'has_docblock' => $docblock !== null,
                            'docblock' => $docblock !== null ? substr($docblock, 0, 500) : null,
                            'is_closure' => $is_closure,
                            'is_internal' => $is_internal,
                            'source' => 'reflection',
                        ];
                    } catch (\Throwable $e) {
                        $errors[] = "Failed to reflect $fname: " . $e->getMessage();
                    }
                }
                
                // Analyze classes
                foreach ($new_classes as $cname) {
                    try {
                        $ref = new ReflectionClass($cname);
                        $methods = [];
                        foreach ($ref->getMethods() as $method) {
                            $m_params = [];
                            foreach ($method->getParameters() as $param) {
                                $m_params[] = [
                                    'name' => $param->getName(),
                                    'has_default' => $param->isDefaultValueAvailable(),
                                    'has_type' => $param->hasType(),
                                    'type' => $param->hasType() ? ($param->getType() instanceof ReflectionNamedType ? $param->getType()->getName() : (string)$param->getType()) : null,
                                ];
                            }
                            $methods[] = [
                                'name' => $method->getName(),
                                'is_public' => $method->isPublic(),
                                'is_static' => $method->isStatic(),
                                'parameters' => $m_params,
                                'return_type' => $method->hasReturnType() ? ($method->getReturnType() instanceof ReflectionNamedType ? $method->getReturnType()->getName() : (string)$method->getReturnType()) : null,
                            ];
                        }
                        
                        $properties = [];
                        foreach ($ref->getProperties() as $prop) {
                            $properties[] = [
                                'name' => $prop->getName(),
                                'is_public' => $prop->isPublic(),
                                'is_static' => $prop->isStatic(),
                                'has_type' => $prop->hasType(),
                                'type' => $prop->hasType() ? ($prop->getType() instanceof ReflectionNamedType ? $prop->getType()->getName() : (string)$prop->getType()) : null,
                            ];
                        }
                        
                        $classes_analyzed[] = [
                            'name' => $cname,
                            'is_abstract' => $ref->isAbstract(),
                            'is_final' => $ref->isFinal(),
                            'is_readonly' => method_exists($ref, 'isReadOnly') ? $ref->isReadOnly() : false,
                            'parent_class' => $ref->getParentClass() ? $ref->getParentClass()->getName() : null,
                            'interfaces' => $ref->getInterfaceNames(),
                            'methods' => $methods,
                            'properties' => $properties,
                        ];
                    } catch (\Throwable $e) {
                        $errors[] = "Failed to reflect class $cname: " . $e->getMessage();
                    }
                }
            };
            
            $sandbox_func();
        }

        // Step 3: For functions not covered by Reflection (or if mode is tokenizer), use tokenizer data
        if ($mode === 'tokenizer' || ($mode === 'auto' && empty($functions_analyzed))) {
            foreach ($defined_names as $fname) {
                // Extract parameter info from token stream (simplified)
                $params = [];
                for ($i = 0; $i < $count; $i++) {
                    if (!is_array($tokens[$i])) continue;
                    if ($tokens[$i][0] === T_FUNCTION) {
                        $j = $i + 1;
                        while ($j < $count && is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) $j++;
                        if ($j < $count && is_string($tokens[$j]) && $tokens[$j] === '&') { $j++; }
                        while ($j < $count && is_array($tokens[$j]) && $tokens[$j][0] === T_WHITESPACE) $j++;
                        if ($j < $count && is_array($tokens[$j]) && $tokens[$j][0] === T_STRING && $tokens[$j][1] === substr($fname, strrpos($fname, '\\') !== false ? strrpos($fname, '\\') + 1 : 0)) {
                            // Extract parameters
                            $depth = 0;
                            $capture = false;
                            $param_start = false;
                            for ($k = $j + 1; $k < $count; $k++) {
                                $tk = $tokens[$k];
                                if (is_string($tk)) {
                                    if ($tk === '(' && !$capture) { $capture = true; $depth = 1; continue; }
                                    if ($tk === '(' && $capture) { $depth++; continue; }
                                    if ($tk === ')') { $depth--; if ($depth <= 0) break; }
                                }
                            }
                            
                            $functions_analyzed[] = [
                                'name' => $fname,
                                'source' => 'tokenizer',
                                'line' => $tokens[$i][2] ?? 0,
                                'parameters' => 'see php_source_analyzer for details',
                            ];
                            break;
                        }
                    }
                }
            }
        }

        return [
            'error' => !empty($errors) ? implode('; ', $errors) : null,
            'errors' => !empty($errors) ? $errors : null,
            'functions' => $functions_analyzed,
            'classes' => $classes_analyzed,
            'function_count' => count($functions_analyzed),
            'class_count' => count($classes_analyzed),
            'technique' => $use_reflect ? 'reflection_api' : 'tokenizer',
            'mode_used' => $mode,
            'extensions_used' => $use_reflect ? ['Reflection', 'tokenizer'] : ['tokenizer'],
        ];
    }
}
