<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_process_scanner = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'process_scanner',
    'description' => 'Enumerate running processes on Windows using FFI (CreateToolhelp32Snapshot + Process32FirstW/Process32NextW). Returns PID, parent PID, process name, thread count, and handle count for every running process. Can filter by name, PID range, or thread count threshold. No native PHP function provides process enumeration — FFI is required. First process/task management capability in the ecosystem. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'filter_name' => 
        array (
          'type' => 'string',
          'description' => 'Optional case-insensitive filter by process name (e.g. \'svchost\', \'php\', \'chrome\').',
        ),
        'min_pid' => 
        array (
          'type' => 'integer',
          'description' => 'Minimum PID to include (default: 0).',
        ),
        'max_pid' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum PID to include (default: 999999).',
        ),
        'min_threads' => 
        array (
          'type' => 'integer',
          'description' => 'Minimum thread count filter (default: 0).',
        ),
        'sort_by' => 
        array (
          'type' => 'string',
          'description' => 'Sort order: \'pid\', \'name\', \'threads\', \'ppid\' (default: \'pid\').',
        ),
        'limit' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum processes to return (0=all, default: 100).',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (1-10, default: 5).',
        ),
      ),
      'required' => 
      array (
      ),
    ),
  ),
);

if (! function_exists('process_scanner')) {
    function process_scanner($filter_name = null, $min_pid = null, $max_pid = null, $min_threads = null, $sort_by = null, $limit = null, $timeout = null)
    {
        // Process Scanner - enumerate running processes via FFI (Windows Tool Help API)
        // Uses CreateToolhelp32Snapshot + Process32FirstW/Process32NextW

        $timeout = isset($timeout) ? min(max((int)$timeout, 1), 10) : 5;
        $filter_name = isset($filter_name) ? (string)$filter_name : '';
        $min_pid = isset($min_pid) ? max(0, (int)$min_pid) : 0;
        $max_pid = isset($max_pid) ? max(0, (int)$max_pid) : 999999;
        $min_threads = isset($min_threads) ? max(0, (int)$min_threads) : 0;
        $sort_by = isset($sort_by) ? (string)$sort_by : 'pid';
        $limit = isset($limit) ? max(0, (int)$limit) : 100;

        $result = [
            'success' => true,
            'os_family' => PHP_OS_FAMILY,
            'ffi_available' => extension_loaded('ffi'),
        ];

        if (!$result['ffi_available']) {
            return array_merge($result, ['error' => 'FFI extension not loaded']);
        }

        if (PHP_OS_FAMILY !== 'Windows') {
            return array_merge($result, [
                'note' => 'Process enumeration via FFI requires Windows',
                'message' => 'On Unix, use proc_open or exec("ps aux")'
            ]);
        }

        try {
            $ffi = FFI::cdef("
                typedef struct {
                    unsigned long dwSize;
                    unsigned long cntUsage;
                    unsigned long th32ProcessID;
                    unsigned long long th32DefaultHeapID;
                    unsigned long th32ModuleID;
                    unsigned long cntThreads;
                    unsigned long th32ParentProcessID;
                    long th32PriClassBase;
                    unsigned long dwFlags;
                    unsigned short szExeFile[260];
                } PROCESSENTRY32W;
                
                void* CreateToolhelp32Snapshot(unsigned long dwFlags, unsigned long th32ProcessID);
                int Process32FirstW(void* hSnapshot, PROCESSENTRY32W* lppe);
                int Process32NextW(void* hSnapshot, PROCESSENTRY32W* lppe);
                int CloseHandle(void* hObject);
            ", "kernel32.dll");
            
            $TH32CS_SNAPPROCESS = 0x00000002;
            $snapshot = $ffi->CreateToolhelp32Snapshot($TH32CS_SNAPPROCESS, 0);
            
            if ($snapshot === null) {
                return array_merge($result, ['error' => 'Failed to create process snapshot']);
            }
            
            $pe = $ffi->new("PROCESSENTRY32W");
            $pe->dwSize = FFI::sizeof($pe);
            
            $processes = [];
            
            if ($ffi->Process32FirstW($snapshot, FFI::addr($pe))) {
                do {
                    // Read process name from WCHAR array
                    $name = '';
                    for ($i = 0; $i < 260; $i++) {
                        $wc = (int)$pe->szExeFile[$i];
                        if ($wc === 0) break;
                        if ($wc >= 32 && $wc < 256) {
                            $name .= chr($wc);
                        }
                    }
                    
                    $pid = (int)$pe->th32ProcessID;
                    $ppid = (int)$pe->th32ParentProcessID;
                    $threads = (int)$pe->cntThreads;
                    
                    // Apply filters
                    if ($pid < $min_pid || $pid > $max_pid) continue;
                    if ($threads < $min_threads) continue;
                    if ($filter_name !== '' && !str_contains(strtolower($name), strtolower($filter_name))) continue;
                    
                    $processes[] = [
                        'pid' => $pid,
                        'ppid' => $ppid,
                        'name' => $name,
                        'threads' => $threads,
                    ];
                    
                } while ($ffi->Process32NextW($snapshot, FFI::addr($pe)));
            }
            
            $ffi->CloseHandle($snapshot);
            
            // Sort
            usort($processes, function($a, $b) use ($sort_by) {
                switch ($sort_by) {
                    case 'name': return strcmp($a['name'], $b['name']);
                    case 'threads': return $b['threads'] - $a['threads'];
                    case 'ppid': return $a['ppid'] - $b['ppid'];
                    default: return $a['pid'] - $b['pid'];
                }
            });
            
            // Limit
            if ($limit > 0 && count($processes) > $limit) {
                $total = count($processes);
                $processes = array_slice($processes, 0, $limit);
                $truncated = true;
            } else {
                $total = count($processes);
                $truncated = false;
            }
            
            // Summary stats
            $stats = [
                'total_processes' => $total,
                'total_threads' => array_sum(array_column($processes, 'threads')),
                'unique_names' => count(array_unique(array_column($processes, 'name'))),
                'filtered' => $truncated,
            ];
            
            return [
                'success' => true,
                'process_count' => count($processes),
                'total_found' => $total,
                'truncated' => $truncated,
                'stats' => $stats,
                'processes' => $processes,
            ];
            
        } catch (\Throwable $e) {
            if (isset($snapshot) && $snapshot !== null) {
                try { $ffi->CloseHandle($snapshot); } catch (\Throwable $ignored) {}
            }
            return array_merge($result, [
                'error' => 'Process enumeration failed: ' . $e->getMessage(),
            ]);
        }
    }
}
