<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_project_analyzer = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'project_analyzer',
    'description' => 'Analyze a PHP project directory and produce a comprehensive structural report. Scans the entire tree: discovers all PHP files, parses classes/functions/namespaces via tokenizer, reads composer.json (packages, PHP version, scripts), counts dependencies (use statements, require/include), maps file types and sizes, and identifies project type (Laravel/Symfony/plain PHP). First project/codebase analysis capability in the ecosystem — enables agents to understand any PHP project structure. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'path' => 
        array (
          'type' => 'string',
          'description' => 'Project directory path relative to project root (default: \'.\').',
        ),
        'max_files' => 
        array (
          'type' => 'integer',
          'description' => 'Max PHP files to analyze (50-5000, default: 200).',
        ),
        'include_vendor' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, include vendor/ in analysis (default: false).',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (10-60, default: 30).',
        ),
      ),
      'required' => 
      array (
      ),
    ),
  ),
);

if (! function_exists('project_analyzer')) {
    function project_analyzer($path = null, $max_files = null, $include_vendor = null, $timeout = null)
    {
        $path = isset($path) ? (string)$path : '.';
        $max_files = isset($max_files) ? max(50, min(5000, (int)$max_files)) : 200;
        $include_vendor = $include_vendor ?? false;
        $timeout = isset($timeout) ? max(10, min(60, (int)$timeout)) : 30;

        $project_root = realpath(__DIR__ . '/../../..');
        if (!$project_root) return ['error' => 'Could not determine project root.', 'success' => false];
        $target = realpath($project_root . '/' . ltrim($path, '/\\'));
        if (!$target || !is_dir($target)) return ['error' => "Directory not found: $path", 'success' => false];

        $start = microtime(true);
        $deadline = time() + $timeout;

        $result = [
            'project_path' => $path, 'project_name' => basename($target),
            'file_stats' => ['total_files' => 0, 'php_files' => 0, 'other_files' => 0, 'total_size_bytes' => 0],
            'php_stats' => ['classes' => 0, 'functions' => 0, 'namespaces' => 0, 'interfaces' => 0, 'traits' => 0, 'total_lines' => 0],
            'dependency_stats' => ['use_statements' => 0, 'require_calls' => 0, 'include_calls' => 0],
            'top_used_classes' => [], 'file_type_breakdown' => [], 'composer' => null, 'largest_files' => [], 'error_files' => [], 'directories' => [],
        ];

        // Check composer.json
        $composer_path = $target . '/composer.json';
        if (file_exists($composer_path)) {
            $cr = @file_get_contents($composer_path);
            if ($cr) {
                $c = @json_decode($cr, true);
                if ($c) {
                    $result['composer'] = [
                        'name' => $c['name'] ?? '(unnamed)', 'type' => $c['type'] ?? 'project',
                        'description' => $c['description'] ?? '',
                        'php_version' => $c['require']['php'] ?? ($c['require-dev']['php'] ?? '(not specified)'),
                        'laravel_version' => $c['require']['laravel/framework'] ?? $c['require']['laravel/laravel'] ?? null,
                        'dependencies' => array_keys($c['require'] ?? []),
                        'dev_dependencies' => array_keys($c['require-dev'] ?? []),
                        'scripts' => array_keys($c['scripts'] ?? []),
                        'total_packages' => count($c['require'] ?? []) + count($c['require-dev'] ?? []),
                    ];
                }
            }
        }

        // Use closure to avoid function ordering issues
        $analyzeFile = function($real_path, $rel_path, &$result, &$use_counts, &$largest_files) {
            $content = @file_get_contents($real_path);
            if ($content === false || empty($content)) {
                $result['error_files'][] = ['path' => $rel_path, 'error' => 'Cannot read'];
                return;
            }
            $size = strlen($content);
            $largest_files[] = ['path' => $rel_path, 'size' => $size, 'type' => 'php'];
            $lines = substr_count($content, "\n") + 1;
            $result['php_stats']['total_lines'] += $lines;
            $tokens = @token_get_all($content);
            if ($tokens === false) { $result['error_files'][] = ['path' => $rel_path, 'error' => 'Tokenization']; return; }
            for ($i = 0; $i < count($tokens); $i++) {
                if (!is_array($tokens[$i])) continue;
                $tt = $tokens[$i][0]; $txt = $tokens[$i][1];
                if ($tt === T_CLASS) { $result['php_stats']['classes']++; }
                elseif ($tt === T_FUNCTION) {
                    $prev = $i - 1;
                    while ($prev > 0 && is_array($tokens[$prev]) && $tokens[$prev][0] === T_WHITESPACE) $prev--;
                    if ($prev > 0 && is_array($tokens[$prev]) && in_array($tokens[$prev][0], [T_PUBLIC, T_PRIVATE, T_PROTECTED, T_STATIC, T_ABSTRACT, T_FINAL, T_FUNCTION])) {
                        // method, skip
                    } else {
                        $result['php_stats']['functions']++;
                    }
                }
                elseif ($tt === T_NAMESPACE) $result['php_stats']['namespaces']++;
                elseif ($tt === T_INTERFACE) $result['php_stats']['interfaces']++;
                elseif ($tt === T_TRAIT) $result['php_stats']['traits']++;
                elseif ($tt === T_USE) {
                    $result['dependency_stats']['use_statements']++;
                    // Extract top-level namespace
                    $j = $i + 1; $us = '';
                    while ($j < count($tokens)) {
                        if (is_array($tokens[$j])) $us .= $tokens[$j][1];
                        else { if ($tokens[$j] === ';' || $tokens[$j] === '{') break; $us .= $tokens[$j]; }
                        $j++;
                    }
                    $us = trim(preg_replace('/\s+/', ' ', $us));
                    $parts = explode(' ', $us);
                    $fp = trim($parts[0] ?? '');
                    if (!empty($fp) && strpos($fp, '\\') !== false) {
                        $ns = explode('\\', $fp)[0];
                        if (!isset($use_counts[$ns])) $use_counts[$ns] = 0;
                        $use_counts[$ns]++;
                    }
                }
                elseif ($tt === T_REQUIRE || $tt === T_REQUIRE_ONCE) $result['dependency_stats']['require_calls']++;
                elseif ($tt === T_INCLUDE || $tt === T_INCLUDE_ONCE) $result['dependency_stats']['include_calls']++;
            }
        };

        $use_counts = [];
        $file_types = [];
        $largest_files = [];
        $php_file_count = 0;
        $total_size = 0;
        $total_files = 0;

        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($target, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::SELF_FIRST
        );

        foreach ($iterator as $item) {
            if (time() > $deadline) { $result['timed_out'] = true; break; }
            $real_path = $item->getRealPath();
            $rel_path = str_replace($target . DIRECTORY_SEPARATOR, '', $real_path);
            $rel_path = str_replace('\\', '/', $rel_path);
            if (!$include_vendor && (strpos($rel_path, 'vendor/') === 0 || strpos($rel_path, 'node_modules/') === 0)) continue;
            if (preg_match('#/\\.|^\\.#', $rel_path)) continue;
            if ($item->isDir()) { $result['directories'][] = $rel_path; continue; }
            $total_files++;
            $size = $item->getSize();
            $total_size += $size;
            $ext = strtolower($item->getExtension());
            if (!isset($file_types[$ext])) $file_types[$ext] = 0;
            $file_types[$ext]++;
            if ($ext === 'php') {
                $php_file_count++;
                if ($php_file_count <= $max_files) $analyzeFile($real_path, $rel_path, $result, $use_counts, $largest_files);
            } elseif ($ext === 'json' || $ext === 'yaml' || $ext === 'yml' || $ext === 'env' || $ext === 'xml' || $ext === 'md') {
                if (count($largest_files) < 5 || $size > 50000) $largest_files[] = ['path' => $rel_path, 'size' => $size, 'type' => $ext];
            }
        }

        usort($largest_files, function($a, $b) { return $b['size'] <=> $a['size']; });
        $result['largest_files'] = array_slice($largest_files, 0, 10);
        $result['file_stats'] = ['total_files' => $total_files, 'php_files' => $php_file_count, 'other_files' => $total_files - $php_file_count, 'total_size_bytes' => $total_size, 'php_files_analyzed' => min($php_file_count, $max_files)];
        $result['file_type_breakdown'] = $file_types;
        $result['directories_count'] = count($result['directories']);
        arsort($use_counts);
        $result['top_used_classes'] = array_slice($use_counts, 0, 20);
        $result['scan_time_ms'] = round((microtime(true) - $start) * 1000);

        // Detect project type
        if ($result['composer']) {
            $type = 'PHP project';
            if ($result['composer']['laravel_version']) $type = 'Laravel';
            elseif (strpos($result['composer']['name'] ?? '', 'symfony') !== false) $type = 'Symfony';
            elseif ($result['composer']['type'] === 'library') $type = 'PHP library';
            elseif ($result['composer']['type'] === 'cli' || $result['composer']['type'] === 'project') $type = 'PHP CLI/project';
            if (file_exists($target . '/artisan')) $type = 'Laravel';
            if (file_exists($target . '/app/Http/Controllers')) $type = 'Laravel';
            $result['project_type'] = $type;
        }

        return ['success' => true, 'result' => $result];
    }
}
