<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_random_number = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'random_number',
    'description' => 'Generate a cryptographically secure random integer between min and max inclusive.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'min' => 
        array (
          'type' => 'integer',
          'description' => 'Minimum value (inclusive)',
        ),
        'max' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum value (inclusive)',
        ),
      ),
      'required' => 
      array (
        0 => 'min',
        1 => 'max',
      ),
    ),
  ),
);

if (! function_exists('random_number')) {
    function random_number($min, $max)
    {
        if ($min > $max) {
            return json_encode(['error' => 'min must be less than or equal to max']);
        }
        $value = random_int($min, $max);
        return json_encode(['min' => $min, 'max' => $max, 'value' => $value]);
    }
}
