<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_read_file = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'read_file',
    'description' => 'Read the contents of a file within the project directory. Path is relative to project root. Refuses to read .env, vendor/, .git/.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'path' => 
        array (
          'type' => 'string',
          'description' => 'File path relative to project root, e.g. \'storage/agent/tools/list_directory.php\'',
        ),
      ),
      'required' => 
      array (
        0 => 'path',
      ),
    ),
  ),
);

if (! function_exists('read_file')) {
    function read_file($path)
    {
        $base = realpath(__DIR__ . '/../../..');
        $full = realpath($base . '/' . ltrim($path, '/'));
        if ($full === false || strpos($full, $base) !== 0) {
            return json_encode(['error' => 'Invalid or restricted path']);
        }
        $restricted = ['/.env', '/.git/', '/vendor/'];
        foreach ($restricted as $r) {
            if (strpos($full, $base . $r) !== false) {
                return json_encode(['error' => 'Access denied: restricted file']);
            }
        }
        if (!is_file($full)) {
            return json_encode(['error' => 'File not found']);
        }
        $content = file_get_contents($full);
        if ($content === false) {
            return json_encode(['error' => 'Failed to read file']);
        }
        return json_encode(['path' => $path, 'size' => strlen($content), 'content' => $content]);
    }
}
