<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_redis_client = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'redis_client',
    'description' => 'Connect to a Redis server, execute commands, and return results. Supports all Redis commands (GET, SET, LPUSH, PUBLISH, SUBSCRIBE, INFO, etc.) via the PHP Redis extension. Returns structured responses with type information. Handles connection errors, authentication (AUTH), database selection (SELECT), and timeouts. Complements websocket_client (real-time binary protocol) by adding in-memory data store access. First Redis/database-cache capability in the ecosystem. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'host' => 
        array (
          'type' => 'string',
          'description' => 'Redis server hostname or IP (default: \'127.0.0.1\').',
        ),
        'port' => 
        array (
          'type' => 'integer',
          'description' => 'Redis server port (default: 6379).',
        ),
        'password' => 
        array (
          'type' => 'string',
          'description' => 'Optional Redis AUTH password.',
        ),
        'database' => 
        array (
          'type' => 'integer',
          'description' => 'Redis database index (0-15, default: 0).',
        ),
        'command' => 
        array (
          'type' => 'string',
          'description' => 'Redis command to execute (e.g. \'PING\', \'INFO\', \'KEYS *\', \'GET mykey\', \'SET mykey value\', \'LPUSH mylist item\', \'PUBLISH channel message\'). Required.',
        ),
        'timeout' => 
        array (
          'type' => 'number',
          'description' => 'Connection timeout in seconds (0.5-30, default: 5).',
        ),
        'retry' => 
        array (
          'type' => 'integer',
          'description' => 'Max retry attempts on connection failure (0-3, default: 1).',
        ),
      ),
      'required' => 
      array (
        0 => 'command',
      ),
    ),
  ),
);

if (! function_exists('redis_client')) {
    function redis_client($command, $host = null, $port = null, $password = null, $database = null, $timeout = null, $retry = null)
    {
        // Redis client using the PHP Redis extension
        // Supports all Redis commands through a unified interface

        // Validate inputs
        $host = isset($host) ? (string)$host : '127.0.0.1';
        $port = isset($port) ? (int)$port : 6379;
        $timeout = isset($timeout) ? min(max((float)$timeout, 0.5), 30.0) : 5.0;
        $database = isset($database) ? min(max((int)$database, 0), 15) : 0;
        $retry = isset($retry) ? min(max((int)$retry, 0), 3) : 1;
        $cmd = isset($command) ? trim((string)$command) : '';
        $password = isset($password) ? (string)$password : '';

        if ($cmd === '') {
            return ['error' => 'Empty command', 'result' => null];
        }

        // Check if Redis extension is available
        if (!extension_loaded('redis')) {
            return ['error' => 'Redis PHP extension is not loaded', 'result' => null];
        }

        // Parse command respecting quoted strings (like shell arguments)
        $parts = str_getcsv($cmd, ' ');
        $command_name = strtoupper($parts[0]);
        $args = array_slice($parts, 1);

        $last_error = '';
        $attempts = 0;

        while ($attempts <= $retry) {
            $attempts++;
            
            try {
                $redis = new Redis();
                $connected = @$redis->connect($host, $port, $timeout);
                
                if (!$connected) {
                    $last_error = "Connection failed to {$host}:{$port} (attempt {$attempts})";
                    if ($attempts <= $retry) {
                        usleep(200000);
                    }
                    continue;
                }
                
                // Authenticate if password provided
                if ($password !== '') {
                    if (!$redis->auth($password)) {
                        $redis->close();
                        return ['error' => 'AUTH failed: invalid password', 'result' => null];
                    }
                }
                
                // Select database
                if ($database > 0) {
                    $redis->select($database);
                }
                
                // Execute command via switch
                $result = null;
                $result_type = 'unknown';
                
                switch ($command_name) {
                    // --- Connection ---
                    case 'PING':
                        $result = $redis->ping();
                        $result_type = 'string';
                        break;
                        
                    case 'ECHO':
                        $result = count($args) >= 1 ? $redis->echo($args[0]) : false;
                        $result_type = 'string';
                        break;
                        
                    case 'SELECT':
                        $result = count($args) >= 1 ? $redis->select((int)$args[0]) : false;
                        $result_type = 'status';
                        break;
                        
                    case 'AUTH':
                        $result = count($args) >= 1 ? $redis->auth(implode(' ', $args)) : false;
                        $result_type = 'status';
                        break;
                        
                    // --- Keys ---
                    case 'KEYS':
                        $result = $redis->keys(count($args) >= 1 ? $args[0] : '*');
                        $result_type = 'array';
                        break;
                        
                    case 'GET':
                        $result = count($args) >= 1 ? $redis->get($args[0]) : null;
                        $result_type = 'string_or_null';
                        break;
                        
                    case 'SET':
                        $result = count($args) >= 2 ? $redis->set($args[0], $args[1]) : false;
                        $result_type = 'status';
                        break;
                        
                    case 'SETEX':
                        $result = count($args) >= 3 ? $redis->setex($args[0], (int)$args[1], $args[2]) : false;
                        $result_type = 'status';
                        break;
                        
                    case 'DEL':
                        $result = count($args) >= 1 ? $redis->del(...$args) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'EXISTS':
                        $result = count($args) >= 1 ? $redis->exists(...$args) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'EXPIRE':
                        $result = count($args) >= 2 ? $redis->expire($args[0], (int)$args[1]) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'TTL':
                        $result = count($args) >= 1 ? $redis->ttl($args[0]) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'TYPE':
                        $result = count($args) >= 1 ? $redis->type($args[0]) : false;
                        $result_type = 'string';
                        break;
                        
                    // --- Strings ---
                    case 'INCR':
                        $result = count($args) >= 1 ? $redis->incr($args[0]) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'INCRBY':
                        $result = count($args) >= 2 ? $redis->incrBy($args[0], (int)$args[1]) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'DECR':
                        $result = count($args) >= 1 ? $redis->decr($args[0]) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'MGET':
                        $result = count($args) >= 1 ? $redis->mget($args) : [];
                        $result_type = 'array';
                        break;
                        
                    case 'MSET':
                        if (count($args) >= 2 && count($args) % 2 === 0) {
                            $kv = [];
                            for ($i = 0; $i < count($args); $i += 2) {
                                $kv[$args[$i]] = $args[$i+1];
                            }
                            $result = $redis->mset($kv);
                        } else {
                            $result = false;
                        }
                        $result_type = 'status';
                        break;
                        
                    // --- Lists ---
                    case 'LPUSH':
                        $result = count($args) >= 1 ? $redis->lPush($args[0], ...array_slice($args, 1)) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'RPUSH':
                        $result = count($args) >= 1 ? $redis->rPush($args[0], ...array_slice($args, 1)) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'LPOP':
                        $result = count($args) >= 1 ? $redis->lPop($args[0]) : false;
                        $result_type = 'string_or_null';
                        break;
                        
                    case 'RPOP':
                        $result = count($args) >= 1 ? $redis->rPop($args[0]) : false;
                        $result_type = 'string_or_null';
                        break;
                        
                    case 'LLEN':
                        $result = count($args) >= 1 ? $redis->lLen($args[0]) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'LRANGE':
                        $result = count($args) >= 3 ? $redis->lRange($args[0], (int)$args[1], (int)$args[2]) : false;
                        $result_type = 'array';
                        break;
                        
                    // --- Sets ---
                    case 'SADD':
                        $result = count($args) >= 1 ? $redis->sAdd($args[0], ...array_slice($args, 1)) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'SMEMBERS':
                        $result = count($args) >= 1 ? $redis->sMembers($args[0]) : [];
                        $result_type = 'array';
                        break;
                        
                    case 'SISMEMBER':
                        $result = count($args) >= 2 ? $redis->sIsMember($args[0], $args[1]) : false;
                        $result_type = 'boolean';
                        break;
                        
                    case 'SCARD':
                        $result = count($args) >= 1 ? $redis->sCard($args[0]) : false;
                        $result_type = 'integer';
                        break;
                        
                    // --- Hashes ---
                    case 'HSET':
                        $result = count($args) >= 3 ? $redis->hSet($args[0], $args[1], $args[2]) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'HGET':
                        $result = count($args) >= 2 ? $redis->hGet($args[0], $args[1]) : false;
                        $result_type = 'string_or_null';
                        break;
                        
                    case 'HGETALL':
                        $result = count($args) >= 1 ? $redis->hGetAll($args[0]) : [];
                        $result_type = 'array';
                        break;
                        
                    case 'HDEL':
                        $result = count($args) >= 1 ? $redis->hDel($args[0], ...array_slice($args, 1)) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'HKEYS':
                        $result = count($args) >= 1 ? $redis->hKeys($args[0]) : [];
                        $result_type = 'array';
                        break;
                        
                    case 'HVALS':
                        $result = count($args) >= 1 ? $redis->hVals($args[0]) : [];
                        $result_type = 'array';
                        break;
                        
                    case 'HLEN':
                        $result = count($args) >= 1 ? $redis->hLen($args[0]) : false;
                        $result_type = 'integer';
                        break;
                        
                    // --- Sorted Sets ---
                    case 'ZADD':
                        $result = count($args) >= 3 ? $redis->zAdd($args[0], (float)$args[1], $args[2]) : false;
                        $result_type = 'integer';
                        break;
                        
                    case 'ZRANGE':
                        $result = count($args) >= 3 ? $redis->zRange($args[0], (int)$args[1], (int)$args[2]) : [];
                        $result_type = 'array';
                        break;
                        
                    case 'ZCARD':
                        $result = count($args) >= 1 ? $redis->zCard($args[0]) : false;
                        $result_type = 'integer';
                        break;
                        
                    // --- Pub/Sub ---
                    case 'PUBLISH':
                        $result = count($args) >= 2 ? $redis->publish($args[0], $args[1]) : false;
                        $result_type = 'integer';
                        break;
                        
                    // --- Server ---
                    case 'INFO':
                        $result = $redis->info(count($args) >= 1 ? $args[0] : null);
                        $result_type = 'array';
                        break;
                        
                    case 'DBSIZE':
                        $result = $redis->dbSize();
                        $result_type = 'integer';
                        break;
                        
                    case 'FLUSHDB':
                        $result = $redis->flushDB();
                        $result_type = 'status';
                        break;
                        
                    case 'FLUSHALL':
                        $result = $redis->flushAll();
                        $result_type = 'status';
                        break;
                        
                    case 'TIME':
                        $result = $redis->time();
                        $result_type = 'array';
                        break;
                        
                    case 'RANDOMKEY':
                        $result = $redis->randomKey();
                        $result_type = 'string_or_null';
                        break;
                        
                    case 'CLIENT':
                        $result = $redis->client(...$args);
                        $result_type = 'mixed';
                        break;
                        
                    // --- Transactions ---
                    case 'MULTI':
                        $result = $redis->multi();
                        $result_type = 'status';
                        break;
                        
                    case 'EXEC':
                        $result = $redis->exec();
                        $result_type = 'array';
                        break;
                        
                    case 'DISCARD':
                        $result = $redis->discard();
                        $result_type = 'status';
                        break;
                        
                    default:
                        // Try rawCommand as fallback
                        try {
                            $result = @$redis->rawCommand($command_name, ...$args);
                            $result_type = 'raw';
                        } catch (\Throwable $e) {
                            $redis->close();
                            return [
                                'error' => "Unsupported command: {$command_name}",
                                'details' => $e->getMessage(),
                                'result' => null
                            ];
                        }
                        break;
                }
                
                $redis->close();
                
                return [
                    'success' => true,
                    'server' => "{$host}:{$port}",
                    'database' => $database,
                    'command' => $cmd,
                    'result' => $result,
                    'result_type' => $result_type,
                    'attempts' => $attempts
                ];
                
            } catch (\Throwable $e) {
                $last_error = $e->getMessage();
                if ($attempts <= $retry) {
                    usleep(200000);
                }
            }
        }

        return [
            'error' => "Redis operation failed after {$attempts} attempt(s): {$last_error}",
            'server' => "{$host}:{$port}",
            'command' => $cmd,
            'result' => null
        ];
    }
}
