<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_scheduled_report = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'scheduled_report',
    'description' => 'Generate a dated markdown digest from multiple live data sources. Fetches data from HackerNews (top stories), Open-Meteo (weather), GitHub (trending repos via search), and optional RSS feeds. Composes all results into a well-formatted markdown report and writes it to the workspace. Designed to be called unattended (e.g. from cron). Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'hn_stories' => 
        array (
          'type' => 'integer',
          'description' => 'Number of HackerNews top stories to include (0 = skip HN, default: 10).',
        ),
        'weather_city' => 
        array (
          'type' => 'string',
          'description' => 'City name for weather report (e.g. \'London\', \'Tokyo\'). Empty = skip weather.',
        ),
        'github_topic' => 
        array (
          'type' => 'string',
          'description' => 'GitHub topic/search term for trending repos (e.g. \'php\', \'machine-learning\'). Empty = skip GitHub.',
        ),
        'rss_url' => 
        array (
          'type' => 'string',
          'description' => 'RSS/Atom feed URL to include recent items. Empty = skip RSS.',
        ),
        'title' => 
        array (
          'type' => 'string',
          'description' => 'Optional custom title for the report (default: auto-generated from date).',
        ),
        'filename' => 
        array (
          'type' => 'string',
          'description' => 'Output filename in workspace (default: auto-generated \'report-YYYY-MM-DD-HHMMSS.md\').',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout per source in seconds (5-30, default: 15).',
        ),
        'max_rss_items' => 
        array (
          'type' => 'integer',
          'description' => 'Max items from RSS feed (1-20, default: 10).',
        ),
      ),
      'required' => 
      array (
      ),
    ),
  ),
);

if (! function_exists('scheduled_report')) {
    function scheduled_report($hn_stories = null, $weather_city = null, $github_topic = null, $rss_url = null, $title = null, $filename = null, $timeout = null, $max_rss_items = null)
    {
        // Scheduled report - multi-source markdown digest
        $hn_stories = isset($hn_stories) ? max(0, (int)$hn_stories) : 10;
        $weather_city = isset($weather_city) ? (string)$weather_city : '';
        $github_topic = isset($github_topic) ? (string)$github_topic : '';
        $rss_url = isset($rss_url) ? (string)$rss_url : '';
        $custom_title = isset($title) ? (string)$title : '';
        $filename = isset($filename) ? (string)$filename : 'report-' . date('Y-m-d-Hi') . '.md';
        $timeout = isset($timeout) ? min(max((int)$timeout, 5), 30) : 15;
        $max_rss = isset($max_rss_items) ? min(max((int)$max_rss_items, 1), 20) : 10;

        $ws = realpath(__DIR__ . '/../../workspace');
        $output = $ws . '/' . $filename;

        $title = $custom_title ?: 'Daily Report - ' . date('Y-m-d');
        $report = "# {$title}\n\n";
        $report .= "_Generated: " . date('Y-m-d H:i:s T') . "_\n\n";
        $sources_ok = 0;
        $sources_err = 0;
        $errors = [];

        // HackerNews
        if ($hn_stories > 0) {
            $report .= "## HackerNews Top Stories\n\n";
            $hn_data = @file_get_contents('https://hacker-news.firebaseio.com/v0/topstories.json', false, stream_context_create(['http' => ['timeout' => $timeout]]));
            if ($hn_data !== false) {
                $ids = array_slice(json_decode($hn_data, true) ?: [], 0, $hn_stories);
                foreach ($ids as $id) {
                    $item = @file_get_contents("https://hacker-news.firebaseio.com/v0/item/{$id}.json", false, stream_context_create(['http' => ['timeout' => 5]]));
                    if ($item) {
                        $story = json_decode($item, true);
                        if ($story && isset($story['title'])) {
                            $score = $story['score'] ?? 0;
                            $link = $story['url'] ?? "https://news.ycombinator.com/item?id={$id}";
                            $by = $story['by'] ?? 'anonymous';
                            $report .= "- [{$story['title']}]({$link}) ({$score} pts by {$by})\n";
                        }
                    }
                }
                $sources_ok++;
                $report .= "\n";
            } else {
                $sources_err++;
                $errors[] = 'HackerNews: fetch failed';
                $report .= "_Failed to fetch HackerNews stories_\n\n";
            }
        }

        // Weather
        if ($weather_city !== '') {
            $report .= "## Weather: {$weather_city}\n\n";
            $geo = @file_get_contents("https://geocoding-api.open-meteo.com/v1/search?name=" . urlencode($weather_city) . "&count=1", false, stream_context_create(['http' => ['timeout' => $timeout]]));
            if ($geo) {
                $geo_data = json_decode($geo, true);
                if ($geo_data && isset($geo_data['results'][0])) {
                    $lat = $geo_data['results'][0]['latitude'];
                    $lon = $geo_data['results'][0]['longitude'];
                    $wx = @file_get_contents("https://api.open-meteo.com/v1/forecast?latitude={$lat}&longitude={$lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&timezone=auto", false, stream_context_create(['http' => ['timeout' => $timeout]]));
                    if ($wx) {
                        $wx_data = json_decode($wx, true);
                        if ($wx_data && isset($wx_data['current'])) {
                            $cur = $wx_data['current'];
                            $report .= "- Temperature: {$cur['temperature_2m']}°C (feels like {$cur['apparent_temperature']}°C)\n";
                            $report .= "- Humidity: {$cur['relative_humidity_2m']}%\n";
                            if (isset($cur['wind_speed_10m'])) $report .= "- Wind: {$cur['wind_speed_10m']} km/h\n";
                            $report .= "- Weather code: {$cur['weather_code']}\n";
                        }
                        if (isset($wx_data['daily'])) {
                            $daily = $wx_data['daily'];
                            $report .= "\n**Forecast:**\n\n";
                            for ($d = 0; $d < min(3, count($daily['time'] ?? [])); $d++) {
                                $report .= "- {$daily['time'][$d]}: {$daily['temperature_2m_min'][$d]}°C - {$daily['temperature_2m_max'][$d]}°C, precip {$daily['precipitation_sum'][$d]}mm\n";
                            }
                        }
                        $sources_ok++;
                    }
                }
            }
            $report .= "\n";
        }

        // GitHub
        if ($github_topic !== '') {
            $report .= "## GitHub: {$github_topic}\n\n";
            $gh = @file_get_contents("https://api.github.com/search/repositories?q={$github_topic}&sort=stars&order=desc&per_page=5", false, stream_context_create(['http' => ['method' => 'GET', 'header' => "User-Agent: PHP-Report-Bot\r\n", 'timeout' => $timeout]]));
            if ($gh) {
                $gh_data = json_decode($gh, true);
                if ($gh_data && isset($gh_data['items'])) {
                    foreach ($gh_data['items'] as $repo) {
                        $stars = $repo['stargazers_count'] ?? 0;
                        $desc = $repo['description'] ?? '(no description)';
                        $report .= "- [{$repo['full_name']}]({$repo['html_url']}) ⭐{$stars} — {$desc}\n";
                    }
                    $sources_ok++;
                }
            } else {
                $report .= "_Failed to fetch GitHub data_\n";
            }
            $report .= "\n";
        }

        // RSS
        if ($rss_url !== '') {
            $report .= "## RSS Feed\n\n";
            $rss_data = @file_get_contents($rss_url, false, stream_context_create(['http' => ['timeout' => $timeout]]));
            if ($rss_data !== false) {
                $xml = @simplexml_load_string($rss_data);
                if ($xml) {
                    $items = [];
                    if (isset($xml->channel->item)) {
                        foreach ($xml->channel->item as $item) {
                            $items[] = ['title' => (string)$item->title, 'link' => (string)$item->link, 'date' => (string)$item->pubDate];
                        }
                    } elseif (isset($xml->entry)) {
                        foreach ($xml->entry as $entry) {
                            $link_attr = $entry->link ? (string)$entry->link['href'] : '';
                            $items[] = ['title' => (string)$entry->title, 'link' => $link_attr, 'date' => (string)$entry->updated];
                        }
                    }
                    $items = array_slice($items, 0, $max_rss);
                    foreach ($items as $item) {
                        $report .= "- [{$item['title']}]({$item['link']}) — {$item['date']}\n";
                    }
                    $sources_ok++;
                }
            } else {
                $report .= "_Failed to fetch RSS feed_\n";
            }
            $report .= "\n";
        }

        // Summary
        $report .= "---\n";
        $report .= "_Sources: {$sources_ok} ok, {$sources_err} failed_\n";
        if (count($errors) > 0) {
            $report .= "_Errors: " . implode('; ', $errors) . "_\n";
        }

        file_put_contents($output, $report);

        return [
            'success' => true,
            'filename' => $filename,
            'report_length' => strlen($report),
            'sources_ok' => $sources_ok,
            'sources_failed' => $sources_err,
            'errors' => count($errors) > 0 ? $errors : null,
        ];
    }
}
