<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_smtp_send_email = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'smtp_send_email',
    'description' => 'Send an email via SMTP protocol using raw TCP sockets. Implements the SMTP protocol (RFC 5321) with HELO/EHLO, MAIL FROM, RCPT TO, DATA, and QUIT commands. Supports optional authentication (AUTH LOGIN) and TLS upgrades (STARTTLS). Connects via stream_socket_client, speaks the SMTP protocol line-by-line, handles multi-line responses. Composes with scheduled_report, web_research, and text_template for automated email reports. First email/send capability in the ecosystem — the only tool that can push notifications out to the world. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'host' => 
        array (
          'type' => 'string',
          'description' => 'SMTP server hostname or IP (default: \'127.0.0.1\').',
        ),
        'port' => 
        array (
          'type' => 'integer',
          'description' => 'SMTP server port (25, 465, 587). Default: 25.',
        ),
        'username' => 
        array (
          'type' => 'string',
          'description' => 'Username for AUTH LOGIN (optional).',
        ),
        'password' => 
        array (
          'type' => 'string',
          'description' => 'Password for AUTH LOGIN (optional).',
        ),
        'use_tls' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, use TLS (connecting to port 465 with implicit TLS, or upgrade via STARTTLS on 587). Default: false.',
        ),
        'from_email' => 
        array (
          'type' => 'string',
          'description' => 'Sender email address. Required.',
        ),
        'from_name' => 
        array (
          'type' => 'string',
          'description' => 'Sender display name (default: auto).',
        ),
        'to' => 
        array (
          'type' => 'string',
          'description' => 'Recipient email address(es). Comma-separated for multiple. Required.',
        ),
        'subject' => 
        array (
          'type' => 'string',
          'description' => 'Email subject line. Required.',
        ),
        'body' => 
        array (
          'type' => 'string',
          'description' => 'Email body (plain text). Required.',
        ),
        'cc' => 
        array (
          'type' => 'string',
          'description' => 'CC recipient(s), comma-separated.',
        ),
        'bcc' => 
        array (
          'type' => 'string',
          'description' => 'BCC recipient(s), comma-separated.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Connection timeout in seconds (5-60, default: 15).',
        ),
      ),
      'required' => 
      array (
        0 => 'from_email',
        1 => 'to',
        2 => 'subject',
        3 => 'body',
      ),
    ),
  ),
);

if (! function_exists('smtp_send_email')) {
    function smtp_send_email($from_email, $to, $subject, $body, $host = null, $port = null, $username = null, $password = null, $use_tls = null, $from_name = null, $cc = null, $bcc = null, $timeout = null)
    {
        // SMTP client - send emails via SMTP protocol (RFC 5321)
        // Uses stream_socket_client for raw TCP connection

        // Validate inputs
        $host = isset($host) ? (string)$host : '127.0.0.1';
        $port = isset($port) ? (int)$port : 25;
        $timeout = isset($timeout) ? min(max((int)$timeout, 5), 60) : 15;
        $from_email = isset($from_email) ? trim((string)$from_email) : '';
        $from_name = isset($from_name) ? trim((string)$from_name) : '';
        $to_raw = isset($to) ? (string)$to : '';
        $cc_raw = isset($cc) ? (string)$cc : '';
        $bcc_raw = isset($bcc) ? (string)$bcc : '';
        $subject = isset($subject) ? (string)$subject : '';
        $body = isset($body) ? (string)$body : '';
        $username = isset($username) ? (string)$username : '';
        $password = isset($password) ? (string)$password : '';
        $use_tls = isset($use_tls) ? (bool)$use_tls : false;

        if ($from_email === '') {
            return ['error' => 'Sender email (from_email) is required'];
        }
        if ($to_raw === '') {
            return ['error' => 'Recipient email (to) is required'];
        }
        if ($subject === '' && $body === '') {
            return ['error' => 'Subject and body are required'];
        }

        $log = [];
        $addLog = function($msg) use (&$log) { $log[] = $msg; };

        // Parse recipients
        $recipients = [];
        foreach ([$to_raw, $cc_raw, $bcc_raw] as $raw) {
            if ($raw !== '') {
                foreach (explode(',', $raw) as $r) {
                    $r = trim($r);
                    if ($r !== '') $recipients[] = $r;
                }
            }
        }

        try {
            // Determine connection type
            $remote = $host . ':' . $port;
            $scheme = 'tcp://';
            
            // Port 465 is implicit TLS (SMTPS)
            if ($port === 465 || $use_tls) {
                $scheme = 'tls://';
            }
            
            $addLog("Connecting to {$scheme}{$remote}...");
            
            $socket = @stream_socket_client($scheme . $remote, $errno, $errstr, $timeout);
            if (!$socket) {
                return ['error' => "Connection failed: {$errstr} ({$errno})", 'log' => $log];
            }
            
            stream_set_timeout($socket, $timeout);
            
            // Read greeting (220)
            $greeting = fgets($socket);
            $addLog("S: {$greeting}");
            if (!str_starts_with(trim($greeting ?: ''), '220')) {
                fclose($socket);
                return ['error' => "Expected 220 greeting, got: " . trim($greeting ?: ''), 'log' => $log];
            }
            
            // Send EHLO
            $ehlo_host = gethostname() ?: 'localhost';
            fwrite($socket, "EHLO {$ehlo_host}\r\n");
            $addLog("C: EHLO {$ehlo_host}");
            
            // Read EHLO response (multi-line, ends with "250 ")
            $ehlo_resp = '';
            while (true) {
                $line = fgets($socket);
                if ($line === false) break;
                $ehlo_resp .= $line;
                $addLog("S: " . trim($line));
                if (strlen($line) >= 4 && substr($line, 3, 1) === ' ') break;
            }
            
            if (!str_starts_with(trim(explode("\n", $ehlo_resp)[0]), '250')) {
                // Try HELO instead
                fwrite($socket, "HELO {$ehlo_host}\r\n");
                $addLog("C: HELO {$ehlo_host}");
                $helo_resp = fgets($socket);
                $addLog("S: " . trim($helo_resp ?: ''));
                if (!str_starts_with(trim($helo_resp ?: ''), '250')) {
                    fclose($socket);
                    return ['error' => 'EHLO/HELO rejected', 'log' => $log];
                }
            }
            
            // STARTTLS if on port 587 and requested (not already using implicit TLS)
            if ($port !== 465 && $use_tls) {
                fwrite($socket, "STARTTLS\r\n");
                $addLog("C: STARTTLS");
                $starttls_resp = fgets($socket);
                $addLog("S: " . trim($starttls_resp ?: ''));
                
                if (str_starts_with(trim($starttls_resp ?: ''), '220')) {
                    // Upgrade to TLS
                    $crypto = @stream_socket_enable_crypto($socket, true, STREAM_CRYPTO_METHOD_TLS_CLIENT);
                    if ($crypto) {
                        $addLog("TLS handshake successful");
                        // Re-send EHLO after TLS
                        fwrite($socket, "EHLO {$ehlo_host}\r\n");
                        $addLog("C: EHLO {$ehlo_host} (TLS)");
                        while (true) {
                            $line = fgets($socket);
                            if ($line === false) break;
                            $addLog("S: " . trim($line));
                            if (strlen($line) >= 4 && substr($line, 3, 1) === ' ') break;
                        }
                    } else {
                        $addLog("TLS handshake failed, continuing without encryption");
                    }
                }
            }
            
            // AUTH LOGIN if credentials provided
            if ($username !== '' && $password !== '') {
                fwrite($socket, "AUTH LOGIN\r\n");
                $addLog("C: AUTH LOGIN");
                $auth_resp = fgets($socket);
                $addLog("S: " . trim($auth_resp ?: ''));
                
                if (str_starts_with(trim($auth_resp ?: ''), '334')) {
                    // Send base64-encoded username
                    fwrite($socket, base64_encode($username) . "\r\n");
                    $addLog("C: " . base64_encode($username) . " (username)");
                    $user_resp = fgets($socket);
                    $addLog("S: " . trim($user_resp ?: ''));
                    
                    if (str_starts_with(trim($user_resp ?: ''), '334')) {
                        // Send base64-encoded password
                        fwrite($socket, base64_encode($password) . "\r\n");
                        $addLog("C: " . base64_encode($password) . " (password)");
                        $pass_resp = fgets($socket);
                        $addLog("S: " . trim($pass_resp ?: ''));
                        
                        if (!str_starts_with(trim($pass_resp ?: ''), '235')) {
                            $addLog("AUTH failed (continuing without auth)");
                        }
                    }
                } else {
                    $addLog("AUTH LOGIN not supported by server (continuing without auth)");
                }
            }
            
            // MAIL FROM
            fwrite($socket, "MAIL FROM:<{$from_email}>\r\n");
            $addLog("C: MAIL FROM:<{$from_email}>");
            $mf_resp = fgets($socket);
            $addLog("S: " . trim($mf_resp ?: ''));
            if (!str_starts_with(trim($mf_resp ?: ''), '250')) {
                fclose($socket);
                return ['error' => 'MAIL FROM rejected', 'response' => trim($mf_resp ?: ''), 'log' => $log];
            }
            
            // RCPT TO for each recipient
            $rcpt_success = 0;
            $rcpt_fail = 0;
            foreach ($recipients as $rcpt) {
                fwrite($socket, "RCPT TO:<{$rcpt}>\r\n");
                $addLog("C: RCPT TO:<{$rcpt}>");
                $rcpt_resp = fgets($socket);
                $addLog("S: " . trim($rcpt_resp ?: ''));
                if (str_starts_with(trim($rcpt_resp ?: ''), '250')) {
                    $rcpt_success++;
                } else {
                    $rcpt_fail++;
                }
            }
            
            if ($rcpt_success === 0) {
                fclose($socket);
                return ['error' => 'All recipients rejected', 'log' => $log];
            }
            
            // DATA
            fwrite($socket, "DATA\r\n");
            $addLog("C: DATA");
            $data_resp = fgets($socket);
            $addLog("S: " . trim($data_resp ?: ''));
            if (!str_starts_with(trim($data_resp ?: ''), '354')) {
                fclose($socket);
                return ['error' => 'DATA command rejected', 'response' => trim($data_resp ?: ''), 'log' => $log];
            }
            
            // Build email headers + body
            $email = "From: {$from_name} <{$from_email}>\r\n";
            $email .= "To: {$to_raw}\r\n";
            if ($cc_raw !== '') {
                $email .= "Cc: {$cc_raw}\r\n";
            }
            $email .= "Subject: {$subject}\r\n";
            $email .= "Date: " . date('r') . "\r\n";
            $email .= "MIME-Version: 1.0\r\n";
            $email .= "Content-Type: text/plain; charset=UTF-8\r\n";
            $email .= "Content-Transfer-Encoding: 8bit\r\n";
            $email .= "\r\n";
            $email .= $body . "\r\n";
            $email .= ".\r\n"; // End of data marker
            
            fwrite($socket, $email);
            $addLog("C: [email body, " . strlen($body) . " chars]");
            $addLog("C: .");
            
            $send_resp = fgets($socket);
            $addLog("S: " . trim($send_resp ?: ''));
            
            $sent_success = str_starts_with(trim($send_resp ?: ''), '250');
            
            // QUIT
            fwrite($socket, "QUIT\r\n");
            $addLog("C: QUIT");
            $quit_resp = fgets($socket);
            $addLog("S: " . trim($quit_resp ?: ''));
            
            fclose($socket);
            
            return [
                'success' => $sent_success,
                'message' => $sent_success ? 'Email sent successfully' : 'Email may not have been accepted',
                'server' => "{$host}:{$port}",
                'from' => $from_email,
                'to' => $recipients,
                'subject' => $subject,
                'body_length' => strlen($body),
                'rcpt_accepted' => $rcpt_success,
                'rcpt_rejected' => $rcpt_fail,
                'log' => $log,
            ];
            
        } catch (\Throwable $e) {
            if (isset($socket) && $socket) fclose($socket);
            return [
                'error' => 'SMTP error: ' . $e->getMessage(),
                'log' => $log,
            ];
        }
    }
}
