<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_sqlite_query = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'sqlite_query',
    'description' => 'Query a SQLite database file using PDO. Supports CREATE TABLE, INSERT, SELECT, UPDATE, DELETE, and arbitrary SQL. Creates the database file if it doesn\'t exist. Returns affected row count, inserted row ID, and fetched rows. Enables persistent structured data storage across sessions — a capability no other tool in the ecosystem provides. Uses PHP\'s PDO_SQLite extension. Never throws — all errors returned as structured data. Database files are stored in the workspace directory.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'sql' => 
        array (
          'type' => 'string',
          'description' => 'The SQL query to execute (e.g. \'CREATE TABLE items (id INTEGER PRIMARY KEY, name TEXT, value TEXT)\', \'SELECT * FROM items WHERE name = ?\', \'INSERT INTO items (name, value) VALUES (?, ?)\')',
        ),
        'params' => 
        array (
          'type' => 'array',
          'description' => 'Optional parameter values for prepared statement placeholders (?). E.g. [\'mykey\', \'myvalue\']',
        ),
        'db_name' => 
        array (
          'type' => 'string',
          'description' => 'Database filename (without path, stored in storage/agent/workspace/). Default: \'agent_data.sqlite\'. Example: \'research.sqlite\'',
        ),
      ),
      'required' => 
      array (
        0 => 'sql',
      ),
    ),
  ),
);

if (! function_exists('sqlite_query')) {
    function sqlite_query($sql, $params = null, $db_name = null)
    {
        if (!is_string($sql) || $sql === '') {
            return ['error' => 'SQL query is required.', 'rows' => [], 'changes' => 0];
        }

        $db_name = isset($db_name) && is_string($db_name) && $db_name !== '' ? preg_replace('/[^a-zA-Z0-9_\-\.]/', '', $db_name) : 'agent_data.sqlite';
        if ($db_name === '') $db_name = 'agent_data.sqlite';
        if (!str_ends_with($db_name, '.sqlite')) $db_name .= '.sqlite';

        $params = isset($params) && is_array($params) ? array_values($params) : [];
        $has_params = !empty($params);

        $db_dir = getcwd() . '/storage/agent/workspace';
        $db_path = $db_dir . '/' . $db_name;

        if (!is_dir($db_dir)) {
            @mkdir($db_dir, 0755, true);
        }

        try {
            $pdo = new PDO('sqlite:' . $db_path);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
            
            $pdo->exec('PRAGMA journal_mode=WAL');
            $pdo->exec('PRAGMA foreign_keys=ON');
            
            $upper_sql = strtoupper(trim($sql));
            $is_query = str_starts_with($upper_sql, 'SELECT') || str_starts_with($upper_sql, 'PRAGMA') || str_starts_with($upper_sql, 'EXPLAIN');
            
            $start = microtime(true);
            
            if ($is_query) {
                if ($has_params) {
                    $stmt = $pdo->prepare($sql);
                    $stmt->execute($params);
                } else {
                    $stmt = $pdo->query($sql);
                }
                $rows = $stmt->fetchAll();
                $columns = [];
                if (!empty($rows)) {
                    $columns = array_keys($rows[0]);
                }
                $elapsed = (microtime(true) - $start) * 1000;
                
                return [
                    'error' => null,
                    'db' => $db_name,
                    'db_path' => 'storage/agent/workspace/' . $db_name,
                    'db_size_bytes' => file_exists($db_path) ? filesize($db_path) : 0,
                    'operation' => 'query',
                    'sql' => $sql,
                    'columns' => $columns,
                    'row_count' => count($rows),
                    'rows' => $rows,
                    'changes' => 0,
                    'timing_ms' => round($elapsed, 2),
                ];
            } else {
                if ($has_params) {
                    $stmt = $pdo->prepare($sql);
                    $stmt->execute($params);
                    $row_count = $stmt->rowCount();
                } else {
                    $row_count = $pdo->exec($sql);
                }
                $elapsed = (microtime(true) - $start) * 1000;
                
                $insert_id = $pdo->lastInsertId();
                $inserted_row = null;
                $is_insert = str_contains($upper_sql, 'INSERT');
                
                if ($is_insert && $insert_id && (int)$insert_id > 0) {
                    if (preg_match('/INSERT\s+INTO\s+\"?([\w]+)\"?/i', $sql, $m)) {
                        $table = $m[1];
                        $row_stmt = $pdo->query("SELECT * FROM \"$table\" WHERE rowid = " . (int)$insert_id);
                        if ($row_stmt) {
                            $inserted_row = $row_stmt->fetch();
                        }
                    }
                }
                
                $operation = 'other';
                if (str_contains($upper_sql, 'CREATE')) $operation = 'ddl';
                elseif ($is_insert) $operation = 'insert';
                elseif (str_contains($upper_sql, 'UPDATE')) $operation = 'update';
                elseif (str_contains($upper_sql, 'DELETE')) $operation = 'delete';
                elseif (str_contains($upper_sql, 'DROP')) $operation = 'ddl';
                elseif (str_contains($upper_sql, 'ALTER')) $operation = 'ddl';
                
                return [
                    'error' => null,
                    'db' => $db_name,
                    'db_path' => 'storage/agent/workspace/' . $db_name,
                    'db_size_bytes' => file_exists($db_path) ? filesize($db_path) : 0,
                    'operation' => $operation,
                    'sql' => $sql,
                    'rows_affected' => $row_count !== false ? $row_count : 0,
                    'insert_id' => $insert_id ? (int)$insert_id : null,
                    'inserted_row' => $inserted_row,
                    'timing_ms' => round($elapsed, 2),
                ];
            }
            
        } catch (PDOException $e) {
            return [
                'error' => 'SQLite error: ' . $e->getMessage(),
                'db' => $db_name,
                'sql' => $sql,
                'rows' => [],
                'changes' => 0,
            ];
        } catch (\Exception $e) {
            return [
                'error' => 'Error: ' . $e->getMessage(),
                'db' => $db_name,
                'rows' => [],
                'changes' => 0,
            ];
        }
    }
}
