<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_string_fuzzy_match = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'string_fuzzy_match',
    'description' => 'Calculate the Levenshtein edit distance and similarity percentage between two strings. Useful for fuzzy matching, typo detection, and near-duplicate detection.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'a' => 
        array (
          'type' => 'string',
          'description' => 'First string',
        ),
        'b' => 
        array (
          'type' => 'string',
          'description' => 'Second string',
        ),
      ),
      'required' => 
      array (
        0 => 'a',
        1 => 'b',
      ),
    ),
  ),
);

if (! function_exists('string_fuzzy_match')) {
    function string_fuzzy_match($a, $b)
    {
        $dist = levenshtein($a, $b);
        $maxLen = max(strlen($a), strlen($b));
        $similarity = $maxLen > 0 ? round((1 - $dist / $maxLen) * 100, 2) : 100;
        return json_encode([
            'distance' => $dist,
            'similarity_percent' => $similarity,
            'identical' => $a === $b,
            'length_a' => strlen($a),
            'length_b' => strlen($b)
        ]);
    }
}
