<?php

// Generated by make_tool. Improved by agent: cleaner word count logic.

$toolDefinition_string_count = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'string_count',
    'description' => 'Count characters, words, and lines in a string.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'input' => 
        array (
          'type' => 'string',
          'description' => 'The string to analyze',
        ),
      ),
      'required' => 
      array (
        0 => 'input',
      ),
    ),
  ),
);

if (! function_exists('string_count')) {
    function string_count($input)
    {
        if ($input === '') {
            return json_encode(['characters' => 0, 'words' => 0, 'lines' => 0]);
        }
        $chars = mb_strlen($input, 'UTF-8') ?: strlen($input);
        $trimmed = trim($input);
        $words = $trimmed === '' ? 0 : count(preg_split('/\s+/', $trimmed));
        $lines = substr_count($input, "\n") + 1;
        return json_encode(['characters' => $chars, 'words' => $words, 'lines' => $lines]);
    }
}
