<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_svg_generator = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'svg_generator',
    'description' => 'Generate SVG (Scalable Vector Graphics) images from structured data. Creates vector graphics using pure XML — no GD/raster dependencies. Supports: basic shapes (rect, circle, ellipse, line, polyline, polygon), text, groups, linear gradients, configurable viewport, colors, opacity, stroke/fill, and transforms. Outputs .svg files to workspace. Composes with color_palette_generator for harmonious color schemes. First vector graphics tool in the ecosystem — complements chart_generator/chart_pie (raster PNG) with infinitely scalable SVG. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'elements' => 
        array (
          'type' => 'array',
          'description' => 'Array of SVG element objects. Each element has: type (string, required: \'rect\',\'circle\',\'ellipse\',\'line\',\'polyline\',\'polygon\',\'text\',\'group\'), and type-specific attributes. See description for full attribute details. Required.',
        ),
        'width' => 
        array (
          'type' => 'number',
          'description' => 'SVG width in pixels (default: 400).',
        ),
        'height' => 
        array (
          'type' => 'number',
          'description' => 'SVG height in pixels (default: 300).',
        ),
        'viewBox' => 
        array (
          'type' => 'string',
          'description' => 'Custom viewBox (e.g. \'0 0 100 100\'). Auto-calculated from width/height if empty.',
        ),
        'title' => 
        array (
          'type' => 'string',
          'description' => 'Optional SVG title (becomes <title> element).',
        ),
        'description' => 
        array (
          'type' => 'string',
          'description' => 'Optional SVG description (<desc> element).',
        ),
        'filename' => 
        array (
          'type' => 'string',
          'description' => 'Output filename (without path, .svg added). Default: auto-generated.',
        ),
        'namespace' => 
        array (
          'type' => 'string',
          'description' => 'SVG namespace (default: \'http://www.w3.org/2000/svg\').',
        ),
      ),
      'required' => 
      array (
        0 => 'elements',
      ),
    ),
  ),
);

if (! function_exists('svg_generator')) {
    function svg_generator($elements, $width = null, $height = null, $viewBox = null, $title = null, $description = null, $filename = null, $namespace = null)
    {
        $elements = $elements ?? [];
        $width = isset($width) ? (float)$width : 400;
        $height = isset($height) ? (float)$height : 300;
        $viewBox = isset($viewBox) ? (string)$viewBox : "0 0 {$width} {$height}";
        $title = isset($title) ? (string)$title : '';
        $description = isset($description) ? (string)$description : '';
        $filename = isset($filename) ? (string)$filename : 'vector_' . date('Ymd_His') . '.svg';
        $namespace = isset($namespace) ? (string)$namespace : 'http://www.w3.org/2000/svg';

        if (empty($elements) || !is_array($elements)) return ['error' => 'elements array is required.', 'success' => false];
        if (count($elements) > 500) return ['error' => 'Maximum 500 elements allowed.', 'success' => false];

        $xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
        $xml .= '<svg xmlns="' . htmlspecialchars($namespace) . '"';
        $xml .= ' width="' . $width . '" height="' . $height . '"';
        $xml .= ' viewBox="' . htmlspecialchars($viewBox) . '"';
        $xml .= '>' . "\n";

        if (!empty($title)) $xml .= '  <title>' . htmlspecialchars($title) . '</title>' . "\n";
        if (!empty($description)) $xml .= '  <desc>' . htmlspecialchars($description) . '</desc>' . "\n";
        $xml .= '  <rect width="100%" height="100%" fill="white" />' . "\n";

        $ren = function($elem, $depth) use (&$ren) {
            if (!is_array($elem) || !isset($elem['type'])) return '';
            $type = $elem['type'];
            $valid = ['rect','circle','ellipse','line','polyline','polygon','text','path','group','defs','linearGradient','radialGradient'];
            if (!in_array($type, $valid)) return '<!-- Unknown: ' . htmlspecialchars($type) . ' -->' . "\n";
            $ind = str_repeat('  ', $depth + 1);
            $attrs = '';
            foreach (['fill','stroke','stroke-width','opacity','transform','id','class','style'] as $a) {
                if (isset($elem[$a])) $attrs .= ' ' . $a . '="' . htmlspecialchars((string)$elem[$a]) . '"';
            }
            switch ($type) {
                case 'rect':
                    $x = $elem['x'] ?? 0; $y = $elem['y'] ?? 0; $w = $elem['width'] ?? 50; $h = $elem['height'] ?? 50;
                    $r = $ind . '<rect x="' . $x . '" y="' . $y . '" width="' . $w . '" height="' . $h . '"';
                    if (isset($elem['rx'])) $r .= ' rx="' . $elem['rx'] . '"';
                    if (isset($elem['ry'])) $r .= ' ry="' . $elem['ry'] . '"';
                    return $r . $attrs . ' />' . "\n";
                case 'circle':
                    return $ind . '<circle cx="' . ($elem['cx'] ?? 0) . '" cy="' . ($elem['cy'] ?? 0) . '" r="' . ($elem['r'] ?? 20) . '"' . $attrs . ' />' . "\n";
                case 'ellipse':
                    return $ind . '<ellipse cx="' . ($elem['cx'] ?? 0) . '" cy="' . ($elem['cy'] ?? 0) . '" rx="' . ($elem['rx'] ?? 30) . '" ry="' . ($elem['ry'] ?? 20) . '"' . $attrs . ' />' . "\n";
                case 'line':
                    return $ind . '<line x1="' . ($elem['x1'] ?? 0) . '" y1="' . ($elem['y1'] ?? 0) . '" x2="' . ($elem['x2'] ?? 100) . '" y2="' . ($elem['y2'] ?? 100) . '"' . $attrs . ' />' . "\n";
                case 'polyline':
                case 'polygon':
                    if (!isset($elem['points']) || !is_array($elem['points'])) return $ind . '<!-- empty points -->' . "\n";
                    $pts = []; foreach ($elem['points'] as $p) { if (is_array($p) && count($p)>=2) $pts[] = $p[0].','.$p[1]; }
                    return empty($pts) ? ($ind . "<!-- empty pts -->\n") : ($ind . '<' . $type . ' points="' . implode(' ', $pts) . '"' . $attrs . ' />' . "\n");
                case 'text':
                    $c = $elem['content'] ?? '';
                    $fs = $elem['font-size'] ?? $elem['fontSize'] ?? 16;
                    $ff = $elem['font-family'] ?? $elem['fontFamily'] ?? 'Arial, sans-serif';
                    $ta = $elem['text-anchor'] ?? $elem['textAnchor'] ?? 'start';
                    return $ind . '<text x="' . ($elem['x'] ?? 0) . '" y="' . ($elem['y'] ?? 20) . '" font-size="' . $fs . '" font-family="' . htmlspecialchars($ff) . '" text-anchor="' . $ta . '"' . $attrs . '>' . htmlspecialchars((string)$c) . '</text>' . "\n";
                case 'path':
                    return $ind . '<path d="' . htmlspecialchars($elem['d'] ?? '') . '"' . $attrs . ' />' . "\n";
                case 'linearGradient':
                case 'radialGradient':
                    $id = $elem['id'] ?? 'grad';
                    $tag = ($type === 'linearGradient') ? 'linearGradient' : 'radialGradient';
                    $r = $ind . '<' . $tag . ' id="' . htmlspecialchars($id) . '"';
                    if ($type === 'linearGradient') {
                        $r .= ' x1="' . ($elem['x1'] ?? '0%') . '" y1="' . ($elem['y1'] ?? '0%') . '" x2="' . ($elem['x2'] ?? '100%') . '" y2="' . ($elem['y2'] ?? '0%') . '"';
                    } else {
                        $r .= ' cx="' . ($elem['cx'] ?? '50%') . '" cy="' . ($elem['cy'] ?? '50%') . '" r="' . ($elem['r'] ?? '50%') . '"';
                    }
                    $r .= '>' . "\n";
                    foreach ($elem['stops'] ?? [] as $s) {
                        $r .= $ind . '  <stop offset="' . ($s['offset'] ?? '0%') . '" stop-color="' . htmlspecialchars($s['stop-color'] ?? $s['stopColor'] ?? '#000') . '"' . (isset($s['stop-opacity']) ? ' stop-opacity="'.$s['stop-opacity'].'"' : '') . ' />' . "\n";
                    }
                    return $r . $ind . '</' . $tag . '>' . "\n";
                case 'defs':
                    $r = $ind . '<defs>' . "\n";
                    foreach ($elem['children'] ?? [] as $c) $r .= $ren($c, $depth+1);
                    return $r . $ind . '</defs>' . "\n";
                case 'group':
                    $r = $ind . '<g' . $attrs . '>' . "\n";
                    foreach ($elem['children'] ?? [] as $c) $r .= $ren($c, $depth+1);
                    return $r . $ind . '</g>' . "\n";
            }
            return '';
        };

        foreach ($elements as $e) $xml .= $ren($e, 1);
        $xml .= '</svg>' . "\n";

        $ws = realpath(__DIR__ . '/../workspace');
        if (!$ws) return ['error' => 'Workspace not found.', 'success' => false];
        $out_path = $ws . '/' . $filename;
        $written = @file_put_contents($out_path, $xml);
        if ($written === false) return ['error' => 'Failed to write SVG.', 'success' => false];

        $simple = @simplexml_load_string($xml);
        $valid_xml = $simple !== false;
        $valid_svg = $valid_xml && $simple->getName() === 'svg';

        return ['success' => true, 'filename' => $filename, 'path' => 'storage/agent/workspace/' . $filename, 'size_bytes' => strlen($xml), 'width' => $width, 'height' => $height, 'elements' => count($elements), 'is_valid_svg' => $valid_svg];
    }
}
