<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_text_concordance = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'text_concordance',
    'description' => 'Generate a concordance (word index) from text: lists each word with the line numbers where it appears. Supports case-insensitive mode, stop word filtering, and minimum frequency threshold. Complements text_frequency_counter and text_ngram_analyzer for literary/textual analysis. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'text' => 
        array (
          'type' => 'string',
          'description' => 'The text to analyze',
        ),
        'case_sensitive' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, \'Word\' and \'word\' are distinct entries (default: false)',
        ),
        'stop_words' => 
        array (
          'type' => 'string',
          'description' => 'Optional comma-separated stop words to exclude (e.g. \'the, a, and, of\')',
        ),
        'min_freq' => 
        array (
          'type' => 'integer',
          'description' => 'Minimum frequency to include (default: 1)',
        ),
        'max_entries' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum entries in result (default: 100)',
        ),
      ),
      'required' => 
      array (
        0 => 'text',
      ),
    ),
  ),
);

if (! function_exists('text_concordance')) {
    function text_concordance($text, $case_sensitive = null, $stop_words = null, $min_freq = null, $max_entries = null)
    {
        if (empty($text)) {
            return json_encode(['error' => 'Text is required', 'concordance' => []]);
        }
        $caseSensitive = isset($caseSensitive) ? (bool)$caseSensitive : false;
        $minFreq = isset($min_freq) && $min_freq > 0 ? (int)$min_freq : 1;
        $maxEntries = isset($max_entries) && $max_entries > 0 ? (int)$max_entries : 100;

        // Parse stop words
        $stopList = [];
        if (!empty($stop_words)) {
            $stopList = array_map('trim', explode(',', $stop_words));
            if (!$caseSensitive) {
                $stopList = array_map('mb_strtolower', $stopList);
            }
        }

        // Split into lines
        $lines = preg_split('/\r\n|\r|\n/', $text);
        $wordMap = []; // word => [count, [line_numbers]]

        foreach ($lines as $lineNum => $line) {
            $line = trim($line);
            if (empty($line)) continue;

            // Split into words (alphabetic sequences only)
            preg_match_all('/[a-zA-Z\']+/', $line, $matches);
            $words = $matches[0];

            foreach ($words as $word) {
                $entry = $caseSensitive ? $word : mb_strtolower($word);

                // Skip stop words
                if (in_array($entry, $stopList, true)) continue;
                // Skip very short words
                if (strlen($entry) < 2) continue;

                if (!isset($wordMap[$entry])) {
                    $wordMap[$entry] = ['word' => $word, 'count' => 0, 'lines' => []];
                }
                $wordMap[$entry]['count']++;

                // Record line number (1-indexed) if not already recorded
                $lineIdx = $lineNum + 1;
                if (!in_array($lineIdx, $wordMap[$entry]['lines'])) {
                    $wordMap[$entry]['lines'][] = $lineIdx;
                }
            }
        }

        // Filter by minimum frequency
        $entries = array_filter($wordMap, function($entry) use ($minFreq) {
            return $entry['count'] >= $minFreq;
        });

        // Sort by frequency descending, then alphabetically
        usort($entries, function($a, $b) {
            if ($b['count'] !== $a['count']) return $b['count'] - $a['count'];
            return strcmp($a['word'], $b['word']);
        });

        $entries = array_slice($entries, 0, $maxEntries);

        $totalWords = array_sum(array_column($wordMap, 'count'));
        $uniqueWords = count($wordMap);

        return json_encode([
            'total_words' => $totalWords,
            'unique_words' => $uniqueWords,
            'total_lines' => count($lines),
            'entries_shown' => count($entries),
            'concordance' => $entries,
        ]);
    }
}
