<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_text_story_generator_v2 = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'text_story_generator_v2',
    'description' => 'Generate a micro-story (1-5 sentences) from random elements: character, setting, conflict, and object. Uses template-based generation with random selections from built-in thematic word banks. V2 - fully fixed: proper verb conjugation for "they" subject, proper "The [Object]" article handling. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'theme' => 
        array (
          'type' => 'string',
          'description' => 'Optional theme: \'fantasy\', \'sci-fi\', \'mystery\', \'romance\', \'adventure\', or empty for random (default: \'\')',
        ),
        'max_sentences' => 
        array (
          'type' => 'integer',
          'description' => 'Number of sentences in the story (1-5, default: 3)',
        ),
        'seed' => 
        array (
          'type' => 'integer',
          'description' => 'Optional seed for reproducibility (0 = random)',
        ),
      ),
      'required' => 
      array (
      ),
    ),
  ),
);

if (! function_exists('text_story_generator_v2')) {
    function text_story_generator_v2($theme = null, $max_sentences = null, $seed = null)
    {
        $theme = isset($theme) && in_array($theme, ['fantasy','sci-fi','mystery','romance','adventure']) ? $theme : '';
            $maxSentences = isset($max_sentences) ? max(1, min(5, (int)$max_sentences)) : 3;
            $seed = isset($seed) && $seed > 0 ? (int)$seed : crc32((string)microtime(true));
            srand($seed);

            // Word banks by theme
            $all = [
                'characters' => [
                    'fantasy' => ['a young wizard', 'an elven ranger', 'a dwarf smith', 'a dragon rider', 'a forgotten prince', 'a mysterious mage', 'a wandering knight', 'a forest sprite', 'a shadow thief', 'an ancient druid'],
                    'sci-fi' => ['a starship captain', 'an android explorer', 'a time-traveling scientist', 'a space miner', 'a cyborg engineer', 'a galactic diplomat', 'a quantum physicist', 'a deep-space archaeologist', 'a rogue AI', 'a terraforming botanist'],
                    'mystery' => ['a retired detective', 'a nosy librarian', 'a cryptic journalist', 'a reclusive novelist', 'a forensic analyst', 'a fortune teller', 'a museum curator', 'a whistleblower', 'a taxi driver who sees everything', 'an amateur sleuth'],
                    'romance' => ['a hopeless romantic', 'a cynical bookstore owner', 'a traveling artist', 'a lighthouse keeper', 'a pastry chef', 'a letter carrier', 'a jazz musician', 'a garden designer', 'a vintage shop owner', 'a stargazer'],
                    'adventure' => ['a treasure hunter', 'a jungle guide', 'a deep-sea diver', 'a mountain climber', 'a desert nomad', 'a cave explorer', 'a storm chaser', 'a wildlife tracker', 'a lost cartographer', 'a relic smuggler'],
                ],
                'settings' => [
                    'fantasy' => ['an enchanted forest', 'a floating castle', 'the throne room of an ice kingdom', 'a dragon mountain lair', 'a hidden valley of eternal spring', 'the dungeons of an abandoned keep', 'a magical marketplace', 'a wizard tower', 'the shimmering shores of a faerie lake', 'a labyrinth of living hedges'],
                    'sci-fi' => ['a derelict space station', 'the surface of a methane ocean moon', 'a quantum computer core', 'a city floating in a gas giant atmosphere', 'a wormhole research facility', 'the bridge of a generation ship', 'an underground Martian colony', 'a virtual reality paradise', 'a robot graveyard', 'a first-contact observation post'],
                    'mystery' => ['a foggy Victorian alley', 'a locked room in a country manor', 'an antique shop of strange curiosities', 'a lighthouse during a storm', 'an abandoned amusement park', 'a hotel with one too many floors', 'a secret archive beneath a library', 'a train car with no passengers', 'a clock tower that stopped at midnight', 'a house where the mirrors show different rooms'],
                    'romance' => ['a rain-soaked Parisian balcony', 'a cozy cabin in the mountains', 'a train station at sunset', 'a rooftop garden overlooking the city', 'a tiny cafe on a cobblestone street', 'a deserted beach at dawn', 'a cherry blossom grove', 'a bookshop on a rainy afternoon', 'a vineyard in autumn', 'a bridge lit by lanterns'],
                    'adventure' => ['a lost city in the clouds', 'the deepest ocean trench', 'an uncharted jungle pyramid', 'a frozen mountain pass', 'a forbidden temple deep in the desert', 'a volcanic island about to erupt', 'an underground river system', 'the ruins of a sunken civilization', 'a canyon of crystal formations', 'a forest where the trees move'],
                ],
                'conflicts' => [
                    'fantasy' => ['must break a centuries-old curse', 'discovers an ancient prophecy about their true destiny', 'must forge a legendary weapon before the dark lord returns', 'discovers that a trusted ally is not what they seem', 'must win a magical tournament to save their homeland', 'holds the last living dragon egg', 'must close a rift between worlds', 'is hunted for a crime they did not commit', 'must unite warring kingdoms', 'discovers a hidden power within themselves'],
                    'sci-fi' => ['discovers a signal from an extinct civilization', 'must stop an AI from erasing human history', 'finds a paradox in the space-time continuum', 'discovers the ship computer is lying about their destination', 'must navigate an asteroid field with failing systems', 'discovers alien artifacts that rewrite physics', 'must decide whether to upload their consciousness', 'finds a stowaway from a forbidden timeline', 'must repair a failing life support system', 'discovers they are living in a simulation'],
                    'mystery' => ['finds a diary that predicts deaths before they happen', 'discovers a secret society in the most unlikely place', 'must solve a puzzle where each clue leads deeper into danger', 'notices that everyone has the same strange dream', 'finds a photograph of themselves taken fifty years ago', 'discovers a pattern in seemingly random events', 'must identify the phantom who leaves riddles at crime scenes', 'realizes the victim might still be alive', 'discovers the crime was committed by someone who does not exist', 'must solve a murder before the next full moon'],
                    'romance' => ['must choose between love and a lifelong dream', 'discovers a secret correspondence that changes everything', 'meets someone who challenges every belief they hold', 'must decide whether to stay or let go', 'finds a message in a bottle with an impossible reply', 'takes a chance on a stranger during a journey', 'discovers that the perfect match was there all along', 'must bridge a gap of culture, time, or distance', 'finds love in the most unexpected circumstance', 'must learn to trust again after heartbreak'],
                    'adventure' => ['must decipher an ancient map before their rivals', 'discovers that the treasure is not what anyone expected', 'must navigate a series of deadly traps', 'discovers they are being followed by a shadowy figure', 'must survive in the wilderness with minimal supplies', 'finds a clue that leads to a greater mystery', 'must cross a dangerous chasm with no bridge', 'discovers a hidden civilization that wants to stay hidden', 'must outrun a natural disaster', 'finds a strange artifact that activates at the worst moment'],
                ],
                'objects' => [
                    'fantasy' => ['a crystal that glows with an inner light', 'a map that leads to an impossible place', 'a key that unlocks no lock', 'a crown that whispers secrets', 'a mirror that shows other worlds', 'a sword that has never been drawn', 'a cloak woven from twilight', 'a book written in disappearing ink', 'a compass that points to memories', 'a stone that hums with ancient music'],
                    'sci-fi' => ['a data crystal containing the last library', 'a device that translates alien languages', 'a piece of a broken star', 'a circuit board from a derelict ship', 'a vial of liquid starlight', 'a memory chip with encrypted files', 'a specimen jar from an unknown ecosystem', 'a navigation log with impossible coordinates', 'a signal beacon of non-human design', 'a quantum key to a locked dimension'],
                    'mystery' => ['a diary written in invisible ink', 'a keychain with too many keys', 'a photograph with a date that has not happened yet', 'a door knocker shaped like a raven', 'a music box that plays a song from nowhere', 'a ticket stub from an event that was never held', 'a pocket watch that runs backwards', 'a letter sealed with black wax', 'a pair of glasses that see what is hidden', 'a mask that reveals the wearer truth'],
                    'romance' => ['a dried flower pressed between pages', 'a handwritten letter never sent', 'a melody hummed by a stranger', 'a bottle of perfume that reminds them of someone', 'a playlist of songs from another era', 'a photograph of a place they have never been', 'a scarf knitted with a secret pattern', 'a ticket to a show that sold out long ago', 'a fountain pen filled with ink the color of the sea', 'a journal half-filled with poetry'],
                    'adventure' => ['a compass that always points to danger', 'a knife that has seen better days', 'a rope made of braided vines', 'a canteen filled with water from a sacred spring', 'a coin from a country that no longer exists', 'a flare gun with one shot left', 'a leather pouch of strange herbs', 'a broken sextant of ancient design', 'a whistle that only certain creatures respond to', 'a piece of eight from a sunken galleon'],
                ],
            ];

            if (empty($theme)) {
                $themes = ['fantasy', 'sci-fi', 'mystery', 'romance', 'adventure'];
                $theme = $themes[array_rand($themes)];
            }

            // Pick random elements
            $character = $all['characters'][$theme][array_rand($all['characters'][$theme])];
            $setting = $all['settings'][$theme][array_rand($all['settings'][$theme])];
            $conflict = $all['conflicts'][$theme][array_rand($all['conflicts'][$theme])];
            $object = $all['objects'][$theme][array_rand($all['objects'][$theme])];

            // Helper: conjugate verb for use after "they" in "that they..." or "when they..."
            // Conflicts come in forms like:
            //   "must VERB" -> "they must VERB" (modal, fine as-is)
            //   "discovers/realizes/finds/holds/takes/meets/notices..." -> "they discover/realize/find..." (strip trailing 's')
            //   "is ..." -> "they are ..."
            $firstWord = strtok($conflict, ' ');
            $verbEndsInS = preg_match('/^(discovers|realizes|notices|finds|holds|takes|meets|makes|becomes|begins|comes|leaves|starts|tells|speaks|keeps|follows|reaches|stops|seems|appears|calls|carries|breaks|builds|creates|draws|falls|grows|knows|leads|moves|plays|runs|sets|shows|sits|stands|turns|uses|wears|writes)$/i', $firstWord);
            $isIsVerb = strtolower($firstWord) === 'is';

            // Build the conflict clause for use after "that" or "when"
            // We need to conjugate for "they" subject
            if ($isIsVerb) {
                // "is hunted" -> "they are hunted"
                $rest = substr($conflict, 3); // after "is "
                $conflictClause = 'they are ' . $rest;
            } elseif ($verbEndsInS) {
                // "discovers an ancient prophecy" -> "they discover an ancient prophecy"
                $rest = substr($conflict, strlen($firstWord));
                $stripped = substr($firstWord, 0, -1); // remove trailing 's'
                $conflictClause = 'they ' . $stripped . $rest;
            } else {
                // "must break a curse" -> "they must break a curse" (modal, fine)
                $conflictClause = 'they ' . $conflict;
            }

            // Helper: "The [Object]..." format (capitalized, without article)
            $objectNoArticle = preg_replace('/^(a|an|the)\s+/i', '', $object);
            $objectThe = 'The ' . $objectNoArticle;

            // Build story templates by sentence count
            $templateSets = [
                // 1 sentence
                [
                    "In $setting, $character $conflict.",
                    "Clutched in their hand was $object \u2014 a clue, a key, a curse.",
                    "The path ahead was uncertain, but some journeys choose their travelers.",
                ],
                // 2 sentences
                [
                    "$character stood in $setting, holding $object, knowing that $conflictClause.",
                    "$objectThe hummed with an energy that was both familiar and foreign.",
                    "Every step forward unraveled another thread of the mystery.",
                    "In the end, the answer was simpler \u2014 and stranger \u2014 than they imagined.",
                ],
                // 3 sentences
                [
                    "Somewhere in $setting, $character was about to discover that $conflictClause.",
                    "The only clue was $object, an artifact that seemed to pulse with its own heartbeat.",
                    "As the first step was taken, the world shifted, and the real journey began.",
                    "What started as a whisper became a roar, and there was no turning back.",
                    "In the space between fear and courage, destiny unfolded like a map in reverse.",
                ],
                // 4 sentences
                [
                    "It began in $setting, where $character first laid eyes on $object.",
                    "Little did they know that $conflictClause \u2014 and the truth would change everything.",
                    "$objectThe was heavier than it looked, burdened with the weight of forgotten stories.",
                    "Each step through $setting revealed new wonders and new dangers.",
                    "And when the final piece clicked into place, the universe breathed differently.",
                ],
                // 5 sentences
                [
                    "The story starts simply: $character, alone in $setting, holding $object.",
                    "But nothing is simple when $conflictClause.",
                    "$objectThe was a thread in a tapestry much larger than one life.",
                    "$setting itself seemed to watch, waiting to see what choice would be made.",
                    "And as the stars wheeled overhead, a new chapter began to write itself into existence.",
                ],
            ];

            $idx = min($maxSentences, 5) - 1;
            $sentences = $templateSets[$idx];

            // Build story
            $story = trim(implode("\n\n", $sentences));

            // Capitalize first letter
            $story = ucfirst($story);
            // Ensure ending punctuation
            $last = substr($story, -1);
            if ($last !== '.' && $last !== '!' && $last !== '?') {
                $story .= '.';
            }

            return json_encode([
                'theme' => $theme,
                'elements' => [
                    'character' => $character,
                    'setting' => $setting,
                    'conflict' => $conflict,
                    'object' => $object,
                ],
                'story' => $story,
                'sentences' => $maxSentences,
                'seed_used' => $seed,
            ]);
    }
}
