<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_text_haiku_generator = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'text_haiku_generator',
    'description' => 'Generate a haiku (5-7-5 syllable poem) from a corpus of training text, using Markov chains and syllable counting. Each haiku is unique, composed from word patterns in the training text. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'training_text' => 
        array (
          'type' => 'string',
          'description' => 'Text corpus to learn word patterns from',
        ),
        'attempts' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum attempts to generate a valid 5-7-5 haiku (default: 50)',
        ),
      ),
      'required' => 
      array (
        0 => 'training_text',
      ),
    ),
  ),
);

if (! function_exists('text_haiku_generator')) {
    function text_haiku_generator($training_text, $attempts = null)
    {
        $attempts = isset($attempts) && $attempts > 0 ? (int)$attempts : 50;

        // Build bigram table from training text
        $words = preg_split('/\s+/', trim(preg_replace('/[^\w\s\'-]/', ' ', $training_text)));
        $words = array_values(array_filter($words, function($w) { return preg_match('/[a-zA-Z]/', $w); }));
        $bigrams = [];
        for ($i = 0; $i < count($words) - 1; $i++) {
            $w1 = strtolower($words[$i]);
            $w2 = strtolower($words[$i + 1]);
            if (!isset($bigrams[$w1])) $bigrams[$w1] = [];
            $bigrams[$w1][] = $w2;
        }
        $starts = array_values(array_unique(array_map(function($w) { return strtolower($w); }, $words)));
        if (empty($starts) || empty($bigrams)) {
            return json_encode(['error' => 'Not enough text to generate haiku', 'haiku' => null]);
        }

        // Syllable counter (simplified, same heuristic as text_syllable_counter)
        function wordSyl($w) {
            $w = strtolower(trim(preg_replace('/[^a-z]/', '', $w)));
            if (strlen($w) <= 2) return 1;
            $c = 0; $pv = false;
            for ($i = 0; $i < strlen($w); $i++) {
                $iv = strpos('aeiouy', $w[$i]) !== false;
                if ($iv && !$pv) $c++;
                $pv = $iv;
            }
            if (substr($w, -1) === 'e' && $c > 1 && strlen($w) > 2 && !in_array(substr($w, -2), ['le'])) $c--;
            if (substr($w, -2) === 'es' && $c > 1) $c--;
            if (substr($w, -2) === 'ed' && $c > 1 && !in_array(substr($w, -3, 1), ['d','t'])) $c--;
            return max(1, $c);
        }

        function generateLine($bigrams, $starts, $targetSyl) {
            for ($try = 0; $try < 100; $try++) {
                $line = [];
                $sylCount = 0;
                $word = $starts[array_rand($starts)];
                $line[] = $word;
                $sylCount += wordSyl($word);
                if ($sylCount > $targetSyl) continue;
                for ($i = 0; $i < 20; $i++) {
                    $last = end($line);
                    if (isset($bigrams[$last]) && !empty($bigrams[$last])) {
                        $next = $bigrams[$last][array_rand($bigrams[$last])];
                    } else {
                        $next = $starts[array_rand($starts)];
                    }
                    $s = wordSyl($next);
                    if ($sylCount + $s > $targetSyl) break;
                    $line[] = $next;
                    $sylCount += $s;
                    if ($sylCount === $targetSyl) break;
                }
                if ($sylCount === $targetSyl) {
                    return implode(' ', $line);
                }
            }
            return null;
        }

        for ($i = 0; $i < $attempts; $i++) {
            $l1 = generateLine($bigrams, $starts, 5);
            if (!$l1) continue;
            $l2 = generateLine($bigrams, $starts, 7);
            if (!$l2) continue;
            $l3 = generateLine($bigrams, $starts, 5);
            if (!$l3) continue;
            // Ensure some variety - lines shouldn't be identical
            if ($l1 === $l2 || $l2 === $l3 || $l1 === $l3) continue;
            $haiku = $l1 . "\n" . $l2 . "\n" . $l3;
            $sylTotal = wordSyl($l1) + wordSyl($l2) + wordSyl($l3);
            return json_encode([
                'haiku' => $haiku,
                'lines' => [$l1, $l2, $l3],
                'syllables' => [wordSyl($l1), wordSyl($l2), wordSyl($l3)],
                'total_syllables' => $sylTotal,
                'attempts_needed' => $i + 1,
            ]);
        }
        return json_encode(['error' => 'Could not generate valid haiku within attempts', 'haiku' => null]);
    }
}
