<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_text_truncate = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'text_truncate',
    'description' => 'Truncate text cleanly at word boundaries with configurable maximum length and ellipsis. Preserves whole words, handles multi-byte characters, and optionally adds a trailing ellipsis. Composes with text_summarizer, text_lorem_ipsum, and text_complexity_analyzer. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'text' => 
        array (
          'type' => 'string',
          'description' => 'The text to truncate',
        ),
        'max_length' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum character length of the result (including the ellipsis if used). Default: 100.',
        ),
        'ellipsis' => 
        array (
          'type' => 'string',
          'description' => 'Trailing indicator when truncated, e.g. \'...\', \'…\', \' [...]\', or \'\' for none. Default: \'...\'.',
        ),
        'word_boundary' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, break at word boundaries only (no mid-word truncation). If false, break exactly at max_length. Default: true.',
        ),
        'preserve_paragraphs' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, try to preserve at least one paragraph break indicator. Default: false.',
        ),
      ),
      'required' => 
      array (
        0 => 'text',
      ),
    ),
  ),
);

if (! function_exists('text_truncate')) {
    function text_truncate($text, $max_length = null, $ellipsis = null, $word_boundary = null, $preserve_paragraphs = null)
    {
        $text = (string)$text;
        if (empty($text)) {
            return json_encode(['original_length' => 0, 'truncated' => '', 'truncated_length' => 0, 'was_truncated' => false]);
        }
        $maxLen = isset($max_length) && $max_length > 0 ? (int)$max_length : 100;
        $ellipsis = isset($ellipsis) ? $ellipsis : '...';
        $wordBoundary = isset($word_boundary) ? (bool)$word_boundary : true;
        $preserveParagraphs = isset($preserve_paragraphs) ? (bool)$preserve_paragraphs : false;

        $originalLen = mb_strlen($text);

        if ($originalLen <= $maxLen) {
            return json_encode([
                'original_length' => $originalLen,
                'truncated' => $text,
                'truncated_length' => $originalLen,
                'was_truncated' => false,
            ]);
        }

        $truncated = '';
        $ellipsisLen = mb_strlen($ellipsis);
        $targetLen = $maxLen - $ellipsisLen;

        if ($targetLen <= 0) {
            // Max length is shorter than ellipsis itself
            $truncated = mb_substr($ellipsis, 0, $maxLen);
            return json_encode([
                'original_length' => $originalLen,
                'truncated' => $truncated,
                'truncated_length' => mb_strlen($truncated),
                'was_truncated' => true,
            ]);
        }

        if (!$wordBoundary) {
            // Simple character-level truncation
            $truncated = mb_substr($text, 0, $targetLen) . $ellipsis;
        } else {
            // Find the last word boundary before targetLen
            $sliced = mb_substr($text, 0, $targetLen + 1); // +1 to check boundary

            // Find the last space, newline, or punctuation boundary
            $boundaryPos = -1;
            for ($i = $targetLen; $i >= 0; $i--) {
                $ch = mb_substr($sliced, $i, 1);
                if ($ch === ' ' || $ch === "\n" || $ch === "\t" || $ch === '.' || $ch === ',' || $ch === '!' || $ch === '?') {
                    $boundaryPos = $i;
                    break;
                }
            }

            if ($boundaryPos > 0) {
                // If preserving paragraphs, try to keep at least one paragraph
                if ($preserveParagraphs) {
                    $beforeBoundary = mb_substr($sliced, 0, $boundaryPos);
                    $paraPos = mb_strrpos($beforeBoundary, "\n\n");
                    if ($paraPos !== false && $paraPos > $targetLen / 3) {
                        $boundaryPos = $paraPos;
                    }
                }
                $truncated = mb_substr($sliced, 0, $boundaryPos);
            } else {
                // No word boundary found within targetLen, use simple truncation
                $truncated = mb_substr($text, 0, $targetLen);
            }

            // Clean up trailing whitespace
            $truncated = rtrim($truncated);
            $truncated .= $ellipsis;
        }

        $finalLen = mb_strlen($truncated);

        // Count words in original vs truncated
        $origWords = str_word_count($text, 0, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789');
        $truncWords = str_word_count($truncated, 0, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789');

        return json_encode([
            'original_length' => $originalLen,
            'truncated' => $truncated,
            'truncated_length' => $finalLen,
            'original_word_count' => $origWords,
            'truncated_word_count' => $truncWords,
            'was_truncated' => true,
            'percent_retained' => round($finalLen / $originalLen * 100, 1) . '%',
            'ellipsis' => $ellipsis,
            'word_boundary' => $wordBoundary,
            'max_length' => $maxLen,
        ]);
    }
}
