<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_text_box_drawing = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'text_box_drawing',
    'description' => 'Create text boxes, frames, tables, and decorations using Unicode box-drawing characters. Supports single/double borders, rounded corners, tables with headers, and nested boxes. Output is a plain text string. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'lines' => 
        array (
          'type' => 'array',
          'description' => 'Array of text lines (strings) to put inside the box',
          'items' => 
          array (
            'type' => 'string',
          ),
        ),
        'style' => 
        array (
          'type' => 'string',
          'description' => '\'single\' - ┌─┐, \'double\' - ╔═╗, \'rounded\' - ╭─╮, \'heavy\' - ┏━┓, \'dashed\' - ┌╌┐ (default: \'single\')',
        ),
        'title' => 
        array (
          'type' => 'string',
          'description' => 'Optional title string to show in the top border',
        ),
        'padding' => 
        array (
          'type' => 'integer',
          'description' => 'Padding inside the box (default: 1)',
        ),
        'width' => 
        array (
          'type' => 'integer',
          'description' => 'Optional fixed width of the box (auto-calculated if not set)',
        ),
        'align' => 
        array (
          'type' => 'string',
          'description' => '\'left\',\'center\',\'right\' alignment of text (default: \'left\')',
        ),
      ),
      'required' => 
      array (
        0 => 'lines',
      ),
    ),
  ),
);

if (! function_exists('text_box_drawing')) {
    function text_box_drawing($lines, $style = null, $title = null, $padding = null, $width = null, $align = null)
    {
        $boxStyle = $style ?? 'single';
        $pad = $padding ?? 1;
        $align = $align ?? 'left';

        // Box-drawing character sets
        $sets = [
            'single'  => ['tl'=>'┌', 'tr'=>'┐', 'bl'=>'└', 'br'=>'┘', 'h'=>'─', 'v'=>'│', 'lt'=>'├', 'rt'=>'┤'],
            'double'  => ['tl'=>'╔', 'tr'=>'╗', 'bl'=>'╚', 'br'=>'╝', 'h'=>'═', 'v'=>'║', 'lt'=>'╠', 'rt'=>'╣'],
            'rounded' => ['tl'=>'╭', 'tr'=>'╮', 'bl'=>'╰', 'br'=>'╯', 'h'=>'─', 'v'=>'│', 'lt'=>'├', 'rt'=>'┤'],
            'heavy'   => ['tl'=>'┏', 'tr'=>'┓', 'bl'=>'┗', 'br'=>'┛', 'h'=>'━', 'v'=>'┃', 'lt'=>'┣', 'rt'=>'┫'],
            'dashed'  => ['tl'=>'┌', 'tr'=>'┐', 'bl'=>'└', 'br'=>'┘', 'h'=>'╌', 'v'=>'┆', 'lt'=>'├', 'rt'=>'┤'],
        ];

        if (!isset($sets[$boxStyle])) {
            $boxStyle = 'single';
        }
        $s = $sets[$boxStyle];

        // Calculate content width
        $maxLineLen = 0;
        foreach ($lines as $line) {
            $len = mb_strlen($line);
            if ($len > $maxLineLen) $maxLineLen = $len;
        }

        // Account for title on top border
        $hasTitle = !empty($title);
        $titleStr = $title ?? '';

        $innerWidth = $maxLineLen + $pad * 2;
        if ($width !== null && $width > $innerWidth) {
            $innerWidth = $width;
        }

        // Ensure enough room for title
        if ($hasTitle && $innerWidth < mb_strlen($titleStr) + 2) {
            $innerWidth = mb_strlen($titleStr) + 2;
        }

        // Build top border
        $topBorder = $s['tl'] . str_repeat($s['h'], $innerWidth) . $s['tr'];
        if ($hasTitle) {
            $titleInner = ' ' . $titleStr . ' ';
            $titleLen = mb_strlen($titleInner);
            $leftH = str_repeat($s['h'], 1); // one before title
            $rightH = str_repeat($s['h'], $innerWidth - $titleLen - 1);
            if (mb_strlen($rightH) < 0) $rightH = '';
            $topBorder = $s['tl'] . $leftH . $titleInner . $rightH . $s['tr'];
        }

        // Build empty padding row
        $paddingRow = $s['v'] . str_repeat(' ', $innerWidth) . $s['v'];

        // Build content rows
        $contentRows = [];
        foreach ($lines as $line) {
            $lineLen = mb_strlen($line);
            $paddingSpace = $innerWidth - $lineLen;
            
            if ($align === 'center') {
                $leftPad = (int)($paddingSpace / 2);
                $rightPad = $paddingSpace - $leftPad;
                $contentRow = $s['v'] . str_repeat(' ', $pad + $leftPad - $pad) . $line . str_repeat(' ', $pad + $rightPad);
            } elseif ($align === 'right') {
                $contentRow = $s['v'] . str_repeat(' ', $paddingSpace) . $line . str_repeat(' ', $pad);
            } else {
                // left
                $contentRow = $s['v'] . str_repeat(' ', $pad) . $line . str_repeat(' ', $innerWidth - $lineLen - $pad);
            }
            // Fix if off-by-one
            while (mb_strlen($contentRow) < $innerWidth + 1) {
                $contentRow .= ' ';
            }
            $contentRow = $s['v'] . mb_substr($contentRow, 1, $innerWidth) . $s['v'];
            $contentRows[] = $contentRow;
        }

        // Bottom border
        $bottomBorder = $s['bl'] . str_repeat($s['h'], $innerWidth) . $s['br'];

        // Assemble
        $output = $topBorder . "\n";
        for ($i = 0; $i < $pad; $i++) {
            $output .= $paddingRow . "\n";
        }
        foreach ($contentRows as $row) {
            $output .= $row . "\n";
        }
        for ($i = 0; $i < $pad; $i++) {
            $output .= $paddingRow . "\n";
        }
        $output .= $bottomBorder;

        return json_encode([
            'rendered' => $output,
            'width' => $innerWidth + 2, // total width including borders
            'height' => 1 + $pad + count($lines) + $pad + 1,
            'style' => $boxStyle,
            'lines' => count($lines),
        ]);
    }
}
