<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_text_lorem_ipsum = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'text_lorem_ipsum',
    'description' => 'Generate Lorem Ipsum placeholder text with configurable paragraphs, sentences per paragraph, and words per sentence. Useful for testing text tools (text_summarizer, text_complexity_analyzer, text_frequency_counter, etc.). Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'paragraphs' => 
        array (
          'type' => 'integer',
          'description' => 'Number of paragraphs to generate (1-20, default: 3)',
        ),
        'sentences_per_paragraph' => 
        array (
          'type' => 'integer',
          'description' => 'Sentences per paragraph (1-10, default: 5)',
        ),
        'words_per_sentence' => 
        array (
          'type' => 'integer',
          'description' => 'Approximate words per sentence (3-20, default: 8)',
        ),
        'start_with_classic' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, start with \'Lorem ipsum dolor sit amet...\' (default: true)',
        ),
      ),
      'required' => 
      array (
      ),
    ),
  ),
);

if (! function_exists('text_lorem_ipsum')) {
    function text_lorem_ipsum($paragraphs = null, $sentences_per_paragraph = null, $words_per_sentence = null, $start_with_classic = null)
    {
        $paras = max(1, min(20, $paragraphs ?? 3));
        $sentPerPara = max(1, min(10, $sentences_per_paragraph ?? 5));
        $wordsPerSent = max(3, min(20, $words_per_sentence ?? 8));
        $classic = $start_with_classic ?? true;

        $loremWords = ['lorem','ipsum','dolor','sit','amet','consectetur','adipiscing','elit','sed','do','eiusmod','tempor','incididunt','ut','labore','et','dolore','magna','aliqua','enim','ad','minim','veniam','quis','nostrud','exercitation','ullamco','laboris','nisi','aliquip','ex','ea','commodo','consequat','duis','aute','irure','dolor','in','reprehenderit','voluptate','velit','esse','cillum','eu','fugiat','nulla','pariatur','excepteur','sint','occaecat','cupidatat','non','proident','sunt','culpa','qui','officia','deserunt','mollit','anim','id','est','laborum','fusce','nec','tellus','sed','augue','semper','porta','mauris','massa','vestibulum','lacinia','arcu','eget','nullam','tincidunt','purus','in','magna','lectus','lobortis','facilisis','bibendum','neque','donec','aliquet','libero','vivamus','justo','feugiat','placerat','vel','venenatis','iaculis','malesuada','cras','metus','donec','vitae','erat','quis','leo','ultricies','hendrerit','aenean','facilisi','phasellus','gravida','dapibus','tellus','maecenas','convallis','nisl','sed','porttitor','ligula','risus','at','auctor','urna','vitae','nunc','sed','pede','pretium','mi','ac','varius','quam','consectetur','ut','mattis','purus','in','luctus','tortor'];

        $capitalize = function($w) { return ucfirst($w); };

        $sentences = [];
        if ($classic) {
            $sentences[] = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.';
            $sentences[] = 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.';
            $sentences[] = 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.';
            $sentences[] = 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';
        }

        // Generate additional random sentences
        $totalSents = $paras * $sentPerPara;
        $seed = crc32(serialize([$paras, $sentPerPara, $wordsPerSent]));
        srand($seed); // Deterministic output

        while (count($sentences) < $totalSents) {
            $wordCount = $wordsPerSent + rand(-2, 2);
            $wordCount = max(3, $wordCount);
            $sentenceWords = [];
            $used = [];
            for ($i = 0; $i < $wordCount; $i++) {
                $idx = array_rand($loremWords);
                $word = $loremWords[$idx];
                // Avoid immediate repetition
                if ($i > 0 && $word === $sentenceWords[$i-1]) {
                    $idx = array_rand($loremWords);
                    $word = $loremWords[$idx];
                }
                $sentenceWords[] = $word;
            }
            $sentenceWords[0] = $capitalize($sentenceWords[0]);
            $sentences[] = implode(' ', $sentenceWords) . '.';
        }

        $output = '';
        for ($p = 0; $p < $paras; $p++) {
            $paraSents = array_slice($sentences, $p * $sentPerPara, $sentPerPara);
            $output .= '  ' . implode(' ', $paraSents) . "\n\n";
        }

        return json_encode([
            'paragraphs' => $paras,
            'sentences_per_paragraph' => $sentPerPara,
            'total_sentences' => count($sentences),
            'total_words' => str_word_count($output),
            'text' => trim($output),
        ]);
    }
}
