<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_text_character_analyzer = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'text_character_analyzer',
    'description' => 'Analyze the character composition of text: count uppercase, lowercase, digits, spaces, punctuation, and other characters. Returns counts, percentages, and a visual composition bar. Useful for password strength estimation, text profiling, and data quality checks. Composes with string_count, text_complexity_analyzer, and text_case_convert. Pure function, no side effects.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'text' => 
        array (
          'type' => 'string',
          'description' => 'The text to analyze',
        ),
      ),
      'required' => 
      array (
        0 => 'text',
      ),
    ),
  ),
);

if (! function_exists('text_character_analyzer')) {
    function text_character_analyzer($text)
    {
        $text = (string)$text;
        if (empty($text)) {
            return json_encode(['error' => 'Text is required', 'length' => 0]);
        }
        $len = mb_strlen($text);

        $upper = 0; $lower = 0; $digits = 0; $spaces = 0;
        $punctuation = 0; $other = 0;

        for ($i = 0; $i < $len; $i++) {
            $ch = mb_substr($text, $i, 1);
            if (ctype_upper($ch)) {
                $upper++;
            } elseif (ctype_lower($ch)) {
                $lower++;
            } elseif (ctype_digit($ch)) {
                $digits++;
            } elseif ($ch === ' ' || $ch === "\t" || $ch === "\n" || $ch === "\r") {
                $spaces++;
            } elseif (ctype_punct($ch) || preg_match('/[.,!?;:\'\"()\[\]{}<>\/\\\\\-=_+`~@#$%^&*|]/', $ch)) {
                $punctuation++;
            } else {
                $other++;
            }
        }

        $totalGraphic = $len - $spaces; // non-space characters

        // Visual composition bar (10 chars wide)
        $barLen = 10;
        $upperBars = round($upper / max(1, $len) * $barLen);
        $lowerBars = round($lower / max(1, $len) * $barLen);
        $digitBars = round($digits / max(1, $len) * $barLen);
        $spaceBars = round($spaces / max(1, $len) * $barLen);
        $punctBars = round($punctuation / max(1, $len) * $barLen);
        $otherBars = $barLen - ($upperBars + $lowerBars + $digitBars + $spaceBars + $punctBars);
        if ($otherBars < 0) $otherBars = 0;

        $bar = '';
        $bar .= str_repeat('A', $upperBars);
        $bar .= str_repeat('a', $lowerBars);
        $bar .= str_repeat('0', $digitBars);
        $bar .= str_repeat('_', $spaceBars);
        $bar .= str_repeat('.', $punctBars);
        $bar .= str_repeat('?', $otherBars);

        // Entropy estimation (simple character-level)
        $probs = [];
        $categories = ['upper' => $upper, 'lower' => $lower, 'digits' => $digits, 'spaces' => $spaces, 'punct' => $punctuation, 'other' => $other];
        $entropy = 0;
        foreach ($categories as $count) {
            if ($count > 0) {
                $p = $count / $len;
                $entropy -= $p * log($p) / log(2);
            }
        }

        $pct = function($n) use ($len) { return $len > 0 ? round($n / $len * 100, 1) : 0; };

        return json_encode([
            'length' => $len,
            'composition' => [
                'uppercase' => ['count' => $upper, 'percentage' => $pct($upper)],
                'lowercase' => ['count' => $lower, 'percentage' => $pct($lower)],
                'digits' => ['count' => $digits, 'percentage' => $pct($digits)],
                'spaces' => ['count' => $spaces, 'percentage' => $pct($spaces)],
                'punctuation' => ['count' => $punctuation, 'percentage' => $pct($punctuation)],
                'other' => ['count' => $other, 'percentage' => $pct($other)],
            ],
            'non_space_characters' => $totalGraphic,
            'composition_entropy' => round($entropy, 4),
            'visual_bar' => $bar . '  (A=upper a=lower 0=digit _=space .=punct ?=other)',
            'legend' => 'A=Uppercase  a=Lowercase  0=Digits  _=Spaces  .=Punctuation  ?=Other',
            'next_steps' => [
                'Feed to string_count for word/line counts.',
                'Use with text_complexity_analyzer for readability.',
                'High entropy suggests diverse character usage (e.g., strong passwords).',
            ],
        ]);
    }
}
