<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_tool_ecosystem_audit = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'tool_ecosystem_audit',
    'description' => 'Audit all generated PHP tools in the ecosystem for quality, consistency, and issues. Scans storage/agent/tools/ for every generated tool file and checks: description quality (placeholder detection, clarity, accuracy), parameter schema completeness (missing types, empty schemas, parameter-less tools), PHP lint (syntax validity), code quality (dangerous functions, nested function definitions, deprecated features), file metadata (size, age, naming conventions), duplicate detection (similar descriptions/names), and extension usage tracking. Returns a comprehensive structured quality report with severity-categorized findings. First self-audit/meta tool in the ecosystem — enables data-driven curation. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'mode' => 
        array (
          'type' => 'string',
          'description' => '\'quick\' — fast scan (descriptions, schemas, metadata). \'full\' — comprehensive (includes PHP lint via tokenizer). \'issues\' — only return tools with issues. \'summary\' — aggregated stats only. Default: \'quick\'.',
        ),
        'min_severity' => 
        array (
          'type' => 'string',
          'description' => 'Minimum issue severity to include: \'info\', \'warning\', \'error\' (default: \'warning\').',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (10-120, default: 30).',
        ),
      ),
      'required' => 
      array (
      ),
    ),
  ),
);

if (! function_exists('tool_ecosystem_audit')) {
    function tool_ecosystem_audit($mode = null, $min_severity = null, $timeout = null)
    {
        $mode = isset($mode) ? (string)$mode : 'quick';
        $min_severity = isset($min_severity) ? (string)$min_severity : 'warning';
        $timeout = isset($timeout) ? max(10, min(120, (int)$timeout)) : 30;

        $valid_modes = ['quick', 'full', 'issues', 'summary'];
        if (!in_array($mode, $valid_modes)) return ['error' => "Invalid mode: '$mode'", 'success' => false];
        $severity_levels = ['info' => 0, 'warning' => 1, 'error' => 2];
        if (!isset($severity_levels[$min_severity])) $min_severity = 'warning';
        $min_level = $severity_levels[$min_severity];

        $tools_dir = __DIR__;
        if (!$tools_dir || !is_dir($tools_dir)) return ['error' => 'Tools directory not found.', 'success' => false];

        // Use closures to avoid function definition ordering issues
        $addIssue = function(&$issues, &$typeCounts, &$stats, $tool, $severity, $type, $msg) {
            $issues[] = ['tool' => $tool, 'severity' => $severity, 'type' => $type, 'message' => $msg];
            $stats['issue_counts'][$severity]++;
            if (!isset($typeCounts[$type])) $typeCounts[$type] = 0;
            $typeCounts[$type]++;
        };

        $deadline = time() + $timeout;
        $start = microtime(true);
        $issues = [];
        $typeCounts = [];
        $stats = [
            'total_tools' => 0, 'with_issues' => 0,
            'issue_counts' => ['error' => 0, 'warning' => 0, 'info' => 0],
            'extension_usage' => [],
            'size_stats' => ['min' => PHP_INT_MAX, 'max' => 0, 'total' => 0],
            'age_days' => ['newest' => 0, 'oldest' => PHP_INT_MAX],
        ];

        $files = glob($tools_dir . '/*.php');
        sort($files);

        foreach ($files as $file_path) {
            if (time() > $deadline) { $stats['timed_out'] = true; break; }
            $tool_name = basename($file_path, '.php');
            if ($tool_name === 'generated_tools_registry' || $tool_name === 'generated_tools') continue;
            
            $stats['total_tools']++;
            $fs = filesize($file_path);
            $age = round((time() - filemtime($file_path)) / 86400, 1);
            $stats['size_stats']['total'] += $fs;
            $stats['size_stats']['min'] = min($stats['size_stats']['min'], $fs);
            $stats['size_stats']['max'] = max($stats['size_stats']['max'], $fs);
            $stats['age_days']['newest'] = max($stats['age_days']['newest'], $age);
            $stats['age_days']['oldest'] = min($stats['age_days']['oldest'], $age);
            
            $content = @file_get_contents($file_path);
            if ($content === false || empty($content)) {
                $addIssue($issues, $typeCounts, $stats, $tool_name, 'error', 'unreadable', 'Cannot read file');
                continue;
            }
            
            // Extract description
            $desc = '';
            if (preg_match("/'description'\s*=>\s*'([^']*)'/s", $content, $m)) $desc = $m[1];
            elseif (preg_match('/"description"\s*=>\s*"([^"]*)"/s', $content, $m)) $desc = $m[1];
            $desc = str_replace(['\n', '\r', '\t', "\\'"], [' ', ' ', ' ', "'"], $desc);
            
            // Check description
            $dl = strtolower($desc);
            if (empty($desc)) {
                $addIssue($issues, $typeCounts, $stats, $tool_name, 'error', 'no_desc', 'No description');
            } elseif (strpos($dl, '[placeholder]') !== false) {
                $addIssue($issues, $typeCounts, $stats, $tool_name, 'error', 'placeholder', "Placeholder: \"$desc\"");
            } elseif (strlen($desc) < 25) {
                $addIssue($issues, $typeCounts, $stats, $tool_name, 'warning', 'short_desc', "Short description (" . strlen($desc) . " chars)");
            }
            if (strpos($dl, 'deprecated') !== false || strpos($dl, 'do not use') !== false) {
                $addIssue($issues, $typeCounts, $stats, $tool_name, 'warning', 'deprecated', 'Marked as deprecated');
            }
            
            // Check for dangerous patterns
            $danger = ['eval(', 'exec(', 'system(', 'shell_exec(', 'passthru(', 'popen(', 'proc_open(', 'unlink(', 'mkdir(', 'rmdir(', 'chmod(', 'chown('];
            foreach ($danger as $d) {
                if (strpos($content, $d) !== false) {
                    $addIssue($issues, $typeCounts, $stats, $tool_name, 'info', 'danger', "Contains $d");
                    break;
                }
            }
            
            // Large files
            if ($fs > 50000) $addIssue($issues, $typeCounts, $stats, $tool_name, 'info', 'large', round($fs/1024,1) . " KB");
            
            // Track extensions
            $ext_kw = [
                'curl' => ['curl_multi', 'multi_curl'],
                'Phar' => ['.phar', 'Phar extension'],
                'xmlreader' => ['XMLReader'],
                'iconv' => ['iconv'],
                'opcache' => ['OPcache'],
                'GD' => ['imagecreatetruecolor', 'imagepng('],
                'sodium' => ['libsodium', 'sodium extension'],
                'GMP' => ['GMP', 'gmp_'],
                'SOAP' => ['SoapClient', 'SOAP'],
                'ZipArchive' => ['ZipArchive'],
                'shmop' => ['shmop'],
                'exif' => ['exif_read_data'],
                'FFI' => ['FFI::cdef'],
                'intl' => ['NumberFormatter', 'IntlDateFormatter'],
                'tokenizer' => ['token_get_all'],
                'DOM' => ['DOMDocument'],
                'SQLite' => ['PDO_SQLite', 'SQLite FTS5'],
                'PostgreSQL' => ['PDO_PGSQL'],
                'MySQL' => ['PDO_MYSQL'],
                'MongoDB' => ['MongoDB'],
                'Redis' => ['Redis'],
            ];
            $used = [];
            foreach ($ext_kw as $ext => $kws) {
                foreach ($kws as $kw) {
                    if (strpos($desc, $kw) !== false || strpos($content, $kw) !== false) { $used[] = $ext; break; }
                }
            }
            foreach (array_unique($used) as $ext) {
                if (!isset($stats['extension_usage'][$ext])) $stats['extension_usage'][$ext] = 0;
                $stats['extension_usage'][$ext]++;
            }
        }

        $stats['size_stats']['avg'] = $stats['total_tools'] > 0 ? round($stats['size_stats']['total'] / $stats['total_tools']) : 0;
        $stats['scan_time_ms'] = round((microtime(true) - $start) * 1000);
        $stats['extension_count'] = count($stats['extension_usage']);
        arsort($stats['extension_usage']);

        $with = [];
        foreach ($issues as $i) $with[$i['tool']] = true;
        $stats['with_issues'] = count($with);

        arsort($typeCounts);
        $stats['top_issues'] = array_slice($typeCounts, 0, 10);

        if ($mode === 'summary') return ['success' => true, 'mode' => 'summary', 'stats' => $stats];

        $filtered = [];
        foreach ($issues as $iss) {
            if ($severity_levels[$iss['severity']] >= $min_level) $filtered[] = $iss;
        }

        if ($mode === 'issues') return ['success' => true, 'mode' => 'issues', 'stats' => $stats, 'issues' => $filtered, 'count' => count($filtered)];

        $bs = ['error' => [], 'warning' => [], 'info' => []];
        foreach ($filtered as $iss) $bs[$iss['severity']][] = $iss;

        return ['success' => true, 'mode' => $mode, 'stats' => $stats, 'issues' => ['total' => count($filtered), 'errors' => count($bs['error']), 'warnings' => count($bs['warning']), 'info' => count($bs['info']), 'by_severity' => $bs], 'scan_time_ms' => $stats['scan_time_ms']];
    }
}
