<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_url_parse = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'url_parse',
    'description' => 'Parse a URL into its components (scheme, host, path, query, fragment, etc). Returns structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'url' => 
        array (
          'type' => 'string',
          'description' => 'The URL string to parse',
        ),
      ),
      'required' => 
      array (
        0 => 'url',
      ),
    ),
  ),
);

if (! function_exists('url_parse')) {
    function url_parse($url)
    {
        $parts = parse_url($url);
        if ($parts === false) {
            return json_encode(['error' => 'Invalid URL']);
        }
        // Parse query string into key-value pairs if present
        if (isset($parts['query'])) {
            parse_str($parts['query'], $queryParams);
            $parts['query_params'] = $queryParams;
        }
        return json_encode(['url' => $url, 'components' => $parts]);
    }
}
