<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_wav_validator = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'wav_validator',
    'description' => 'Validate WAV audio files in the workspace. Reads RIFF/WAV header structure: checks \'RIFF\' magic, \'WAVE\' format, \'fmt \' and \'data\' chunks, sample rate, bit depth, channels, and data size consistency. Reports which files are valid WAVs and which are corrupt. Pure PHP, no shell. Never throws.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'path' => 
        array (
          'type' => 'string',
          'description' => 'Path to a single .wav file, or a directory to scan all .wav files. Default: storage/agent/workspace.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (1-10, default: 5).',
        ),
      ),
      'required' => 
      array (
      ),
    ),
  ),
);

if (! function_exists('wav_validator')) {
    function wav_validator($path = null, $timeout = null)
    {
        $path = $path ?? getcwd() . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'agent' . DIRECTORY_SEPARATOR . 'workspace';
        $timeout = $timeout ?? 5;
        $timeout = max(1, min(10, $timeout));
        $start = microtime(true);

        // Normalize path
        $prefix = getcwd() . DIRECTORY_SEPARATOR;
        $fullPath = $path;
        if (strpos($path, $prefix) !== 0 && strpos($path, 'storage') === 0) {
            $fullPath = $prefix . $path;
        }

        $files = [];
        if (is_dir($fullPath)) {
            $it = new DirectoryIterator($fullPath);
            foreach ($it as $f) {
                if ($f->isFile() && strtolower($f->getExtension()) === 'wav') {
                    $files[] = $f->getPathname();
                }
            }
        } elseif (is_file($fullPath)) {
            $files = [$fullPath];
        } else {
            return ['error' => 'Path not found: ' . $path];
        }

        sort($files);
        $results = [];

        foreach ($files as $wavPath) {
            $name = basename($wavPath);
            $size = filesize($wavPath);
            if ($size < 44) {
                $results[] = ['file' => $name, 'valid' => false, 'error' => 'File too small for WAV header (< 44 bytes)', 'size' => $size];
                continue;
            }
            
            $fh = @fopen($wavPath, 'rb');
            if (!$fh) {
                $results[] = ['file' => $name, 'valid' => false, 'error' => 'Cannot open file', 'size' => $size];
                continue;
            }
            
            $header = fread($fh, 44);
            fclose($fh);
            
            $errors = [];
            $info = [];
            
            // RIFF header check
            if (substr($header, 0, 4) !== 'RIFF') {
                $errors[] = 'Missing RIFF magic';
            }
            $riffSize = unpack('V', substr($header, 4, 4))[1];
            if (substr($header, 8, 4) !== 'WAVE') {
                $errors[] = 'Missing WAVE format';
            }
            
            // fmt chunk
            if (substr($header, 12, 4) !== 'fmt ') {
                $errors[] = 'Missing fmt chunk';
            }
            $fmtSize = unpack('V', substr($header, 16, 4))[1];
            $audioFormat = unpack('v', substr($header, 20, 2))[1];
            $numChannels = unpack('v', substr($header, 22, 2))[1];
            $sampleRate = unpack('V', substr($header, 24, 4))[1];
            $byteRate = unpack('V', substr($header, 28, 4))[1];
            $blockAlign = unpack('v', substr($header, 32, 2))[1];
            $bitsPerSample = unpack('v', substr($header, 34, 2))[1];
            
            if ($audioFormat !== 1) {
                $errors[] = 'Not PCM format (format=' . $audioFormat . ')';
            }
            
            // data chunk
            if (substr($header, 36, 4) !== 'data') {
                $errors[] = 'Missing data chunk';
            }
            $dataSize = unpack('V', substr($header, 40, 4))[1];
            
            // Validate consistency
            $expectedBlockAlign = $numChannels * ($bitsPerSample / 8);
            if (abs($blockAlign - $expectedBlockAlign) > 0.01) {
                $errors[] = 'block_align inconsistent';
            }
            $expectedByteRate = $sampleRate * $blockAlign;
            if ($byteRate !== $expectedByteRate) {
                $errors[] = 'byte_rate inconsistent';
            }
            $expectedDataSize = $riffSize - 36;
            if ($dataSize > $size - 44) {
                $errors[] = 'data chunk larger than file';
            }
            
            $info = [
                'audio_format' => $audioFormat === 1 ? 'PCM' : $audioFormat,
                'channels' => $numChannels,
                'sample_rate' => $sampleRate,
                'bits_per_sample' => $bitsPerSample,
                'byte_rate' => $byteRate,
                'block_align' => $blockAlign,
                'data_size' => $dataSize,
                'riff_size' => $riffSize,
            ];
            
            $results[] = [
                'file' => $name,
                'size' => $size,
                'valid' => empty($errors),
                'errors' => empty($errors) ? null : $errors,
                'info' => $info,
            ];
        }

        $elapsed = round(microtime(true) - $start, 3);
        return [
            'files_checked' => count($files),
            'valid_count' => count(array_filter($results, fn($r) => $r['valid'])),
            'invalid_count' => count(array_filter($results, fn($r) => !$r['valid'])),
            'elapsed_seconds' => $elapsed,
            'results' => $results,
        ];
    }
}
