<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_weather_aqi = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'weather_aqi',
    'description' => 'Fetch real-time air quality index (AQI) and pollutant data from the free Open-Meteo Air Quality API (no API key required). Accepts a city name (uses geocoding) or explicit lat/lon. Returns European AQI, US AQI, PM2.5, PM10, NO2, O3, SO2, CO levels with human-readable quality descriptions. First environmental/air quality data capability.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'city' => 
        array (
          'type' => 'string',
          'description' => 'City name (e.g. London, Tokyo).',
        ),
        'latitude' => 
        array (
          'type' => 'number',
          'description' => 'Explicit latitude.',
        ),
        'longitude' => 
        array (
          'type' => 'number',
          'description' => 'Explicit longitude.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (5-30). Default: 15.',
        ),
      ),
    ),
  ),
);

if (! function_exists('weather_aqi')) {
    function weather_aqi($city = null, $latitude = null, $longitude = null, $timeout = null)
    {
        // Air Quality Index from Open-Meteo
        $city=isset($city)?(string)$city:'';
        $lat=isset($latitude)?(float)$latitude:null;
        $lon=isset($longitude)?(float)$longitude:null;
        $t=isset($timeout)?min(max((int)$t,5),30):15;

        if($city!==''){
            $geo=@file_get_contents("https://geocoding-api.open-meteo.com/v1/search?name=".urlencode($city)."&count=1",false,stream_context_create(['http'=>['timeout'=>$t]]));
            if($geo){$gd=json_decode($geo,true);if($gd&&isset($gd['results'][0])){$lat=$gd['results'][0]['latitude'];$lon=$gd['results'][0]['longitude'];}}
        }
        if($lat===null||$lon===null)return['error'=>'Location required'];

        $url="https://air-quality-api.open-meteo.com/v1/air-quality?latitude={$lat}&longitude={$lon}&current=european_aqi,us_aqi,pm2_5,pm10,nitrogen_dioxide,ozone,sulphur_dioxide,carbon_monoxide&timezone=auto";
        $resp=@file_get_contents($url,false,stream_context_create(['http'=>['timeout'=>$t]]));
        if(!$resp)return['error'=>'AQI fetch failed'];

        $d=json_decode($resp,true);
        if(!$d||!isset($d['current']))return['error'=>'Invalid response'];

        $c=$d['current'];
        $aqi_desc=function($v){if($v===null)return'none';if($v<=50)return'Good';if($v<=100)return'Moderate';if($v<=150)return'Unhealthy for Sensitive';if($v<=200)return'Unhealthy';if($v<=300)return'Very Unhealthy';return'Hazardous';};

        return['success'=>true,
            'location'=>['city'=>$city?:'custom',lat=>$lat,lon=>$lon],
            'time'=>$c['time']??'',
            'european_aqi'=>['value'=>$c['european_aqi']??null,'description'=>$aqi_desc($c['european_aqi']??0)],
            'us_aqi'=>['value'=>$c['us_aqi']??null,'description'=>$aqi_desc($c['us_aqi']??0)],
            'pollutants'=>[
                'pm2_5'=>['ugm3'=>$c['pm2_5']??null,'description'=>$c['pm2_5']?($c['pm2_5']<=15?'Good':($c['pm2_5']<=35?'Moderate':'Poor')):''],
                'pm10'=>['ugm3'=>$c['pm10']??null],
                'no2'=>['ugm3'=>$c['nitrogen_dioxide']??null],
                'o3'=>['ugm3'=>$c['ozone']??null],
                'so2'=>['ugm3'=>$c['sulphur_dioxide']??null],
                'co'=>['ugm3'=>$c['carbon_monoxide']??null],
            ],
            'dominant_pollutant'=>function_exists('array_search')?array_search(max($c['pm2_5']??0,$c['pm10']??0,$c['nitrogen_dioxide']??0,$c['ozone']??0,$c['sulphur_dioxide']??0),[$c['pm2_5']??0,$c['pm10']??0,$c['nitrogen_dioxide']??0,$c['ozone']??0,$c['sulphur_dioxide']??0]):null,
        ];
    }
}
