<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_web_form_submitter = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'web_form_submitter',
    'description' => 'Fetch a URL, parse all HTML forms using DOMDocument/DOMXPath, automatically detect CSRF tokens and hidden fields, fill in user-specified field values, and submit the form via HTTP POST or GET. Handles input, textarea, select, checkbox, radio, and hidden fields. Resolves relative action URLs. Returns the submission response with status code, headers, and body. First web automation/bot capability in the ecosystem — programmatically interact with web forms. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'url' => 
        array (
          'type' => 'string',
          'description' => 'The URL of the page containing the form to fill and submit.',
        ),
        'form_index' => 
        array (
          'type' => 'integer',
          'description' => 'Which form on the page to use (0-indexed, default: 0).',
        ),
        'fields' => 
        array (
          'type' => 'object',
          'description' => 'Associative object mapping field names to values to fill in. E.g. {"username": "test", "password": "secret"}. Hidden fields and CSRF tokens are auto-detected and included.',
        ),
        'submit_button' => 
        array (
          'type' => 'string',
          'description' => 'Name of the submit button to \'click\' (default: auto-detect the first submit button).',
        ),
        'override_method' => 
        array (
          'type' => 'string',
          'description' => 'Override the form\'s HTTP method (\'POST\' or \'GET\'). Default: use the form\'s method attribute.',
        ),
        'override_action' => 
        array (
          'type' => 'string',
          'description' => 'Override the form\'s action URL. Default: use the form\'s action attribute (resolved relative to page URL).',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'HTTP timeout in seconds (5-40, default: 20).',
        ),
        'max_redirects' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum redirects to follow (0-20, default: 5).',
        ),
        'preview_only' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, parse and return form structure without submitting (default: false).',
        ),
      ),
      'required' => 
      array (
        0 => 'url',
      ),
    ),
  ),
);

if (! function_exists('web_form_submitter')) {
    function web_form_submitter($url, $form_index = null, $fields = null, $submit_button = null, $override_method = null, $override_action = null, $timeout = null, $max_redirects = null, $preview_only = null)
    {
        // Fetch the page
        $timeout = $timeout ?? 20;
        $max_redirects = $max_redirects ?? 5;

        $context = stream_context_create([
            'http' => [
                'method' => 'GET',
                'timeout' => $timeout,
                'max_redirects' => $max_redirects,
                'header' => "User-Agent: self-bootstrapping-agent/1.0\r\nAccept: text/html,application/xhtml+xml\r\n",
                'ignore_errors' => true,
            ]
        ]);

        $html = @file_get_contents($url, false, $context);

        if ($html === false) {
            return [
                'success' => false,
                'error' => 'Failed to fetch URL: ' . $url,
                'url' => $url,
            ];
        }

        // Parse HTML
        $dom = new DOMDocument();
        libxml_use_internal_errors(true);
        $dom->loadHTML($html, LIBXML_NOERROR | LIBXML_NOWARNING);
        libxml_clear_errors();

        $xpath = new DOMXPath($dom);

        // Find all forms
        $forms = $dom->getElementsByTagName('form');
        $form_count = $forms->length;

        if ($form_count === 0) {
            return [
                'success' => false,
                'error' => 'No forms found on the page.',
                'url' => $url,
                'form_count' => 0,
            ];
        }

        $form_index = (int)($form_index ?? 0);
        if ($form_index >= $form_count) {
            return [
                'success' => false,
                'error' => "Form index $form_index out of range. Page has $form_count form(s).",
                'url' => $url,
                'form_count' => $form_count,
            ];
        }

        $form = $forms->item($form_index);

        // Extract form attributes
        $form_action = $form->getAttribute('action');
        $form_method = strtoupper($form->getAttribute('method') ?: 'GET');
        $form_enctype = $form->getAttribute('enctype') ?: 'application/x-www-form-urlencoded';
        $form_id = $form->getAttribute('id') ?: '(no id)';
        $form_name = $form->getAttribute('name') ?: '(no name)';

        // Resolve action URL relative to page URL
        if (empty($form_action) || $form_action === '') {
            $form_action = $url;
        } elseif ($form_action[0] === '/') {
            $parsed = parse_url($url);
            $form_action = ($parsed['scheme'] ?? 'https') . '://' . ($parsed['host'] ?? '') . $form_action;
        } elseif (!preg_match('#^https?://#i', $form_action)) {
            // Relative URL
            $base = preg_replace('#/[^/]*$#', '/', $url);
            $form_action = $base . $form_action;
        }

        // Use overrides if provided
        $action_url = $override_action ?? $form_action;
        $method = strtoupper($override_method ?? $form_method);

        // Extract all form fields
        $all_fields = [];
        $field_details = [];
        $csrf_fields = [];
        $submit_buttons = [];
        $hidden_fields = [];

        // Known CSRF token field names
        $csrf_patterns = ['_token', 'csrf_token', 'authenticity_token', '__RequestVerificationToken',
            'csrf', '_csrf', '_csrf_token', 'xsrf_token', 'nonce', '_wpnonce', 'form_key'];

        // Helper to check CSRF
        $is_csrf = function($name) use ($csrf_patterns) {
            $lower = strtolower($name);
            foreach ($csrf_patterns as $pat) {
                if ($lower === strtolower($pat) || strpos($lower, 'csrf') !== false || strpos($lower, 'token') !== false) {
                    return true;
                }
            }
            return false;
        };

        // Collect <input> elements
        $inputs = $xpath->query('.//input', $form);
        foreach ($inputs as $input) {
            $name = $input->getAttribute('name');
            $type = strtolower($input->getAttribute('type') ?: 'text');
            $value = $input->getAttribute('value');
            
            if ($name === '') continue;
            
            $info = [
                'name' => $name,
                'type' => $type,
                'value' => $value,
            ];
            
            if ($type === 'hidden') {
                $hidden_fields[$name] = $value;
                $field_details[] = $info;
                if ($is_csrf($name)) {
                    $csrf_fields[$name] = $value;
                }
            } elseif ($type === 'submit' || $type === 'image') {
                $submit_buttons[] = $info;
            } elseif ($type === 'checkbox' || $type === 'radio') {
                $checked = $input->hasAttribute('checked');
                $info['checked'] = $checked;
                $field_details[] = $info;
            } else {
                $field_details[] = $info;
            }
        }

        // Collect <button> elements (modern submit buttons)
        $buttons = $xpath->query('.//button', $form);
        foreach ($buttons as $btn) {
            $btn_type = strtolower($btn->getAttribute('type') ?: 'submit');
            $btn_name = $btn->getAttribute('name');
            $btn_value = $btn->getAttribute('value') ?: trim($btn->textContent);
            
            if ($btn_type === 'submit') {
                $submit_buttons[] = [
                    'name' => $btn_name ?: '',
                    'type' => 'button-submit',
                    'value' => $btn_value,
                    'tag' => 'button',
                ];
            }
        }

        // Collect textareas
        $textareas = $xpath->query('.//textarea', $form);
        foreach ($textareas as $ta) {
            $name = $ta->getAttribute('name');
            if ($name === '') continue;
            $value = $ta->textContent;
            $field_details[] = [
                'name' => $name,
                'type' => 'textarea',
                'value' => $value,
            ];
        }

        // Collect selects
        $selects = $xpath->query('.//select', $form);
        foreach ($selects as $sel) {
            $name = $sel->getAttribute('name');
            if ($name === '') continue;
            $options = [];
            $selected_value = null;
            $option_nodes = $xpath->query('.//option', $sel);
            foreach ($option_nodes as $opt) {
                $opt_val = $opt->getAttribute('value');
                $opt_text = trim($opt->textContent);
                $is_selected = $opt->hasAttribute('selected');
                $options[] = ['value' => $opt_val, 'text' => $opt_text, 'selected' => $is_selected];
                if ($is_selected) $selected_value = $opt_val;
            }
            $field_details[] = [
                'name' => $name,
                'type' => 'select',
                'value' => $selected_value ?? ($options[0]['value'] ?? ''),
                'options' => $options,
            ];
        }

        // Determine submit button
        $submit_name = null;
        $submit_value = null;
        if (!empty($submit_button)) {
            $submit_name = $submit_button;
            foreach ($submit_buttons as $sb) {
                if ($sb['name'] === $submit_button || (empty($sb['name']) && $sb['value'] === $submit_button)) {
                    $submit_value = $sb['value'];
                    break;
                }
            }
        } elseif (!empty($submit_buttons)) {
            $submit_name = $submit_buttons[0]['name'] ?: null;
            $submit_value = $submit_buttons[0]['value'] ?? 'Submit';
        }

        // Build the final field set
        // 1. Start with hidden fields
        foreach ($hidden_fields as $hname => $hval) {
            $all_fields[$hname] = $hval;
        }

        // 2. Add select defaults
        foreach ($field_details as $fd) {
            if ($fd['type'] === 'select' && !empty($fd['value']) && !empty($fd['name'])) {
                $all_fields[$fd['name']] = $fd['value'];
            }
        }

        // 3. Merge user-specified fields (overrides defaults)
        $user_fields = $fields ?? [];
        foreach ($user_fields as $fname => $fval) {
            $all_fields[$fname] = $fval;
        }

        // 4. Add submit button
        if ($submit_name !== null && $submit_name !== '') {
            $all_fields[$submit_name] = $submit_value ?? 'Submit';
        }

        // Build form structure report
        $form_structure = [
            'form_index' => $form_index,
            'form_count' => $form_count,
            'form_id' => $form_id,
            'form_name' => $form_name,
            'action' => $form_action,
            'resolved_action' => $action_url,
            'method' => $method,
            'enctype' => $form_enctype,
            'fields_found' => count($field_details),
            'field_details' => $field_details,
            'hidden_fields' => array_keys($hidden_fields),
            'csrf_tokens_detected' => !empty($csrf_fields) ? array_keys($csrf_fields) : [],
            'submit_buttons' => $submit_buttons,
            'final_fields' => $all_fields,
        ];

        // Preview mode — just return form structure
        if ($preview_only ?? false) {
            return [
                'success' => true,
                'preview' => true,
                'url' => $url,
                'form_structure' => $form_structure,
            ];
        }

        // Submit the form
        $post_data = http_build_query($all_fields);

        if ($method === 'GET') {
            $sep = (strpos($action_url, '?') === false) ? '?' : '&';
            $submit_url = $action_url . $sep . $post_data;
            
            $submit_context = stream_context_create([
                'http' => [
                    'method' => 'GET',
                    'timeout' => $timeout,
                    'max_redirects' => $max_redirects,
                    'header' => "User-Agent: self-bootstrapping-agent/1.0\r\nAccept: text/html,application/xhtml+xml\r\n",
                    'ignore_errors' => true,
                ]
            ]);
            
            $response_body = @file_get_contents($submit_url, false, $submit_context);
        } else {
            $submit_context = stream_context_create([
                'http' => [
                    'method' => 'POST',
                    'timeout' => $timeout,
                    'max_redirects' => $max_redirects,
                    'header' => "User-Agent: self-bootstrapping-agent/1.0\r\n" .
                                "Accept: text/html,application/xhtml+xml\r\n" .
                                "Content-Type: application/x-www-form-urlencoded\r\n" .
                                "Content-Length: " . strlen($post_data) . "\r\n",
                    'content' => $post_data,
                    'ignore_errors' => true,
                ]
            ]);
            
            $response_body = @file_get_contents($action_url, false, $submit_context);
        }

        // Parse response headers
        $response_status = 'unknown';
        $response_headers_out = [];
        if (isset($http_response_header)) {
            foreach ($http_response_header as $h) {
                if (stripos($h, 'HTTP/') === 0) {
                    if (preg_match('#HTTP/\d\.\d\s+(\d+)#', $h, $m)) {
                        $response_status = (int)$m[1];
                    }
                } else {
                    $parts = explode(':', $h, 2);
                    if (count($parts) === 2) {
                        $response_headers_out[strtolower(trim($parts[0]))] = trim($parts[1]);
                    }
                }
            }
        }

        return [
            'success' => true,
            'preview' => false,
            'url' => $url,
            'form_structure' => $form_structure,
            'submission' => [
                'action_url' => $action_url,
                'method' => $method,
                'fields_sent' => array_keys($all_fields),
                'fields_count' => count($all_fields),
            ],
            'response' => [
                'status_code' => $response_status,
                'headers' => $response_headers_out,
                'body_length' => strlen($response_body ?: ''),
                'body_preview' => mb_substr($response_body ?: '', 0, 2000),
                'body' => mb_substr($response_body ?: '', 0, 100000),
            ],
        ];
    }
}
