<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_web_search = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'web_search',
    'description' => 'Search the web using the free DuckDuckGo Instant Answer API (no API key required). Returns abstracts, definitions, infobox data (structured facts), related topics, and web results. Handles disambiguation, images, and source attribution. First web search capability in the ecosystem — queries the open web and returns structured knowledge. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'query' => 
        array (
          'type' => 'string',
          'description' => 'Search query (e.g. \'PHP programming language\', \'Albert Einstein\', \'Eiffel Tower\').',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (5-30, default: 15).',
        ),
      ),
      'required' => 
      array (
        0 => 'query',
      ),
    ),
  ),
);

if (! function_exists('web_search')) {
    function web_search($query, $timeout = null)
    {
        $query = trim($query ?? '');
        $timeout = (int)($timeout ?? 15);

        if (empty($query)) {
            return ['success' => false, 'error' => 'Search query is required.'];
        }

        // DuckDuckGo Instant Answer API — free, no key required
        $url = 'https://api.duckduckgo.com/?q=' . urlencode($query)
            . '&format=json&no_html=1&skip_disambig=1&t=self-bootstrapping-agent';

        $context = stream_context_create([
            'http' => [
                'method' => 'GET',
                'timeout' => $timeout,
                'header' => "User-Agent: self-bootstrapping-agent/1.0\r\nAccept: application/json\r\n",
                'ignore_errors' => true,
            ]
        ]);

        $response = @file_get_contents($url, false, $context);

        if ($response === false) {
            return ['success' => false, 'error' => 'Failed to reach DuckDuckGo API.'];
        }

        $data = json_decode($response, true);

        if ($data === null) {
            return ['success' => false, 'error' => 'Failed to parse API response.'];
        }

        // Parse results
        $abstract = $data['Abstract'] ?? '';
        $abstract_text = $data['AbstractText'] ?? '';
        $abstract_source = $data['AbstractSource'] ?? '';
        $abstract_url = $data['AbstractURL'] ?? '';
        $heading = $data['Heading'] ?? '';
        $answer = $data['Answer'] ?? '';
        $answer_type = $data['AnswerType'] ?? '';
        $image = $data['Image'] ?? '';
        $definition = $data['Definition'] ?? '';
        $definition_source = $data['DefinitionSource'] ?? '';

        // Related topics
        $related = [];
        if (isset($data['RelatedTopics']) && is_array($data['RelatedTopics'])) {
            foreach ($data['RelatedTopics'] as $topic) {
                if (is_array($topic)) {
                    // Sometimes topics are nested with a "Topics" key (disambiguation groups)
                    if (isset($topic['Topics'])) {
                        foreach ($topic['Topics'] as $subtopic) {
                            $related[] = [
                                'text' => $subtopic['Text'] ?? '',
                                'url' => $subtopic['FirstURL'] ?? '',
                                'icon' => $subtopic['Icon']['URL'] ?? null,
                            ];
                        }
                    } else {
                        $related[] = [
                            'text' => $topic['Text'] ?? '',
                            'url' => $topic['FirstURL'] ?? '',
                            'icon' => $topic['Icon']['URL'] ?? null,
                        ];
                    }
                }
            }
        }

        // Infobox (structured data)
        $infobox = null;
        if (isset($data['Infobox']) && is_array($data['Infobox'])) {
            $infobox = [
                'content' => [],
                'meta' => [],
            ];
            foreach ($data['Infobox']['content'] ?? [] as $item) {
                $infobox['content'][] = [
                    'label' => $item['label'] ?? '',
                    'value' => $item['value'] ?? '',
                    'data_type' => $item['data_type'] ?? '',
                ];
            }
            foreach ($data['Infobox']['meta'] ?? [] as $meta) {
                $infobox['meta'][] = [
                    'label' => $meta['label'] ?? '',
                    'value' => $meta['value'] ?? '',
                ];
            }
        }

        // Results (web results)
        $results = [];
        if (isset($data['Results']) && is_array($data['Results'])) {
            foreach ($data['Results'] as $r) {
                $results[] = [
                    'title' => $r['Text'] ?? '',
                    'url' => $r['FirstURL'] ?? '',
                    'icon' => $r['Icon']['URL'] ?? null,
                ];
            }
        }

        return [
            'success' => true,
            'query' => $query,
            'heading' => $heading ?: null,
            'abstract' => $abstract_text ?: ($abstract ?: null),
            'abstract_source' => $abstract_source ?: null,
            'abstract_url' => $abstract_url ?: null,
            'definition' => $definition ?: null,
            'definition_source' => $definition_source ?: null,
            'answer' => $answer ?: null,
            'answer_type' => $answer_type ?: null,
            'image' => $image ? ('https://duckduckgo.com' . $image) : null,
            'infobox' => $infobox,
            'related_topics_count' => count($related),
            'related_topics' => array_slice($related, 0, 15),
            'results_count' => count($results),
            'results' => $results,
            'api_type' => $data['Type'] ?? 'unknown',
        ];
    }
}
