<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_web_monitor = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'web_monitor',
    'description' => 'Periodically fetch a web page URL, extract its readable text content, diff against the last snapshot stored in SQLite, and report what changed. Like feed_watcher but for arbitrary HTML pages — uses DOMDocument/DOMXPath to strip navigation, scripts, and styles before extracting meaningful content. Computes line-level diffs (additions/removals) between snapshots. Stores full content state in SQLite for cross-session persistence. Never throws — all errors returned as structured data.',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'url' => 
        array (
          'type' => 'string',
          'description' => 'The URL to monitor for changes.',
        ),
        'db_name' => 
        array (
          'type' => 'string',
          'description' => 'SQLite database filename (stored in workspace). Default: \'web_monitor.sqlite\'.',
        ),
        'timeout' => 
        array (
          'type' => 'integer',
          'description' => 'Timeout in seconds (5-30, default: 20).',
        ),
        'max_changes' => 
        array (
          'type' => 'integer',
          'description' => 'Maximum diff lines to report (10-200, default: 50).',
        ),
        'force_refresh' => 
        array (
          'type' => 'boolean',
          'description' => 'If true, store the current content as the new baseline without reporting diff. Default: false.',
        ),
        'selector' => 
        array (
          'type' => 'string',
          'description' => 'Optional CSS-style selector or element ID to scope monitoring to a specific part of the page (e.g. \'main\', \'article\', \'#content\'). Default: extracts body text.',
        ),
      ),
      'required' => 
      array (
        0 => 'url',
      ),
    ),
  ),
);

if (! function_exists('web_monitor')) {
    function web_monitor($url, $db_name = null, $timeout = null, $max_changes = null, $force_refresh = null, $selector = null)
    {
        // Web Page Monitor - fetch, diff, and store page content changes
        $url = isset($url) ? (string)$url : '';
        if ($url === '') return ['error' => 'URL required'];

        $db_name = isset($db_name) ? (string)$db_name : 'web_monitor.sqlite';
        $timeout = isset($timeout) ? min(max((int)$timeout, 5), 30) : 20;
        $max_changes = isset($max_changes) ? min(max((int)$max_changes, 10), 200) : 50;
        $force_refresh = isset($force_refresh) ? (bool)$force_refresh : false;

        $ws = realpath(__DIR__ . '/../../workspace');
        $db_path = $ws . '/' . $db_name;

        try {
            // Fetch page
            $page = @file_get_contents($url, false, stream_context_create([
                'http' => ['timeout' => $timeout, 'header' => "User-Agent: PHP-Web-Monitor/1.0\r\n"],
                'ssl' => ['verify_peer' => false, 'verify_peer_name' => false],
            ]));
            
            if ($page === false) return ['error' => 'Failed to fetch URL', 'url' => $url];
            
            $fetch_time = date('Y-m-d H:i:s');
            $status_code = '200';
            $content_type = '';
            
            // Extract text content using DOM
            $doc = new DOMDocument();
            @$doc->loadHTML('<?xml encoding="utf-8" ?>' . $page);
            $xpath = new DOMXPath($doc);
            
            // Remove scripts, styles, nav
            foreach (['script', 'style', 'nav', 'footer', 'header', 'aside'] as $tag) {
                foreach ($xpath->query("//{$tag}") as $node) {
                    $node->parentNode->removeChild($node);
                }
            }
            
            // If selector specified, try to scope
            $content = '';
            if (isset($selector) && $selector !== '') {
                $sel = $selector;
                if ($sel[0] === '#') {
                    $nodes = $xpath->query("//*[@id='" . substr($sel, 1) . "']");
                } elseif ($sel[0] === '.') {
                    $nodes = $xpath->query("//*[contains(@class, '" . substr($sel, 1) . "')]");
                } else {
                    $nodes = $xpath->query("//{$sel}");
                }
                if ($nodes && $nodes->length > 0) {
                    $content = $nodes->item(0)->textContent;
                }
            }
            
            if ($content === '') {
                $body = $xpath->query('//body');
                $content = $body->length > 0 ? $body->item(0)->textContent : $page;
            }
            
            // Clean text
            $content = preg_replace('/\s+/', ' ', $content);
            $content = preg_replace('/[^\P{C}\n]+/u', '', $content);
            $content = trim($content);
            
            if (strlen($content) > 50000) $content = substr($content, 0, 50000);
            
            // Store/Retrieve from SQLite
            $pdo = new PDO("sqlite:{$db_path}");
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $pdo->exec("CREATE TABLE IF NOT EXISTS snapshots (
                url TEXT PRIMARY KEY,
                content TEXT,
                fetched_at TEXT
            )");
            
            $stmt = $pdo->prepare("SELECT content, fetched_at FROM snapshots WHERE url = ?");
            $stmt->execute([$url]);
            $previous = $stmt->fetch(PDO::FETCH_ASSOC);
            
            if ($force_refresh || !$previous) {
                // Store as baseline
                $pdo->prepare("INSERT OR REPLACE INTO snapshots (url, content, fetched_at) VALUES (?, ?, ?)")
                    ->execute([$url, $content, $fetch_time]);
                
                return [
                    'success' => true,
                    'url' => $url,
                    'status' => 'baseline_recorded',
                    'content_length' => strlen($content),
                    'fetched_at' => $fetch_time,
                ];
            }
            
            // Compute diff
            $old_lines = explode("\n", trim($previous['content']));
            $new_lines = explode("\n", trim($content));
            
            // Simple LCS-based diff
            $old_map = array_flip($old_lines);
            $additions = [];
            $removals = [];
            $unchanged = [];
            
            foreach ($new_lines as $i => $line) {
                $line = trim($line);
                if ($line === '') continue;
                if (isset($old_map[$line])) {
                    $unchanged[] = $line;
                } else {
                    $additions[] = $line;
                }
            }
            
            $new_map = array_flip($new_lines);
            foreach ($old_lines as $i => $line) {
                $line = trim($line);
                if ($line === '') continue;
                if (!isset($new_map[$line])) {
                    $removals[] = $line;
                }
            }
            
            // Store new content
            $pdo->prepare("INSERT OR REPLACE INTO snapshots (url, content, fetched_at) VALUES (?, ?, ?)")
                ->execute([$url, $content, $fetch_time]);
            
            $has_changes = count($additions) > 0 || count($removals) > 0;
            
            return [
                'success' => true,
                'url' => $url,
                'status' => $has_changes ? 'changes_detected' : 'no_changes',
                'fetched_at' => $fetch_time,
                'last_fetched' => $previous['fetched_at'],
                'content_length' => strlen($content),
                'changes' => [
                    'additions' => count($additions),
                    'removals' => count($removals),
                    'unchanged' => count($unchanged),
                ],
                'added_lines' => $has_changes ? array_slice($additions, 0, $max_changes) : null,
                'removed_lines' => $has_changes ? array_slice($removals, 0, $max_changes) : null,
            ];
            
        } catch (\Throwable $e) {
            return ['error' => 'Monitor failed: ' . $e->getMessage()];
        }
    }
}
