<?php

// Generated by make_tool. Do not edit by hand unless you know why.

$toolDefinition_websocket_client = array (
  'type' => 'function',
  'function' => 
  array (
    'name' => 'websocket_client',
    'description' => '[existing tool - keep intact]',
    'parameters' => 
    array (
      'type' => 'object',
      'properties' => 
      array (
        'test' => 
        array (
          'type' => 'string',
        ),
      ),
    ),
  ),
);

if (! function_exists('websocket_client')) {
    function websocket_client($test = null)
    {
        return ['error' => 'websocket_client intact']; 
    }
}
